### ISSUE TITLE
Module build failed: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by JetQin** [ant-design/ant-design#1016]
使用webpack 编译，报错
```
ERROR in ./js/app.js
Module build failed: ReferenceError: window is not defined
    at Object.<anonymous> (/Users/jet/code/js/es6-react/node_modules/rc-tree/lib/TreeNode.js:39:36)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/jet/code/js/es6-react/node_modules/rc-tree/lib/index.js:13:17)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
```

webpack 配置文件如下：
```
var webpack = require('webpack');
var uglifyJsPlugin = webpack.optimize.UglifyJsPlugin;
var OpenBrowserPlugin = require('open-browser-webpack-plugin');

module.exports = {
    entry:'./js/app.js',
    output:{
        path:__dirname,
        filename:'./build/bundle.js'
    },
    module:{
        loaders:[
            {
                test:/\.js[x]?$/,
                exclude:/(node_modules|bower_components)/,
                loader:'babel',
                query:{
                    presets:['es2015','react']
                }
            },
            {
                test:/\.(png|jpg)$/,
                loader:'url-loader?limit=8192'
            },
            {
                test:/\.css$/,
                loader:'style-loader!css-loader?module'
            }
        ]
    },
    plugins:[
        new uglifyJsPlugin({compress:{warnings:false}}),
        new OpenBrowserPlugin({url:'http://localhost:8080'})
    ]
};

```

rc-tree/lib/TreeNode.js:39:36

```
var _util = require('./util');

var browserUa = (0, _util.browser)(window.navigator.userAgent || '');
var ieOrEdge = /.*(IE|Edge).+/.test(browserUa);
// const uaArray = browserUa.split(' ');
```

**Comment by afc163** [comment]
最好给出可重现的仓库。

**Comment by JetQin** [comment]
@afc163  ant.design官网的脚手架上用的是antd-tool 编译，能不能用babel编译，可不可以给个示例文件呀

**Comment by afc163** [comment]
ant-tool 里面就是 babel 。

**Comment by afc163** [comment]
理论上业界的脚手架也都是可以用的：https://github.com/enaqx/awesome-react#boilerplates

**Comment by JetQin** [comment]
编译的时候使用
`browserify js/App.jsx -t babelify --outfile build/bundle.js ` 
只是单纯的引用antd 该如何编译呢？

```
{
  "name": "es6_start",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "atool-build",
    "build": "browserify js/App.jsx -t babelify --outfile build/bundle.js",
    "start": "webpack-dev-server --hot --progress --colors",
  },
  "license": "ISC",
  "babel": {
    "presets": [
      "es2015",
      "react",
      "antd"
    ]
  },
  "dependencies": {
    "antd": "0.12.1",
    "browserify": "^13.0.0",
    "babelify": "^7.2.0",
    "babel-cli": "^6.4.5",
    "babel-core": "~6.0.20",
    "babel-loader": "~6.0.1",
    "babel-preset-es2015": "~6.0.15",
    "babel-preset-react": "~6.0.15",
    "babel-plugin-transform-react-jsx": "~6.3",
    "babel-plugin-antd": "0.2.0",
    "bundle-loader": "^0.5.4",
    "css-loader": "~0.16.0",
    "file-loader": "~0.8.4",
    "history": "^1.17.0",
    "html-webpack-plugin": "~1.6.2",
    "open-browser-webpack-plugin": "0.0.1",
    "react": "~0.14.2",
    "react-dom": "~0.14.2",
    "react-hot-loader": "^1.3.0",
    "react-router": "^1.0.3",
    "style-loader": "~0.12.3",
    "url-loader": "~0.5.6",
    "webpack": "~1.11.0",
    "webpack-dev-server": "^1.10.1",
    "http-server": "~0.8.5",
    "reflux": "^0.3.0"
  },
  "devDependencies": {
    "atool-build": "^0.5.0",
    "babel-plugin-antd": "^0.2.0",
    "babelify": "^7.2.0"
  }
}

```

**Comment by afc163** [comment]
reinstall and try.

**Comment by welljs** [comment]
I got it everything! Can you write English or Russian?
