### ISSUE TITLE
CI with console.error

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#10342]
```
 PASS  components/upload/__tests__/upload.test.js
  ● Console

    console.error node_modules/_jsdom@11.10.0@jsdom/lib/jsdom/virtual-console.js:29
      Error: Error: Response for preflight has invalid HTTP status code 301
          at Object.dispatchError (/Users/afc163/Projects/ant-design/node_modules/_jsdom@11.10.0@jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at EventEmitter.client.on.err (/Users/afc163/Projects/ant-design/node_modules/_jsdom@11.10.0@jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at EventEmitter.emit (events.js:185:15)
          at Request.preflightClient.on.resp (/Users/afc163/Projects/ant-design/node_modules/_jsdom@11.10.0@jsdom/lib/jsdom/living/xhr-utils.js:376:16)
          at Request.emit (events.js:180:13)
          at Request.onRequestResponse (/Users/afc163/Projects/ant-design/node_modules/_request@2.85.0@request/request.js:1068:10)
          at ClientRequest.emit (events.js:180:13)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:540:21)
          at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
          at Socket.socketOnData (_http_client.js:445:20) undefined
```

**Comment by yesmeck** [comment]
Need to mock HTTP requests.
