### ISSUE TITLE
antd 兼容 nodejs 的问题

### ISSUE THREAD

**Issue by silverPanda** [ant-design/ant-design#1109]
我现在在用 koajs 直出 react 应用，结果在执行 node 的时候全部抛出了 antd 库中的错误，例如：
```
Unhandled rejection ReferenceError: window is not defined
    at Object.<anonymous> (/Users/LEO/Desktop/Workspace/node_modules/rc-tree/lib/TreeNode.js:39:36)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/LEO/Desktop/Workspace/node_modules/rc-tree/lib/util.js:19:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/LEO/Desktop/Workspace/node_modules/rc-tree/lib/Tree.js:33:13)
    at Module._compile (module.js:413:34)

```
这一类的没处理 DOM 中的window document 之类的问题........难道我要在 process hander 这些 dom 错误么？ 强迫症要范了

**Comment by silverPanda** [comment]
能否在 antd 中加入 jsdom 这一类的玩意 hack？

**Comment by afc163** [comment]
这个貌似和 https://github.com/ant-design/ant-design/issues/1016 的问题一样。是我们在使用中没有遇到这个问题。

@warmhug rc-tree 的代码有没有优化的空间？

**Comment by afc163** [comment]
如果是服务端渲染，现在暂时不支持。https://github.com/ant-design/ant-design/issues/215

**Comment by silverPanda** [comment]
目前不改antd代码的话，我想到的办法只能在 node 全局环境中用 jsdom hack 一些 window document

**Comment by warmhug** [comment]
https://github.com/react-component/tree/commit/83e9b9e0aae9ec35a2fe518c8ae58ff7f22143ed#diff-85564e24f0c5138a6a78e791c8fe1be0R7

修复了下，麻烦再试试看。

**Comment by afc163** [comment]
@silverPanda

**Comment by afc163** [comment]
这个问题是否修复了？@silverPanda

**Comment by silverPanda** [comment]
已经修复^^
