### ISSUE TITLE
antd server start error

### ISSUE THREAD

**Issue by zxpzxp1** [ant-design/ant-design#11197]
\node_modules\antd-mobile\lib\input-item\CustomKeyboard.js:51
var IS_IOS = /iphone|ipad|ipod/i.test(window.navigator.userAgent);
                                      ^

ReferenceError: window is not defined
    at Object.<anonymous> (E:\鍓嶇\code\react-chat\node_modules\antd-mobile\lib\input-item\CustomKeyboard.js:51:39)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\鍓嶇\code\react-chat\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\鍓嶇\code\react-chat\node_modules\antd-mobile\lib\input-item\CustomInput.js:37:23)

"antd-mobile": "^2.1.11"

**Comment by zxpzxp1** [comment]
starting `babel-node server/server.js` node --exec babel-node server/server.js
