### ISSUE TITLE
Jest error occurred in the <Wave> component

### ISSUE THREAD

**Issue by E-two** [ant-design/ant-design#11868]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
webpack@3.12.0 antd@3.8.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0yyr58y3v0)

### Steps to reproduce
 it("should render right thing and don't change unexpected", () => {
    const { component } = setup();
    const tree = renderer.create(component).toJSON();

    expect(tree).toMatchSnapshot();
  });

### What is expected?
it render right without errors

### What is actually happening?
The above error occurred in the <Wave> component:
    in Wave (created by Button)

    in Button (created by App)

    in div (created by App)

    in App

Consider adding an error boundary to your tree to customize error handling behavior.

Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

---
v3.6.6版本没有这个问题，更新到最新版本出现的

**Comment by E-two** [comment]
But the following error occurred when I tested：
Please see this link:  https://codesandbox.io/s/0yyr58y3v0

this is the errors:
expect(function).not.toThrow()


Expected the function not to throw an error.

Instead, it threw:

  TypeError: node.getAttribute is not a function      

      at Wave._this.bindAnimationEvent (https:/0yyr58y3v0.codesandbox.io/node_modules/antd/lib/_util/wave.js:82:22)

      at Wave.componentDidMount (https:/0yyr58y3v0.codesandbox.io/node_modules/antd/lib/_util/wave.js:124:34)

      at commitLifeCycles (https:/0yyr58y3v0.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6444:22)

      at commitAllLifeCycles (https:/0yyr58y3v0.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7540:7)

      at HTMLUnknownElement.callCallback (https:/0yyr58y3v0.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1899:14)

      at Object.invokeGuardedCallbackDev (https:/0yyr58y3v0.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1937:16)

      at invokeGuardedCallback (https:/0yyr58y3v0.codesandbox.io/node_modules/react-test-renderer/cjs/react-test-
