### ISSUE TITLE
Menu component throws "TypeError: cannot set property width of undefined" in Jest snapshot tests

### ISSUE THREAD

**Issue by marina101** [ant-design/ant-design#12439]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
10.13.6, chrome 69.0.3497.100 (Official Build) (64-bit), "antd": "^3.9.3",     "react": "^16.5.2",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6j5nvo4pqk)

### Steps to reproduce
1) run the jest snapshot test
Running the jest snapshot test fails with the following error: TypeError: Cannot set property 'width' of undefined

### What is expected?
The test should pass / show new snapshot

### What is actually happening?
The test fails and produces this stacktrace:

```console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6884
      The above error occurred in the <DOMWrap> component:
          in DOMWrap (created by SubPopupMenu)
          in SubPopupMenu (created by Connect(SubPopupMenu))
          in Connect(SubPopupMenu) (created by Menu)
          in Provider (created by Menu)
          in Menu (created by Menu)
          in Menu (at App.jsx:23)
          in div (created by Basic)
          in Basic (created by Adapter)
          in Adapter (at App.jsx:19)
          in div (created by BasicLayout)
          in BasicLayout (created by Adapter)
          in Adapter (at App.jsx:18)
          in Router (created by BrowserRouter)
          in BrowserRouter (at App.jsx:17)
          in App (at App.spec.js:9)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● App Snapshot › renders

    TypeError: Cannot set property 'width' of undefined

      at DOMWrap._this.setChildrenWidthAndResize (node_modules/rc-menu/lib/DOMWrap.js:147:54)
      at DOMWrap.componentDidMount (node_modules/rc-menu/lib/DOMWrap.js:195:10)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7019:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8234:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2312:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2362:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2411:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8404:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9769:3)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9697:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9601:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9573:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9461:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9256:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9865:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9892:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9903:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10428:5)
      at Object.test (src/test/__tests__/App.spec.js:8:51)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)```

---
As soon as I added the antd menu, these problems started. It looks like it might be related to how the component interacts with: 
/node_modules/rc-menu/lib/DOMWrap.js


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by picodoth** [comment]
@marina101 is there a repo that I can checkout somewhere?

**Comment by marina101** [comment]
@picodoth: I can't link you to the repo because its a private repo, but if you checkout the code sandbox example, it reproduces the error.

**Comment by picodoth** [comment]
a patch fix was made in [rc-menu@7.4.11](https://github.com/react-component/menu/commit/a8f053e4e35dc89f00e99823b9f29640c8fe8a1e), can you reinstall antd locally to try it again?

**Comment by marina101** [comment]
I uninstalled and reinstalled antd, and also explicitly installed rc-menu and updated its version to 7.4.1

Now getting the following error/stacktrace:
```TypeError: elem.getBoundingClientRect is not a function

      at getWidth (node_modules/rc-menu/lib/util.js:69:23)
      at node_modules/rc-menu/lib/DOMWrap.js:149:35
          at Array.map (<anonymous>)
      at DOMWrap._this.setChildrenWidthAndResize (node_modules/rc-menu/lib/DOMWrap.js:148:38)
      at DOMWrap.componentDidMount (node_modules/rc-menu/lib/DOMWrap.js:195:10)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7019:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8234:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2312:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2362:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2411:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8404:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9769:3)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9697:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9601:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9573:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9461:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9256:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9865:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9892:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9903:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10428:5)
      at Object.test (src/test/__tests__/App.spec.js:13:51)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>

  App Snapshot
    ✕ renders (33ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.823s, estimated 4s
Ran all test suites related to changed files.

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6884
    The above error occurred in the <DOMWrap> component:
        in DOMWrap (created by SubPopupMenu)
        in SubPopupMenu (created by Connect(SubPopupMenu))
        in Connect(SubPopupMenu) (created by Menu)
        in Provider (created by Menu)
        in Menu (created by Menu)
        in Menu (at MainMenu.jsx:8)
        in Unknown (at App.jsx:22)
        in div (created by Basic)
        in Basic (created by Adapter)
        in Adapter (at App.jsx:18)
        in div (created by BasicLayout)
        in BasicLayout (created by Adapter)
        in Adapter (at App.jsx:17)
        in Router (created by BrowserRouter)
        in BrowserRouter (at App.jsx:16)
        in App (at App.spec.js:14)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.```

**Comment by picodoth** [comment]
Please try rc-menu@7.4.12

**Comment by marina101** [comment]
I use enzyme tests as well, but the fact that this doesn't work with Jest is a bug. 
Tried with 7.4.12, still having an error. Now with this stacktrace:


```TypeError: Cannot read property 'length' of undefined

      at N (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:8:171)
      at f (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:7:472)
      at C (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:8:22)
      at J (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:3:441)
      at v.observe (node_modules/mutationobserver-shim/dist/mutationobserver.min.js:9:196)
      at DOMWrap.componentDidMount (node_modules/rc-menu/lib/DOMWrap.js:217:31)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7019:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8234:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2312:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2362:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2411:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8404:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9769:3)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9697:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9601:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9573:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9461:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9256:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9865:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9892:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9903:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10428:5)
      at Object.test (src/test/__tests__/App.spec.js:13:51)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  App Snapshot
    ✕ renders (76ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        7.257s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6884
    The above error occurred in the <DOMWrap> component:
        in DOMWrap (created by SubPopupMenu)
        in SubPopupMenu (created by Connect(SubPopupMenu))
        in Connect(SubPopupMenu) (created by Menu)
        in Provider (created by Menu)
        in Menu (created by Menu)
        in Menu (at MainMenu.jsx:8)
        in Unknown (at App.jsx:22)
        in div (created by Basic)
        in Basic (created by Adapter)
        in Adapter (at App.jsx:18)
        in div (created by BasicLayout)
        in BasicLayout (created by Adapter)
        in Adapter (at App.jsx:17)
        in Router (created by BrowserRouter)
        in BrowserRouter (at App.jsx:16)
        in App (at App.spec.js:14)```

**Comment by picodoth** [comment]
rc-menu and antd are also tested with enzyme + jest, we didn't see this kind of failure. My guess it's not about Jest, but seems like react-test-renderer does not depend on jsdom, that's why we're seeing these issues. Is it easy for you to use enzyme + jest to testing for the related files?

**Comment by zombieJ** [comment]
Hi @marina101 , rc component which antd deps on use some DOM native props. This means `react-test-renderer` can not handle that.
If you want to test on this, pls use enzyme instead. You can ref follow sample:
* https://github.com/ant-design/ant-design/tree/master/tests
* https://github.com/react-component/tree/tree/master/tests
