### ISSUE TITLE
New site issues to fix

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1259]
- [x] 高亮代码逻辑放到后端编译过程，不然站点会很卡。
- [x] 演示代码区域去掉 Collapse ，交互和视觉按原来的来。
- [x] 首页按钮动画有问题。
- [x] https://github.com/benjycui/react-github-button/issues/1
- [x] 响应式。
- [x] 演示框高亮效果。
- [x] router 优化
- [x] 组件页浮动锚点缺少高亮
- [x] 组件页浮动锚点快速向上滚动时，回位会延时
- [x] 单页 GA 支持：https://github.com/ant-design/ant-design/blob/master/site/templates/layout.html#L88-L100
- [x] 原有文档页内链接排查修复 https://github.com/ant-design/ant-design/commit/5cbc8fc814129fe69e9555371406d3e1d2dc4e7d
- [x] 去掉 common.js ，单入口不需要提公共依赖
- <del>[ ] 加载了两次 ga.js 和 api.github.com 的数据。</del>均是 307 跳转导致
- [x] 移除网站对 TweenMax 和 jQuery 的依赖。https://github.com/ant-design/ant-design/commit/1b9a7b3dbe86dfb178e8ae6c4a38d952d7716fa0
- [x] iframe demo 挂了。(fixed in https://github.com/ant-design/antd-md-loader/commit/45b7c75cffda9542266082b251ae904c94203b0d , need publish)
- [x] 废弃代码和依赖移除 #1309 https://github.com/ant-design/ant-design/commit/fccc268fc0c548c5d56f4c26c345fe234b13d22f
- [x] iframe code 里的 react-router 更换 cdn 到国内 https://github.com/ant-design/antd-md-loader/commit/b4314d1dbdeceb4e3a6c20dfb3108567656d280a
- [x] demo 的 hidden 字段失效 https://github.com/ant-design/ant-design/commit/202f01c2926744a9d6648e7c7d04c3586416b244
- [x] index.md 里的代码高亮失效 [```html](http://127.0.0.1:8001/#/components/icon?scrollTo=%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8&_k=fmdpls) https://github.com/ant-design/ant-design/commit/24ade9178d0148df9fb4db621afdc6c6eb6ac0c7
- [x] http://127.0.0.1:8001/#/docs/spec/introduce 页面题图的居中样式代码丢失 https://github.com/benjycui/jsonml-to-react-component/commit/4c2896f4b82c202aa5b15b7159b829a2c26a69b1
- [x] `npm WARN jsonml-to-react-component@0.1.10 requires a peer of react@~0.15.0 but none was installed.`
- [x] upload 页面本地无法上传，`upload.do` 不存在。 Waiting for: https://github.com/dora-js/dora/issues/62
- [x] 404 页面 https://github.com/ant-design/ant-design/pull/1518
- [x] 代码高亮问题 https://github.com/ant-design/ant-design/pull/1479
- [x] 首页滚屏下去的导航样式变化失效了。https://github.com/ant-design/ant-design/commit/36af97c20ba46e010fa437ceefcd8e9e61843c2a
- [x] `a` to `Link` see: https://github.com/ant-design/ant-design/commit/5cbc8fc814129fe69e9555371406d3e1d2dc4e7d#commitcomment-17312899 done: https://github.com/ant-design/ant-design/commit/b81034cc132fbd8a07b39551b113e52ce595ffba
- [x] 左侧菜单没有高亮。https://github.com/ant-design/ant-design/commit/a621522c56257f8f4e69bbc4b0bfe68233e0d018
- [x] `component/introduce` => `docs/react/introduce` https://github.com/ant-design/ant-design/commit/c23d724ab9e68b14a60ec0591397a435dab6e0f5

持续补充ing...

**Comment by afc163** [comment]
```
ERROR in ./~/highlight.js/lib/languages/autoit.js
Module parse failed: /Users/afc163/Projects/ant-design/node_modules/highlight.js/lib/languages/autoit.js Maximum call stack size exceeded
You may need an appropriate loader to handle this file type.
RangeError: Maximum call stack size exceeded
    at Parser.applyPluginsBailResult (/Users/afc163/Projects/ant-design/node_modules/tapable/lib/Tapable.js:44:35)
    at Parser.evaluateExpression (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/Users/afc163/Projects/ant-design/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/Users/afc163/Projects/ant-design/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:711:20)
    at Parser.<anonymous> (/Users/afc163/Projects/ant-design/node_modules/webpack/lib/Parser.js:60:20)
    at Parser.applyPluginsBailResult (/Users/afc163/Projects/ant-design/node_modules/tapable/lib/Tapable.js:48:50)
 @ ./~/highlight.js/lib/index.js 13:32-61
```

启动有时会报这个错。

**Comment by afc163** [comment]
```
  Error: write EPIPE
      at Object.exports._errnoException (util.js:856:11)
      at exports._exceptionWithHostPort (util.js:879:20)
      at WriteWrap.afterWrite (net.js:763:14)

webpack building...
📦  1/1 build modules
webpack: bundle build is now finished.
webpack built 8c436e927cea86785cf4 in 4815ms
webpack building...
📦  1/1 build modules
webpack: bundle build is now finished.
webpack built 9df93b7353591905f31c in 4735ms

  Error: write EPIPE
      at Object.exports._errnoException (util.js:856:11)
      at exports._exceptionWithHostPort (util.js:879:20)
      at WriteWrap.afterWrite (net.js:763:14)
```

hmr 的时候，有时会报错。

**Comment by benjycui** [comment]
@sorrycc 上面这个报错，应该是工具那边的问题？

**Comment by benjycui** [comment]
highlight.js 报错，参考 https://github.com/isagalaev/highlight.js/issues/895 https://github.com/webpack/webpack/issues/1721

**Comment by benjycui** [comment]
Enable GA https://github.com/ant-design/ant-design/commit/6199cf158fcf55ae4d9073c002492ac00a96c33a

**Comment by afc163** [comment]
![](https://os.alipayobjects.com/rmsportal/YizLDSNgEfVOOuK.png)

首页滚屏下去的导航样式变化失效了。

**Comment by afc163** [comment]
HMR 貌似失效了。

**Comment by afc163** [comment]
http://127.0.0.1:8001/#/components/changelog?_k=ri7us1

- [ ] 左侧菜单没有高亮。

**Comment by benjycui** [comment]
All done, close now?

**Comment by afc163** [comment]
:+1:
