### ISSUE TITLE
Input组件服务端渲染出现document未定义异常

### ISSUE THREAD

**Issue by langjt** [ant-design/ant-design#1321]
Input组件使用服务端渲染出现document未定义异常：
error given was: ReferenceError: document is not defined
    at ieGT9 (/antd/lib/input/index.js:35:22)
    at Input.renderInput (/antd/lib/input/index.js:129:26)
    at Input.render (/antd/lib/input/index.js:145:42)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/react/lib/ReactMultiChild.js:241:44)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/components/input/index.jsx#L6

这里不会 `reture false` 吗？

**Comment by afc163** [comment]
对，应该是 `'undefined'`。
