### ISSUE TITLE
Jest throw error when testing Tabs.TabPane

### ISSUE THREAD

**Issue by banyudu** [ant-design/ant-design#13620]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
macOS Mojave 10.14.1 with node v8.9.1

### Reproduction link
[https://github.com/banyudu/antd-jest-error](https://github.com/banyudu/antd-jest-error)

### Steps to reproduce
npm i && npm test

### What is expected?
Success test

### What is actually happening?
Error: Uncaught [TypeError: Cannot read property 'scrollWidth' of undefined]
        at reportException (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2381:16)
        at invokeGuardedCallback (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2434:31)
        at commitRoot (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9779:7)
        at completeRoot (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11210:3) TypeError: Cannot read property 'scrollWidth' of undefined
        at ScrollableTabBarNode.getScrollWH (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/rc-tabs/lib/ScrollableTabBarNode.js:230:18)
        at ScrollableTabBarNode.setNextPrev (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/rc-tabs/lib/ScrollableTabBarNode.js:171:28)
        at ScrollableTabBarNode.componentDidUpdate (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/rc-tabs/lib/ScrollableTabBarNode.js:146:27)
        at ScrollableTabBarNode.componentDidMount (/Users/banyudu/dev/zhike/apollon/antd-jest-error/node_modules/rc-tabs/lib/ScrollableTabBarNode.js:131:12)

**Comment by banyudu** [comment]
There is a similar issue https://github.com/ant-design/ant-design/issues/5362, but the solution in it can't solve this issue.

**Comment by banyudu** [comment]
```javascript
import React from 'react'
import renderer from 'react-test-renderer'
import { Tabs } from 'antd'

const TabPane = Tabs.TabPane

if (typeof window !== 'undefined') {
  global.window.resizeTo = (width, height) => {
    global.window.innerWidth = width || global.window.innerWidth;
    global.window.innerHeight = height || global.window.innerHeight;
    global.window.dispatchEvent(new Event('resize'));
  };
  global.window.scrollTo = () => {};
}

// The built-in requestAnimationFrame and cancelAnimationFrame not working with jest.runFakeTimes()
// https://github.com/facebook/jest/issues/5147
global.requestAnimationFrame = cb => setTimeout(cb, 0);
global.cancelAnimationFrame = cb => clearTimeout(cb, 0);

it('TabPane', () => {
  expect(renderer.create(<div></div>).toJSON()).toMatchSnapshot() // works
  expect(renderer.create(<Tabs><TabPane tab="demo" key="demo"></TabPane></Tabs>).toJSON()).toMatchSnapshot() // fail
})
```

**Comment by pdavid0** [comment]
I am facing the same issue, followed the `jest` + `enzyme`, no resolution.

**Comment by yanlee26** [comment]
I got this error: `node_modules/antd/es/button/style/css.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/index.css';`

**Comment by arvinsim** [comment]
I also get the same error as @yanlee26

**Comment by arvinsim** [comment]
Any resolution on this?

**Comment by Priyayarra** [comment]
I also got the same error

**Comment by dgreene1** [comment]
Has anyone resolved this yet?

We still have problems even when we follow the regular Jest advice of [transforming antd from a ES6 module to a CJS module](https://github.com/facebook/jest/issues/2081#issuecomment-619441551) and also [replacing the CSS import](https://jestjs.io/docs/en/webpack#mocking-css-modules). @chenshuai2144 since we've all tried numerous workarounds for htis, can you investigate if this is an issue with antd and not our configurations?

cc'ing my coworker @patelrikin since he's also interested in finding out what your teams have done to get around this.

**Comment by Andrew-He** [comment]
got the same error, 

I did jest-mock to bypass this component 

```
jest.mock(
  'react-icecream/node_modules/rc-tabs/lib/ScrollableTabBarNode',
  () => () => null
)
```

and it works fine.

**Comment by dgreene1** [comment]
But if you mock the component, you’re not even executing the test (in most cases).

We need a real solution that work with Ant’s Babel/import plugin.

**Comment by Gervwyk** [comment]
Any ideas how to make this work. Simular issue with react-test-renderer for Selector:
```
TypeError: Cannot read property 'scrollWidth' of null
```

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/14462#issuecomment-456122785

Or you can upgrade to antd v4.

**Comment by dgreene1** [comment]
Please reopen this since none of the linked articles solve the root problem.
