### ISSUE TITLE
windows 下开发模式 npm start 报错

### ISSUE THREAD

**Issue by dntzhang** [ant-design/ant-design#13732]
E:\All-In-One\Work\Project\ant-design-master>npm start

> antd@3.11.2 start E:\All-In-One\Work\Project\ant-design-master
> rimraf _site && mkdir _site && node ./scripts/generateColorLess.js && cross-en
v NODE_ENV=development bisheng start -c ./site/bisheng.config.js

Theme generated successfully. OutputFile: E:\All-In-One\Work\Project\ant-design-
master\_site\color.less
module.js:478
    throw err;
    ^

Error: Cannot find module 'E:\All-In-One\Work\Project\ant-design-master\node_mod
ules\E:\All-In-One\Work\Project\ant-design-master\site\bisheng.config.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at Module.require (E:\All-In-One\Work\Project\ant-design-master\node_modules
\bisheng\lib\index.js:66:23)
    at require (internal/module.js:20:19)
    at getBishengConfig (E:\All-In-One\Work\Project\ant-design-master\node_modul
es\bisheng\lib\utils\get-bisheng-config.js:42:54)
    at Object.start (E:\All-In-One\Work\Project\ant-design-master\node_modules\b
isheng\lib\index.js:98:23)
    at Object.<anonymous> (E:\All-In-One\Work\Project\ant-design-master\node_mod
ules\bisheng\bin\bisheng-start:10:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! antd@3.11.2 start: `rimraf _site && mkdir _site && node ./scripts/gener
ateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bishen
g.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@3.11.2 start script 'rimraf _site && mkdir _site &&
node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng st
art -c ./site/bisheng.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf _site && mkdir _site && node ./scripts/generateColorLess.js
&& cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\All-In-One\Work\Project\ant-design-master\npm-debug.log

**Comment by ztplz** [comment]
当总项目下有`./site/bisheng.config.js`这个文件吗

**Comment by dntzhang** [comment]
哈。有的，mac下正常，window编不过

**Comment by afc163** [comment]
windows 本地调试问题欢迎提交 PR

**Comment by dntzhang** [comment]
嗯。知道了~多谢各位。  结贴...
