### ISSUE TITLE
Error: Cannot find module '/home/circleci/ant-design/node_modules/WebpackOptionsApply'

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14766]
```
> antd@3.13.2 prepublish /home/circleci/ant-design
> antd-tools run guard

antd-tools run guard
module.js:550
    throw err;
    ^

Error: Cannot find module '/home/circleci/ant-design/node_modules/WebpackOptionsApply'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at Module.require (/home/circleci/ant-design/node_modules/antd-tools/lib/utils/projectHelper.js:31:25)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/circleci/ant-design/node_modules/webpack/lib/webpack.js:10:29)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd@3.13.2 prepublish: `antd-tools run guard`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the antd@3.13.2 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-02-10T08_05_46_990Z-debug.log
Exited with code 1
```

https://circleci.com/gh/ant-design/ant-design/52899

**Comment by ztplz** [comment]
https://stackoverflow.com/questions/49684857/after-npm-install-getting-error-cannot-find-module-lib-utils-unsupported

**Comment by ztplz** [comment]
本地也一样，看起来是npm的问题

**Comment by ztplz** [comment]
https://github.com/ant-design/antd-tools/blob/master/lib/utils/projectHelper.js#L22
require被改了 后面的路径不对了

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/52532117-90bb2080-2d5a-11e9-8d68-226137936044.png)

**Comment by chenshuai2144** [comment]
pro 也有问题，umi 也启动了了。
```
2019-02-10T08:02:03.4346036Z Building ...
2019-02-10T08:02:03.5594493Z /home/vsts/work/1/s/node_modules/ajv/lib/keyword.js:65
2019-02-10T08:02:03.5595591Z       throw new Error('custom keyword definition is invalid: '  + this.errorsText(validateDefinition.errors));
2019-02-10T08:02:03.5595658Z       ^
2019-02-10T08:02:03.5595813Z 
2019-02-10T08:02:03.5595860Z Error: custom keyword definition is invalid: data.errors should be boolean
2019-02-10T08:02:03.5595907Z     at Ajv.addKeyword (/home/vsts/work/1/s/node_modules/ajv/lib/keyword.js:65:13)
2019-02-10T08:02:03.5596227Z     at module.exports (/home/vsts/work/1/s/node_modules/ajv-errors/index.js:10:7)
2019-02-10T08:02:03.5596495Z     at Object.<anonymous> (/home/vsts/work/1/s/node_modules/schema-utils/src/validateOptions.js:22:1)
2019-02-10T08:02:03.5596581Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-02-10T08:02:03.5596646Z     at Module._compile (/home/vsts/work/1/s/node_modules/pirates/lib/index.js:83:24)
2019-02-10T08:02:03.5596705Z     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-02-10T08:02:03.5596751Z     at Object.newLoader [as .js] (/home/vsts/work/1/s/node_modules/pirates/lib/index.js:88:7)
2019-02-10T08:02:03.5596815Z     at Module.load (internal/modules/cjs/loader.js:599:32)
2019-02-10T08:02:03.5596857Z     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-02-10T08:02:03.5596899Z     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-02-10T08:02:03.5596970Z     at Module.require (internal/modules/cjs/loader.js:637:17)
2019-02-10T08:02:03.5597012Z     at require (internal/modules/cjs/helpers.js:22:18)
2019-02-10T08:02:03.5597271Z     at Object.<anonymous> (/home/vsts/work/1/s/node_modules/schema-utils/src/index.js:7:25)
2019-02-10T08:02:03.5597370Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
2019-02-10T08:02:03.5597414Z     at Module._compile (/home/vsts/work/1/s/node_modules/pirates/lib/index.js:83:24)
2019-02-10T08:02:03.5597493Z     at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by ztplz** [comment]
重装下就没事了

**Comment by ztplz** [comment]
brew装的node好像有问题  我卸了从官网下了一个 没用brew装 win上应该没问题  可以试试

**Comment by ztplz** [comment]
也可能跟版本有关   我从官网直接下的最新的

**Comment by imhele** [comment]
> brew装的node好像有问题 我卸了从官网下了一个 没用brew装 win上应该没问题 可以试试

+1

**Comment by zombieJ** [comment]
Seems fixed. close.
ref: #14767
