### ISSUE TITLE
Menu can not pass the test

### ISSUE THREAD

**Issue by eruca** [ant-design/ant-design#15305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0p3q15km30)

### Steps to reproduce
index.test.js

### What is expected?
can pass the test

### What is actually happening?
error happened

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | Mac 10.14.2 |
| Browser | Chrome 72.0.3626.81 |

**Comment by eruca** [comment]
```js
describe('Antd Menu', () => {
    it('Menu', () => {
        const wrapper = render.create(
            <Menu>
                <Menu.Item>菜单项</Menu.Item>
            </Menu>
        );
        expect(wrapper.root.children.length).toBe(1);
    });
});

describe('Antd Menu', () => {
    it('Menu', () => {
        const wrapper = render.create(
            <Menu mode="horizontal" style={{ lineHeight: '66px' }} selectedKeys={['/']}>
                <Menu.Item key="/" title="Home">
                    Home
                </Menu.Item>
            </Menu>
        );
        expect(wrapper.root.children.length).toBe(1);
    });
});
```
in my own project, the upper one can pass when the other will fail, if I delete the props of mode, it will success

**Comment by eruca** [comment]
```bash
    TypeError: Cannot read property 'split' of undefined

      25 | describe('Antd Menu', () => {
      26 |     it('Menu', () => {
    > 27 |         const wrapper = render.create(
         |                                ^
      28 |             <Menu mode="horizontal" style={{ lineHeight: '66px' }} selectedKeys={['/']}>
      29 |                 <Menu.Item key="/" title="Home">
      30 |                     Home

      at node_modules/_rc-menu@7.4.21@rc-menu/lib/DOMWrap.js:83:31
          at Array.filter (<anonymous>)
      at DOMWrap._this.getMenuItemNodes (node_modules/_rc-menu@7.4.21@rc-menu/lib/DOMWrap.js:82:41)
      at DOMWrap._this.setChildrenWidthAndResize (node_modules/_rc-menu@7.4.21@rc-menu/lib/DOMWrap.js:166:33)
      at DOMWrap.componentDidMount (node_modules/_rc-menu@7.4.21@rc-menu/lib/DOMWrap.js:231:10)
      at commitLifeCycles (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:9411:22)
      at commitAllLifeCycles (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:10808:7)
      at HTMLUnknownElement.callCallback (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:2377:14)
      at invokeEventListeners (node_modules/_jsdom@11.12.0@jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/_jsdom@11.12.0@jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/_jsdom@11.12.0@jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/_jsdom@11.12.0@jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/_jsdom@11.12.0@jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:2427:16)
      at invokeGuardedCallback (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:2480:31)
      at commitRoot (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:11020:7)
      at node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12471:5
      at Object.unstable_runWithPriority (node_modules/_scheduler@0.13.4@scheduler/cjs/scheduler.development.js:255:12)
      at completeRoot (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12470:13)
      at performWorkOnRoot (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12399:9)
      at performWork (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12307:7)
      at performSyncWork (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12281:3)
      at requestWork (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12150:5)
      at scheduleWork (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:11965:5)
      at scheduleRootUpdate (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12564:3)
      at updateContainerAtExpirationTime (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12592:10)
      at updateContainer (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:12603:10)
      at Object.create (node_modules/_react-test-renderer@16.8.4@react-test-renderer/cjs/react-test-renderer.development.js:13036:5)
      at Object.it (src/components/GlobalHeader/index.test.tsx:27:32)
```

**Comment by ztplz** [comment]
https://github.com/react-component/menu/issues/232 Looks like the same problem.

**Comment by rwieruch** [comment]
Yes. A React component rendered with a Antd Menu component in Jest with react-test-renderer runs into this issue.
