### ISSUE TITLE
antd-tools是否支持window系统

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design#1536]
运行后会出现这种错误
Error: spawn F:\node\node-global\node_modules\antd-tools\node_modules\atool-build\bin\atool-build ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)

**Comment by afc163** [comment]
可以到这里统一讨论：https://github.com/ant-design/ant-design/issues/1352
