### ISSUE TITLE
Tree test cases fail occasionally

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15839]
https://dev.azure.com/ant-design/ant-design/_build/results?buildId=1488

```
Summary of all failing tests
FAIL components/tree/__tests__/directory.test.js
  ● Directory Tree › expand › with state control › click

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

       98 |             .at(0)
       99 |             .simulate(action);
    > 100 |           jest.runAllTimers();
          |                ^
      101 |           expect(wrapper.render()).toMatchSnapshot();
      102 |         });
      103 |       });

      at FakeTimers.runAllTimers (node_modules/@jest/fake-timers/build/jestFakeTimers.js:207:13)
      at Object.runAllTimers (components/tree/__tests__/directory.test.js:100:16)

  ● Directory Tree › expand › with state control › doubleClick

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

       98 |             .at(0)
       99 |             .simulate(action);
    > 100 |           jest.runAllTimers();
          |                ^
      101 |           expect(wrapper.render()).toMatchSnapshot();
      102 |         });
      103 |       });

      at FakeTimers.runAllTimers (node_modules/@jest/fake-timers/build/jestFakeTimers.js:207:13)
      at Object.runAllTimers (components/tree/__tests__/directory.test.js:100:16)
```

**Comment by zombieJ** [comment]
Caused by Directory use debounce for expand logic. It's strange that only happens on Azure.

**Comment by ztplz** [comment]
https://github.com/facebook/jest/issues/3465

**Comment by zombieJ** [comment]
Reopen since this still happen.

**Comment by zombieJ** [comment]
Said. Seems still happened.
