### ISSUE TITLE
use antd with next.js for SSR && Cannot read property 'gutter' of undefined

### ISSUE THREAD

**Issue by wb-yangxing** [ant-design/ant-design#16368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/wb-yangxing/next-with-antd](https://github.com/wb-yangxing/next-with-antd)

### Steps to reproduce
npm i 安装依赖，
npm run build    构建应用，
npm run start    启动服务，
open http://localhost:3000/index

### What is expected?
http://localhost:3000/index and works fine

### What is actually happening?
TypeError: Cannot read property 'gutter' of undefined
    at Object.children (/Users/yang_x/next-with-antd/node_modules/antd/lib/grid/col.js:105:28)
    at a.render (/Users/yang_x/next-with-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (/Users/yang_x/next-with-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/Users/yang_x/next-with-antd/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (/Users/yang_x/next-with-antd/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Users/yang_x/next-with-antd/node_modules/next-server/dist/server/render.js:211:20)
    at Function.value (/Users/yang_x/next-with-antd/.next/server/static/gVGYFE7htLmJdueAzXhv4/pages/_document.js:995:41)
    at Object.loadGetInitialProps (/Users/yang_x/next-with-antd/node_modules/next-server/dist/lib/utils.js:42:35)
    at Object.renderToHTML (/Users/yang_x/next-with-antd/node_modules/next-server/dist/server/render.js:218:36)
    at <anonymous>

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | mac OS |
| Browser | chrome |

**Comment by zombieJ** [comment]
It's a bug from next.js.
You can trace it by the issue: https://github.com/zeit/next.js/issues/7167
