### ISSUE TITLE
WeekPicker周和月的语言能够和系统一致

### ISSUE THREAD

**Issue by 595113876** [ant-design/ant-design#16772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
WeekPicker不设置默认值的情况下，周和月份与系统语言不一致

### What does the proposed API look like?
WeekPicker周和月的语言能够和系统一致

**Comment by ztplz** [comment]
这不是一个ui库该做的事，获取系统语言应该由你自己获取，再更改antd的语言设置。

**Comment by 595113876** [comment]
antd的语言已经设置为中文，但是周日历的月份和周还是显示的英文

**Comment by ztplz** [comment]
@595113876  能写个在线例子或者建个重现仓库？

**Comment by 595113876** [comment]
import React from 'react';
import { LocaleProvider } from 'antd';
import zhCN from 'antd/lib/locale-provider/zh_CN';
import 'moment/locale/zh-cn';
import withRouter from 'umi/withRouter';
import { DatePicker } from 'antd';

export default withRouter(props => {
  return (
    <LocaleProvider locale={zhCN}>
      <DatePicker.WeekPicker />
    </LocaleProvider>
  );
});

**Comment by ztplz** [comment]
@595113876 你贴代码没用的，之前有过这样的情况，跟moment的引用有关系。你应该建一个重现的git repo，确保环境一致。

**Comment by 595113876** [comment]
https://github.com/595113876/test.git
这是我创建的仓库

**Comment by afc163** [comment]
```
🌈  test-moment@1.0.0 git:❨master❩ npm start

> test@1.0.0 start /Users/afc163/Projects/test-moment
> umi dev

✖  error     [hardSource] is no longer valid. Please remove it from the configuration file.
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/Users/afc163/Projects/test-moment/pages'
    at readdirSync (fs.js:783:3)
    at getRouteConfigFromDir (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/routes/getRouteConfigFromDir.js:35:37)
    at _default (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/routes/getRouteConfig.js:31:49)
    at Object.fetchRoutes (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/plugins/commands/getRouteManager.js:23:51)
    at api.registerCommand (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/plugins/commands/dev/index.js:38:19)
    at Service.runCommand (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/Service.js:359:12)
    at Service.run (/Users/afc163/Projects/test-moment/node_modules/umi-build-dev/lib/Service.js:327:17)
    at Object.<anonymous> (/Users/afc163/Projects/test-moment/node_modules/umi/lib/scripts/realDev.js:28:47)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/afc163/.npm/_logs/2019-05-27T03_18_55_113Z-debug.log
```

跑不起来

**Comment by 595113876** [comment]
请使用yarn
启动流程
1、yarn 命令加载依赖
2、yarn start启动项目

**Comment by afc163** [comment]
是这么操作的，报上面的错。

**Comment by 595113876** [comment]
已更新仓库代码，请拉取新的代码后重新启动

**Comment by afc163** [comment]
```
rm -rf node_modules yarn.lock
yarn
yarn start
```

这样就行了。yarn.lock 里面有两个版本不一致的 moment。

**Comment by 595113876** [comment]
已解决，感谢
