### ISSUE TITLE
正式环境-服务端渲染时Menu和Tabs组件报错

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design#18659]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jihfgz/antd-issue-18659](https://github.com/jihfgz/antd-issue-18659)
重现连接已更新。修改NODE_ENV为其他值不报错，能正确打印渲染的HTML

### Steps to reproduce
webpack 配置文件 plugins 下增加 以下配置（只有production会出错，其他正常）
```
new webpack.DefinePlugin({
    'process.env': {
        NODE_ENV: '"production"',
    },
}),
```

### What is expected?
```
====================渲染成功==================
<div data-reactroot=""><ul class="ant-menu ant-menu-light ant-menu-root ant-menu-inline" role="menu"><li class="ant-menu-submenu ant-menu-submenu-inline" role="menuitem"><div style="padd
ing-left:0" class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>测试</span><i class="ant-menu-submenu-arrow"></i></div><div></div></li></ul><div class="ant-ta
bs ant-tabs-top ant-tabs-line"><div role="tablist" class="ant-tabs-bar ant-tabs-top-bar" tabindex="0"><div class="ant-tabs-nav-container"><span unselectable="unselectable" class="ant-tab
s-tab-prev ant-tabs-tab-btn-disabled"><span class="ant-tabs-tab-prev-icon"><i aria-label="icon: left" class="anticon anticon-left ant-tabs-tab-prev-icon-target"><svg viewBox="64 64 896 8
96" focusable="false" class="" data-icon="left" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M724 218.3V141c0-6.7-7.7-10.4-12.9-6.3L260.3 486.8a31.86 31.86 0
0 0 0 50.3l450.8 352.1c5.3 4.1 12.9.4 12.9-6.3v-77.3c0-4.9-2.3-9.6-6.1-12.6l-360-281 360-281.1c3.8-3 6.1-7.7 6.1-12.6z"></path></svg></i></span></span><span unselectable="unselectable" c
lass="ant-tabs-tab-next ant-tabs-tab-btn-disabled"><span class="ant-tabs-tab-next-icon"><i aria-label="icon: right" class="anticon anticon-right ant-tabs-tab-next-icon-target"><svg viewB
ox="64 64 896 896" focusable="false" class="" data-icon="right" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M765.7 486.8L314.9 134.7A7.97 7.97 0 0 0 302 141v
77.3c0 4.9 2.3 9.6 6.1 12.6l360 281.1-360 281.1c-3.9 3-6.1 7.7-6.1 12.6V883c0 6.7 7.7 10.4 12.9 6.3l450.8-352.1a31.96 31.96 0 0 0 0-50.4z"></path></svg></i></span></span><div class="ant-
tabs-nav-wrap"><div class="ant-tabs-nav-scroll"><div class="ant-tabs-nav ant-tabs-nav-animated"><div><div role="tab" aria-disabled="false" aria-selected="true" class="ant-tabs-tab-active
 ant-tabs-tab">tab1</div><div role="tab" aria-disabled="false" aria-selected="false" class=" ant-tabs-tab">tab2</div></div><div class="ant-tabs-ink-bar ant-tabs-ink-bar-animated"></div><
/div></div></div></div></div><div tabindex="0" style="width:0;height:0;overflow:hidden;position:absolute" role="presentation"></div><div class="ant-tabs-content ant-tabs-content-animated
 ant-tabs-top-content" style="margin-left:0%"><div role="tabpanel" aria-hidden="false" class="ant-tabs-tabpane ant-tabs-tabpane-active"><div tabindex="0" style="width:0;height:0;overflow
:hidden;position:absolute" role="presentation"></div>123<div tabindex="0" style="width:0;height:0;overflow:hidden;position:absolute" role="presentation"></div></div><div role="tabpanel"
aria-hidden="true" class="ant-tabs-tabpane ant-tabs-tabpane-inactive"></div></div><div tabindex="0" style="width:0;height:0;overflow:hidden;position:absolute" role="presentation"></div><
/div></div>
====================渲染结束==================

```

### What is actually happening?
```
0|index    | TypeError: Cannot read property 'antdMenuTheme' of undefined
0|index    |     at Object.eval [as children] (webpack:///./node_modules/antd/lib/menu/SubMenu.js?:74:34)
0|index    |     at a.render (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:47:174)
0|index    |     at a.read (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:44:161)
0|index    |     at Object.renderToString (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:55:83)
0|index    |     at eval (webpack:///./app/view/index.server.jsx?:180:44)
0|index    |     at <anonymous>
0|index    |     at process._tickCallback (internal/process/next_tick.js:188:7)
0|index    | TypeError: Cannot read property 'sentinelStart' of undefined
0|index    |     at Object.children (/opt/hp/node_modules/rc-tabs/lib/TabPane.js:90:36)
0|index    |     at a.render (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:47:174)
0|index    |     at a.read (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:44:161)
0|index    |     at Object.renderToString (webpack:///./node_modules/react-dom/cjs/react-dom-server.node.production.min.js?:55:83)
0|index    |     at eval (webpack:///./app/view/index.server.jsx?:180:44)
0|index    |     at <anonymous>
0|index    |     at process._tickCallback (internal/process/next_tick.js:188:7)

```

之前都是正常的，最近一段时间发现这问题，具体什么时候，那个版本开始出现不太确定。出错的功能没有变更过代码。

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.2 |
| System | window |
| Browser | chrome |

**Comment by jihfgz** [comment]
重现项目 https://github.com/jihfgz/antd-issue-18659

**Comment by afc163** [comment]
Fixed in , try to remove `node_modules` and `package-lock.json`.

https://github.com/react-component/menu/commit/353039be098cd2c65593c7f8217428bb3e872df0

**Comment by afc163** [comment]
https://github.com/react-component/menu/issues/276
https://github.com/react-component/menu/issues/275
