### ISSUE TITLE
Custom Theme setup fails! Problem with "react-rewired-app" package

### ISSUE THREAD

**Issue by MaxArrowhead** [ant-design/ant-design#18837]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rt21v)

### Steps to reproduce
Following a FRESH installation with CREATE-REACT-APP as explained on the official documentation (https://ant.design/docs/react/use-with-create-react-app)
After changing the "yarn start" script to use "react-rewired-app start" (https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides)
we get an error:

yarn start
yarn start v0.27.5
$ react-app-rewired start
module.js:540
    throw err;
    ^

Error: Cannot find module '/.../antd-demo/node_modules/react-scripts/config/webpackDevServer.config.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/visione/Desktop/antd-demo/node_modules/react-app-rewired/scripts/start.js:17:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.

### What is expected?
Expected to start the local server and show the index page. 

### What is actually happening?
The build breaks.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9.0 |
| System | MAC OS 10.14.2 |
| Browser | Chrome 76 |

**Comment by MaxArrowhead** [comment]
This is the dependency list that got Ant theming to work: 

"dependencies": {
    "@apollo/react-hooks": "^3.0.1",
    "@sentry/browser": "^5.6.3",
    "antd": "^3.23.3",
    "apollo-boost": "^0.4.4",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "apollo-link-state": "^0.4.2",
    "babel-eslint": "^10.0.2",
    "babel-plugin-import": "^1.12.1",
    "client-oauth2": "^4.2.5",
    "core-js": "^2.6.5",
    "customize-cra": "^0.7.0",
    "eslint": "^6.4.0",
    "graphql": "^14.5.6",
    "graphql-tag": "^2.10.1",
    "jwt-decode": "^2.2.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-apollo": "^3.1.1",
    "react-app-rewired": "^2.1.3",
    "react-dom": "^16.9.0",
    "react-responsive": "^8.0.1",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.1.1",
    "react-test-renderer": "^16.9.0",
    "styled-components": "^4.3.2"
  },
  "devDependencies": {
    "@testing-library/react": "^9.1.4",
    "babel-core": "^6.26.3",
    "babel-jest": "^23.6.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "eslint-plugin-prettier": "^3.1.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "less-loader": "^5.0.0",
    "mini-css-extract-plugin": "^0.8.0",
    "prettier": "^1.18.2",
    "sass": "^1.18.0",
    "sass-loader": "^7.3.1"
  },


----


And the config-overrides.js:

const { override, fixBabelImports, addLessLoader } = require('customize-cra');
module.exports = override(
    fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
    }),
    addLessLoader({
        javascriptEnabled: true,
        modifyVars: { '@primary-color': '#5ad192' },
    }),
);


----

and the .babelrc:

{
  "plugins": [
    ["import", {
      "libraryName": "antd",
      "libraryDirectory": "es",
      "style": "css" // `style: true` for less
    }]
  ],
  "env": {
    "production": {
      "plugins": ["transform-es2015-modules-commonjs"]
    },
    "development": {
      "plugins": ["transform-es2015-modules-commonjs"]
    },
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
