### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by spt110** [ant-design/ant-design#1884]
**问题描述**sunpeitaodeMacBook-Pro:antd-demo sunpeitao$ npm start

> @ start /Users/sunpeitao/mycode/antd-demo
> dora -p 8001 --plugins "webpack,hmr,proxy,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html"

/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora-plugin-hmr/0.6.0/dora-plugin-hmr/lib/index.js:72
        loader.query.presets.push('react-hmre');
                    ^

TypeError: Cannot read property 'presets' of undefined
    at /Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora-plugin-hmr/0.6.0/dora-plugin-hmr/lib/index.js:72:21
    at Array.forEach (native)
    at Object.webpackUpdateConfigFinally (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora-plugin-hmr/0.6.0/dora-plugin-hmr/lib/index.js:70:34)
    at ret (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/plugin.js:140:29)
    at run (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/reduceAsync.js:21:5)
    at next (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/reduceAsync.js:14:14)
    at iteratorCallback (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/reduceAsync.js:23:7)
    at ret (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/plugin.js:113:23)
    at run (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/reduceAsync.js:21:5)
    at reduceAsync (/Users/sunpeitao/mycode/antd-demo/node_modules/.npminstall/dora/0.3.2/dora/lib/reduceAsync.js:27:10)
（描述一下问题）

**发生环境**

- antd 版本：
- 操作系统及版本：mac
- 浏览器及版本：
- 在线演示地址：

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by rrandom** [comment]
我遇到了同样的问题， antd-init --type plain-react 后npm start 报同样的错误, 去掉dora参数中的hmr后可用

**Comment by afc163** [comment]
@fengmk2

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/antd-init/issues/57
