### ISSUE TITLE
执行NPM RUN BUILD 之后 IE下运行报错，貌似是babel对依赖的react antd 没有进行转换

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#1963]
行: 11056
错误: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

我在webpark已配置es3ify-loader

    <script src="../jquery-1.12.1.min.js"></script>
    
</head>

media.match.min.js 这个JS报错。例外没有被接触

**Comment by benjycui** [comment]
其实这是个 React 抛出的 warning，请确认 webpack 的配置在开发环境下没有压缩 React 的代码。

**Comment by wuhaih** [comment]
测试环境已压缩代码，script那段脚本是否需要下载到本地？

**Comment by wuhaih** [comment]
开发及测试环境我都是将react，antd抽到comm的，请问我该怎么解决

**Comment by benjycui** [comment]
webpack 配置问题，建议去 webpack 的社区寻找答案，谢谢。

**Comment by wangqianqian1100** [comment]
module.js:538
    throw err;
    ^

Error: Cannot find module 'react-scripts/package.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\easyvoa\easyvoa\node_m
odules\_react-app-rewired@1.5.0@react-app-rewired\scripts\utils\paths.js:24:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easyvoa@0.1.0 build: `react-app-rewired build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easyvoa@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-02T0
2_13_57_724Z-debug.log
