### ISSUE TITLE
warnings on npm start

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20700]
```
> antd@4.0.0-rc.0 start /Users/afc163/Projects/ant-design
> rimraf _site && mkdir _site && cross-env NODE_ENV=development concurrently "node ./scripts/generateColorLess.js" "bisheng start -c ./site/bisheng.config.js"

[0] 🔩 less render start!
[1] ℹ Compiling 🚚  Bisheng
[1] ℹ ｢wds｣: Project is running at http://localhost/
[1] ℹ ｢wds｣: webpack output is served from undefined
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/afc163/Projects/ant-design/_site
[1] ℹ ｢wds｣: 404s will fallback to /index.html
[0] 🎩 less render end!
[0] 🌈 Theme generated successfully. OutputFile: /Users/afc163/Projects/ant-design/_site/color.less
[0] node ./scripts/generateColorLess.js exited with code 0
[1] ✔ 🚚  Bisheng: Compiled successfully in 55.25s
[1]  WARNING  Compiled with 2 warnings18:34:46
[1] 
[1]  warning  in ./site/theme/template/utils.d.ts
[1] 
[1] Module build failed (from ./node_modules/_ts-loader@6.2.1@ts-loader/index.js):
[1] Error: Debug Failure. Output generation failed
[1]     at Object.transpileModule (/Users/afc163/Projects/ant-design/node_modules/_typescript@3.7.4@typescript/lib/typescript.js:116867:29)
[1]     at getTranspilationEmit (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:318:74)
[1]     at successLoader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:66:15)
[1]     at Object.loader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:22:12)
[1] 
[1]  @ ./site/theme sync ^\.\/template.*$
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/routes.index.js
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1]  @ multi ./node_modules/_webpack-dev-server@3.10.1@webpack-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1] 
[1]  warning  in ./site/theme/template/Layout/Footer.d.ts
[1] 
[1] Module build failed (from ./node_modules/_ts-loader@6.2.1@ts-loader/index.js):
[1] Error: Debug Failure. Output generation failed
[1]     at Object.transpileModule (/Users/afc163/Projects/ant-design/node_modules/_typescript@3.7.4@typescript/lib/typescript.js:116867:29)
[1]     at getTranspilationEmit (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:318:74)
[1]     at successLoader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:66:15)
[1]     at Object.loader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:22:12)
[1] 
[1]  @ ./site/theme sync ^\.\/template.*$
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/routes.index.js
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1]  @ multi ./node_modules/_webpack-dev-server@3.10.1@webpack-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1] 
[1]  WAIT  Compiling...18:34:47
[1] 
[1] ℹ Compiling 🚚  Bisheng
[1] ✔ 🚚  Bisheng: Compiled successfully in 972.84ms
[1]  WARNING  Compiled with 2 warnings18:34:50
[1] 
[1]  warning  in ./site/theme/template/Layout/Footer.d.ts
[1] 
[1] Module build failed (from ./node_modules/_ts-loader@6.2.1@ts-loader/index.js):
[1] Error: Debug Failure. Output generation failed
[1]     at Object.transpileModule (/Users/afc163/Projects/ant-design/node_modules/_typescript@3.7.4@typescript/lib/typescript.js:116867:29)
[1]     at getTranspilationEmit (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:318:74)
[1]     at successLoader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:66:15)
[1]     at Object.loader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:22:12)
[1] 
[1]  @ ./site/theme sync ^\.\/template.*$
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/routes.index.js
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1]  @ multi ./node_modules/_webpack-dev-server@3.10.1@webpack-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1] 
[1]  warning  in ./site/theme/template/utils.d.ts
[1] 
[1] Module build failed (from ./node_modules/_ts-loader@6.2.1@ts-loader/index.js):
[1] Error: Debug Failure. Output generation failed
[1]     at Object.transpileModule (/Users/afc163/Projects/ant-design/node_modules/_typescript@3.7.4@typescript/lib/typescript.js:116867:29)
[1]     at getTranspilationEmit (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:318:74)
[1]     at successLoader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:66:15)
[1]     at Object.loader (/Users/afc163/Projects/ant-design/node_modules/_ts-loader@6.2.1@ts-loader/dist/index.js:22:12)
[1] 
[1]  @ ./site/theme sync ^\.\/template.*$
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/routes.index.js
[1]  @ ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
[1]  @ multi ./node_modules/_webpack-dev-server@3.10.1@webpack-dev-server/client?http://localhost (webpack)/hot/dev-server.js ./node_modules/_bisheng@1.4.6@bisheng/tmp/entry.index.js
```

**Comment by zombieJ** [comment]
site 一部分是 jsx 一部分是 tsx 报的错，要全切成 tsx 的。
