### ISSUE TITLE
Upgrade V4 fail used codemod 

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20996]
@vagusX 

有遇到这种错误么，公司的项目没法提供示例

> 脚手架是自己写的，不是 CRA

```bash
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/shaw/.npm/_npx/40393/lib/node_modules/@ant-design/codemod-v4/node_modules/core-js/modules/_is-object.js:3:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/shaw/.npm/_npx/40393/lib/node_modules/@ant-design/codemod-v4/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/shaw/.npm/_npx/40393/lib/node_modules/@ant-design/codemod-v4/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.630seconds 
----------- antd4 dependencies alert -----------

Please install the following dependencies:

* antd^4.0.0-rc.0

----------- Thanks for using @ant-design/codemod -----------

 ⇡ 36s
❯ npm ls antd                                    

└── antd@4.0.0-rc.1 

❯ fd interopRequireDefault ./node_modules/@babel/runtime/helpers
node_modules/@babel/runtime/helpers/esm/interopRequireDefault.js
node_modules/@babel/runtime/helpers/interopRequireDefault.js
```

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | macOS Catalina |
| Browser | Chrome |

**Comment by shaodahong** [comment]
看了一下模块都有，我 `upgrade antd` 之后 `npx -p @ant-design/codemod-v4 antd4-codemod src` 一把梭，就没然后了

**Comment by vagusX** [comment]
我来看看

**Comment by vagusX** [comment]
试一下最新版本 [v1.0.0-alpha.12](https://github.com/ant-design/codemod-v4/releases/tag/v1.0.0-alpha.12)，问题应该解决了

**Comment by shaodahong** [comment]
还是不行，另外试了一下全局的

```bash
yarn global add @ant-design/codemod-v4

antd4-codemod src

```

```bash

TypeError: $export is not a function
    at Object.<anonymous> (/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:6
$export($export.S, 'Object', {
^

TypeError: $export is not a function
    at Object.<anonymous> (/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:6
$export($export.S, 'Object', {
^

TypeError: $export is not a function
    at Object.<anonymous> (/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:6
$export($export.S, 'Object', {
^

TypeError: $export is not a function
    at Object.<anonymous> (/Users/shaw/.config/yarn/global/node_modules/core-js/modules/es6.object.set-prototype-of.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/shaw/.config/yarn/global/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.745seconds 
----------- antd4 dependencies alert -----------

Please install the following dependencies:

* antd^4.0.0-rc.0

----------- Thanks for using @ant-design/codemod -----------
```

**Comment by shaodahong** [comment]
再试了下 `npm global`，也是这个 `Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

**Comment by vagusX** [comment]
> 再试了下 `npm global`，也是这个 `Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

咱们线下联系下吧

**Comment by vagusX** [comment]
可能是因为 comptaible 里面的 util 不能在 node 中使用，我把这几个方法考过来看看

**Comment by shaodahong** [comment]
嗯，等晚点我看看能不能搞个例子复现下

**Comment by vagusX** [comment]
@shaodahong 再试试看 @ant-design/codemod-v4@1.0.0-alpha.13

**Comment by shaodahong** [comment]
OK了
