### ISSUE TITLE
win10环境下，打包后启动dora报错

### ISSUE THREAD

**Issue by wg5945** [ant-design/ant-design#2164]
windows环境，没有装openssl

执行dora命令：
`dora --plugins "proxy,browser-history?index=./index.html"`

结果：
```
===========
failed to create cert dir ,please create one by yourself - \Users\wg\.anyproxy_certs\
this error will not block main thread unless you use https-related features in anyproxy
===========
          proxy: load rule from proxy.config.js
temp certs cleared
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn E:\Src\dxmall\backend\node_modules\dora-anyproxy\cert\gen-rootCA.cmd ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3

```

**Comment by afc163** [comment]
Try ask it in https://github.com/alibaba/anyproxy

**Comment by ottomao** [comment]
升级一下依赖的AnyProxy版本吧，最新版已经不依赖openssl和cmd脚本了。
