### ISSUE TITLE
antd-bin安装运行出现错误

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#220]
安装antd-bin的时候会安装node-gpy，没有python的话会出现如下错误：
- 缺失python

```
H:\Users\zhbhun\tmp\node_modules\antd-bin\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\buffer
util>if not defined npm_config_node_gyp (node "H:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (H:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at H:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "H:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\Users\zhbhun\tmp\node_modules\antd-bin\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_m
odules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

- MSBUILD : error MSB3428

```
H:\nodejs\node_global\node_modules\antd-bin\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node
_gyp (node "H:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果
将该组件安装到了其他位置，请将其位置添加到系统路
径中。 [H:\nodejs\node_global\node_modules\antd-bin\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (H:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "H:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\nodejs\node_global\node_modules\antd-bin\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@0.3.8

> utf-8-validate@1.1.0 install H:\nodejs\node_global\node_modules\antd-bin\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-vali
date
> node-gyp rebuild
```

这里node-gyp安装出现问题，是否会影响antd-bin的正常使用。

---

准备好了python，在忽略第二个问题`MSBUILD : error MSB3428`的情况下，直接运行`npm run dev`，会出现如下错误：

```
ERROR in ./~/antd/lib/index.css
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./H:/nodejs/node_global/node_modules/antd-bin/node_modul
es/css-loader/lib/css-base.js in D:\Project\Javascript\React\antd\antd-demo\node_modules\antd\lib
    at Tapable.<anonymous> (H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\lib\Compilation.js:222:38)
    at Tapable.onDoneResolving (H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\lib\NormalModuleFactory.js:28:20)
    at Tapable.<anonymous> (H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\lib\NormalModuleFactory.js:83:20)
    at H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\async\lib\async.js:251:17
    at done (H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\async\lib\async.js:126:15)
    at H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\async\lib\async.js:32:16
    at H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\async\lib\async.js:248:21
    at H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\async\lib\async.js:572:34
    at H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (H:\nodejs\node_global\node_modules\antd-bin\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
 @ ./~/antd/lib/index.js 1:0-22
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 512 kB [rendered]
        [0] H:/nodejs/node_global/~/antd-bin/~/css-loader?sourceMap&-restructuring!H:/nodejs/node_global/~/antd-bin/~/autoprefixer-loader!./~/antd/lib/index.css
 512 kB {0} [built] [1 error]

    ERROR in H:/nodejs/node_global/~/antd-bin/~/css-loader?sourceMap&-restructuring!H:/nodejs/node_global/~/antd-bin/~/autoprefixer-loader!./~/antd/lib/index.cs
s
    Module not found: Error: Cannot resolve 'file' or 'directory' ./H:/nodejs/node_global/node_modules/antd-bin/node_modules/css-loader/lib/css-base.js in D:\Pr
oject\Javascript\React\antd\antd-demo\node_modules\antd\lib
     @ H:/nodejs/node_global/~/antd-bin/~/css-loader?sourceMap&-restructuring!H:/nodejs/node_global/~/antd-bin/~/autoprefixer-loader!./~/antd/lib/index.css 1:27
-123
webpack: bundle is now VALID.
```

这里查找css-loader时，路径怎么是`./H:/nodejs/node_global/node_modules/antd-bin/node_modules/css-loader/lib/css-base.js`

---

antd的字体链向alicdn，这个可以像bootstrap一样直接在模块里提供？

```
@font-face {
  font-family: 'anticon';
  src: url('//at.alicdn.com/t/font_1440074043_6914854.eot');
  /* IE9*/
  src: url('//at.alicdn.com/t/font_1440074043_6914854.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('//at.alicdn.com/t/font_1440074043_6914854.woff') format('woff'), /* chrome、firefox */ url('//at.alicdn.com/t/font_1440074043_6914854.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/ url('//at.alicdn.com/t/font_1440074043_6914854.svg#iconfont') format('svg');
  /* iOS 4.1- */
}
```

**Comment by sorrycc** [comment]
1. optional dep 安装出错，不影响使用
1. antd 和项目路径不在一个盘符的时候会出这个问题，提了 pr，一直没合。。 https://github.com/webpack/loader-utils/pull/14
