### ISSUE TITLE
npm create umi 无法正常创建项目

### ISSUE THREAD

**Issue by moli3** [ant-design/ant-design#23189]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.暂时没有.com](http://www.暂时没有.com)

### Steps to reproduce
mkdir demo
cd demo
npm create umi

### What is expected?
创建新的项目

### What is actually happening?
fatal: 目标路径 '/xxx/xxx/xxx/demo' 已经存在，并且不是一个空目录。
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: git clone https://gitee.com/ant-design/ant-design-pro --depth=1 /xxx/xxx/xxx/demo
null
null
    at makeError (/Users/.npm/_npx/14266/lib/node_modules/create-umi/node_modules/execa/index.js:174:9)
    at /Users/.npm/_npx/14266/lib/node_modules/create-umi/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AntDesignProGenerator.writing (/Users/.npm/_npx/14266/lib/node_modules/create-umi/lib/generators/ant-design-pro/index.js:118:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/.npm/_npx/14266/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:791:20)
    at processImmediate (internal/timers.js:456:21) {
  code: 128,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'git clone https://gitee.com/ant-design/ant-design-pro --depth=1 /xxx/xxx/xxx/demo',
  timedOut: false,
  killed: false
}

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.3.1 |
| System | macOS |
| Browser | chrome |

**Comment by AngYang123** [comment]
https://github.com/ant-design/ant-design-pro/issues/6363
今天也遇到，参考这个

**Comment by zombieJ** [comment]
Merge to https://github.com/ant-design/ant-design-pro/issues/6363
