### ISSUE TITLE
You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.

### ISSUE THREAD

**Issue by marsky911** [ant-design/ant-design#24906]
You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.
Here's the mock I use:
```js
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});
```
[source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

_Originally posted by @Thanaen in https://github.com/ant-design/ant-design/issues/21096#issuecomment-578118486_

**Comment by marsky911** [comment]
> You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.
> Here's the mock I use:
> 
> ```js
> Object.defineProperty(window, 'matchMedia', {
>   writable: true,
>   value: jest.fn().mockImplementation(query => ({
>     matches: false,
>     media: query,
>     onchange: null,
>     addListener: jest.fn(), // deprecated
>     removeListener: jest.fn(), // deprecated
>     addEventListener: jest.fn(),
>     removeEventListener: jest.fn(),
>     dispatchEvent: jest.fn(),
>   })),
> });
> ```
> 
> [source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)
> 
> _Originally posted by @Thanaen in [#21096 (comment)](https://github.com/ant-design/ant-design/issues/21096#issuecomment-578118486)_

TypeError: mql.addListener is not a function

      at node_modules/_antd@4.2.4@antd/lib/_util/responsiveObserve.js:87:11
          at Array.forEach (<anonymous>)
      at Object.register (node_modules/_antd@4.2.4@antd/lib/_util/responsiveObserve.js:77:32)
      at Object.subscribe (node_modules/_antd@4.2.4@antd/lib/_util/responsiveObserve.js:42:12)
      at Row.componentDidMount (node_modules/_antd@4.2.4@antd/lib/grid/row.js:143:52)
      at commitLifeCycles (node_modules/_react-dom@16.13.1@react-dom/cjs/react-dom.development.js:19814:22)
      at commitLayoutEffects (node_modules/_react-dom@16.13.1@react-dom/cjs/react-dom.development.js:22803:7)
      at Object.invokeGuardedCallbackImpl (node_modules/_react-dom@16.13.1@react-dom/cjs/react-dom.development.js:113:10)
      at invokeGuardedCallback (node_modules/_react-dom@16.13.1@react-dom/cjs/react-dom.development.js:292:31)
      at commitRootImpl (node_modules/_react-dom@16.13.1@react-dom/cjs/react-dom.development.js:22541:9)
