### ISSUE TITLE
用官方的create-react-app创建的项目怎么添加antd

### ISSUE THREAD

**Issue by lslvxy** [ant-design/ant-design#2526]
用官方的create-react-app创建的项目怎么添加antd

**Comment by afc163** [comment]
感觉 antd-init 都不用了，后面直接用 create-react-app 来做上手例子。@sorrycc

**Comment by sorrycc** [comment]
那把 antd-init 改成一个空壳，就留提示? demo 走 create-react-app，项目走 dva-cli 。

**Comment by lslvxy** [comment]
我用create-react-app创建的项目引用了antd但是css加载不了，menu组件都是js能加载css不对，不知道怎么配置了

**Comment by afc163** [comment]
欢迎探索和 PR ，一起来贡献。

**Comment by lslvxy** [comment]
暂时还只能用ant-init了，还没找到好的解决办法

**Comment by lslvxy** [comment]
找到解决办法了，先运行npm run eject 获得完整版本，然后添加 `npm i --save antd` 添加antd，`npm i --save-dev babel-plugin-antd`添加babel插件，然后在`config/babel.dev.js`中`plugins`中添加
```
.concat([
        [require.resolve('babel-plugin-antd'), {
            style: "css",
        }]
    ])
```

最后结果是
```
plugins: [
        'babel-plugin-syntax-trailing-function-commas',
        'babel-plugin-transform-class-properties',
        'babel-plugin-transform-object-rest-spread'
    ].map(require.resolve).concat([
        [require.resolve('babel-plugin-transform-runtime'), {
            helpers: false,
            polyfill: false,
            regenerator: true
        }]
    ]).concat([
        [require.resolve('babel-plugin-antd'), {
            style: "css",
        }]
    ])
```
然后在引用antd组件就没有问题了

**Comment by lslvxy** [comment]
现在start可以运行了，但是运行build的时候只要加上了antd的组件就build失败

```

Failed to create a production build. Reason:
Module build failed: Error: /home/lise/GitHub/react/src/App.js: File/Program node, we can't possibly find a statement parent to this
    at NodePath.getStatementParent (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/family.js:43:11)
    at PathHoister.getAttachmentPath (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/lib/hoister.js:118:26)
    at PathHoister.run (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/lib/hoister.js:171:25)
    at NodePath.hoist (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/modification.js:292:18)
    at PluginPass.JSXElement (/home/lise/GitHub/react/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:39:16)
    at newFn (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:211:19)
    at Function.traverse.node (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/index.js:161:17)
    at NodePath.visit (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/path/context.js:116:19)
    at TraversalContext.visitQueue (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitMultiple (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:113:17)
    at TraversalContext.visit (/home/lise/GitHub/react/node_modules/.npminstall/babel-traverse/6.13.0/babel-traverse/lib/context.js:209:19)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react@0.0.1 build: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react@0.0.1 build script 'node ./scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lise/GitHub/react/npm-debug.log
```

**Comment by sorrycc** [comment]
`babel.prod.js` 也要同步改的。

**Comment by lslvxy** [comment]
dev和pro都改过了的

**Comment by lslvxy** [comment]
查到原因了，因为prod中babel加了一个`babel-plugin-transform-react-constant-elements`插件导致的

**Comment by luckydrq** [comment]
粗看了一下create-react-app，貌似默认的配置不支持less/sass，这个跑antd不行吧？

**Comment by lslvxy** [comment]
需要另加对应的loader

**Comment by anhuiliujun** [comment]
@lslvxy 你最后怎么让 babel-plugin-transform-react-constant-elements与antd兼容的？

**Comment by lslvxy** [comment]
我把这个插件给注掉了。。。

**Comment by dancinglone** [comment]
如果项目要用这个插件，那怎么破。。。

**Comment by dancinglone** [comment]
求老大们指点

**Comment by afc163** [comment]
https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup

eject 出 webpack 配置文件，并按照 https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js 添加相关 loader。

**Comment by imWildCat** [comment]
我这么做就成功了，不知道有什么漏洞？

```js
// in index.js
import 'antd/dist/antd.css';
```

```js
// in App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import { DatePicker } from 'antd';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React!</h2>
        </div>
        <DatePicker />
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;

```

**Comment by DanielWLam** [comment]
所以imWildCat的就是正解了吗？

**Comment by wuyunjiang** [comment]
@imWildCat 
这样是可以，但是打包后的文件就变得好大，请问怎么解决啊

**Comment by afc163** [comment]
为什么不看官方文档呢？https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by alihanniba** [comment]
按照文档来就可以   loader都不用添加  npm start  与 npm build 都没问题
