### ISSUE TITLE
Badge crash when snapshot test with jest&react-test-renderer 

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design#25423]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-shadow-33nbi?file=/index.js)

### Steps to reproduce
just check the output of the snapshot test

### What is expected?
the component with Badge will be taken snapshot correctly.

### What is actually happening?
try to take snapshot with renderer.create(<TheComponent />).toJSON();
but it crash:

```
Cannot read property 'add' of undefined

TypeError: Cannot read property 'add' of undefined
    at cssAnimation (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:107:18)
    at AnimateChild.transition (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:104:54)
    at AnimateChild.componentWillAppear (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:67:14)
    at Animate.performAppear (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:297:32)
    at eval (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:92:18)
    at Array.forEach (<anonymous>)
    at Animate.componentDidMount (eval at ko (https://codesandbox.io/static/js/sandbox.fcf79e2d2.js:1:199727), <anonymous>:90:16)
    at commitLifeCycles (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10428:22)
    at commitLayoutEffects (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13295:7)
    at HTMLUnknownElement.callCallback (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9972:14)
    at innerInvokeEventListeners (https://33nbi.csb.app/static/js/jsdom-4.0.0.min.js:1:1334219)
    at invokeEventListeners (https://33nbi.csb.app/static/js/jsdom-4.0.0.min.js:1:1333311)
    at HTMLUnknownElementImpl._dispatch (https://33nbi.csb.app/static/js/jsdom-4.0.0.min.js:1:1332307)
    at HTMLUnknownElementImpl.dispatchEvent (https://33nbi.csb.app/static/js/jsdom-4.0.0.min.js:1:1329421)
    at HTMLUnknownElement.dispatchEvent (https://33nbi.csb.app/static/js/jsdom-4.0.0.min.js:1:1529878)
    at Object.invokeGuardedCallbackDev (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10021:16)
    at invokeGuardedCallback (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10073:31)
    at commitRootImpl (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13033:9)
    at unstable_runWithPriority (https://33nbi.csb.app/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
    at commitRoot (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12873:3)
    at finishSyncRender (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12384:3)
    at performSyncWorkOnRoot (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12370:7)
    at eval (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1825:24)
    at unstable_runWithPriority (https://33nbi.csb.app/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)
    at flushSyncCallbackQueueImpl (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1820:7)
    at flushSyncCallbackQueue (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1808:3)
    at scheduleUpdateOnFiber (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11776:9)
    at updateContainer (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14747:3)
    at Object.create (https://33nbi.csb.app/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15455:5)
    at Object.eval (https://33nbi.csb.app/__test__/index.snapshot.test.js:15:23)
    at https://codesandbox.io/static/js/vendors~jest-lite.d7cf4386a.chunk.js:1:199229
    at new Promise (<anonymous>)
    at t.callAsyncFn (https://codesandbox.io/static/js/vendors~jest-lite.d7cf4386a.chunk.js:1:198888)
    at https://codesandbox.io/static/js/jest-lite.8233511c0.chunk.js:1:6536
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2675
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
    at https://codesandbox.io/static/js/jest-lite.8233511c0.chunk.js:1:6803
    at https://codesandbox.io/static/js/jest-lite.8233511c0.chunk.js:1:5468
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
```

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.5 |
| Browser | Google Chrome 83.0.4103.116（Official Build） |

**Comment by zombieJ** [comment]
Seems it not get dom node function correctly in your test. Since we do not use `react-scripts`, we can help less on it.

You can ref antd `render` demo test if use jest directly: https://github.com/ant-design/ant-design/blob/645bbacfd602363531b850694bdfe17d47fe598f/tests/shared/demoTest.ts
