### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by RickLucassen** [ant-design/ant-design#26621]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-h5f4k)

### Steps to reproduce
- Create eventlistener on "window" for "error". (window.addEventListener("error", (e) => console.error(e));)
- Render widget that renders a dropdown of some sort when clicking the input field.
- Click on the field.
- See "ResizeObserver loop limit exceeded" error message in console.

### What is expected?
For the error not to be generated

### What is actually happening?
Opening any kind of widget (dropdown) generates this error.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.11.0 |
| System | Ubuntu 20.04.1 |
| Browser | Chromium 85.0.4183.83 |

**Comment by afc163** [comment]
@cyjake 

https://github.com/react-component/resize-observer/pull/18
https://github.com/react-component/align/pull/72

**Comment by zombieJ** [comment]
Seems error has gone after refactor of `rc-trigger` & `rc-motion`.

**Comment by makarov-roman** [comment]
hi @zombieJ, is there any eta when those refactorings would make into release?

**Comment by makarov-roman** [comment]
hi @zombieJ, is there any eta when those refactorings would make into release?

**Comment by zombieJ** [comment]
@makarov-roman  remove your lock file and reinstall.

**Comment by gynekolog** [comment]
@zombieJ Remove lock file is not a good solution.
You can make It better by deleting antd part only from the lock file and run `yarn` or `npm-install` again.
Or upgrade only concretely packages (`rc-resize-observer`, `rc-align`, `rc-trigger`, `rc-motion` ?)

**Comment by nigulasikk** [comment]
> Seems error has gone after refactor of `rc-trigger` & `rc-motion`.

antd（v 4.16.9）中，还存在题主说的问题呢。例子：https://codesandbox.io/s/4ovng?file=/src/index.js

**Comment by citmusa** [comment]
Please reopen. As @nigulasikk shows this is still an issue

**Comment by scheinercc** [comment]
For completeness, the message text in Firefox and Safari reads:

> ResizeObserver loop completed with undelivered notifications.

---

> ResizeObserver loop limit exceeded

Is Chrome at all only

**Comment by hopperhuang** [comment]
will this bug be fixed?

**Comment by git-dingyc** [comment]
will this bug be fixed?

**Comment by 1006223320** [comment]
will this bug be fixed?

**Comment by mqliutie** [comment]
mark

**Comment by alienzhangyw** [comment]
Error comes out when clicking Select input

**Comment by ishan123456789** [comment]
> Hi I'm facing same error on Select component of antd version 4.17.2 any fix for this
https://github.com/ant-design/ant-design/issues/15075#issuecomment-1120156254

**Comment by afc163** [comment]
https://stackoverflow.com/a/58701523/3040605

**Comment by ishan123456789** [comment]
For anyone wanting to remove the popup from react you can use:
```
body > hmr-error-overlay { // This worked for me the container element might have changed so add change accordingly 
  display: none;
}
```
And to not let go of all the errors I added this block for error logging in the `index.jsx`

```
window.addEventListener('error', function (e) {
  console.error(e.message);
  // prevent React's listener from firing
  e.stopImmediatePropagation();
  // prevent the browser's console error message
  e.preventDefault();
});
```

**Comment by GrayYoung** [comment]
https://blog.csdn.net/MoveLikeRabbit/article/details/116997380
This article might help you to figure out the issue.

**Comment by GrayYoung** [comment]
Sucks, a waste of my time...

**Comment by nghiahc2** [comment]
still face this error with antd table

**Comment by mMarcos208** [comment]
@nghiahc2 I have the same issue when navigation to page that using Table component.

Any solution?

**Comment by nghiahc2** [comment]
@mMarcos208 i upgraded react from 17 to 18... And it works!

**Comment by quangnmwork** [comment]
Same isssue

**Comment by MudulOzan** [comment]
Still no update? I have the same problem

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-oevinj?file=/index.js The latest version of 4.x cannot reproduce this problem

**Comment by yoyo837** [comment]
> > https://codesandbox.io/s/antd-reproduction-template-forked-oevinj?file=/index.js The latest version of 4.x cannot reproduce this problem
> 
> I am using the latest tho still have this

How to reproduce, I can't reproduce it with 4.x latest.

**Comment by MudulOzan** [comment]
> > > https://codesandbox.io/s/antd-reproduction-template-forked-oevinj?file=/index.js The latest version of 4.x cannot reproduce this problem
> > 
> > 
> > I am using the latest tho still have this
> 
> How to reproduce, I can't reproduce it with 4.x latest.

I joined a complicated project I don't know all all posibilities but hear me out: Collapse inside Popover

I created a custom collapse component on my own and then put it inside Popover not a problem at all. Then I add one more css rule which is border bottom then I recieve this error. Pretty strange to me but I don't know how to reproduce or what causes this.

**Comment by MarcusCody** [comment]
I have the same issue with the Sider that is in collapsed mode when I click one of the menus in the Sider. The error will be prompted

**Comment by becausemon01** [comment]
I think this issue relationship with package **rc-resize-observer** . You can update version suitable

**Comment by tim-basic** [comment]
Also having issue with this

**Comment by vaibhavsharma9** [comment]
Try giving fixed width to antD select.
This works fore me

**Comment by aalvarezwindey** [comment]
Same issue when using `Table` component with `scroll={{ x: true }}`

**Comment by calinvasileandrei** [comment]
I have antd 4.18.5 and react 17 and got the same problem with the select... anyone has a quick fix?

**Comment by yoyo837** [comment]
Any one please provide a new reproduce link?

**Comment by busy-mango** [comment]
I have antd 4.24.10 and react 18 and got the same problem，this feels terrible

**Comment by Shen120** [comment]
This problem has always existed，this version is 4x@latest

**Comment by J4rvisW0ng** [comment]
+1

**Comment by alavrenteva** [comment]
+1

**Comment by FrankKleiton** [comment]
+1

**Comment by jamilalisgandarov** [comment]
+1

**Comment by asagcs** [comment]
+1

**Comment by gaochao-git** [comment]
现象：Table组件设置了scroll={{ x: 'max-content' }}或者scroll={{ x:true }}属性后点击菜单出现错误Modal弹窗，每次点击都会出现，错误信息如下
```
ERROR
ResizeObserver loop limit exceeded
    at handleError (http://localhost:3000/static/js/bundle.js:324281:58)
    at http://localhost:3000/static/js/bundle.js:324300:7
```

代码：
```
import React from 'react';
import { Table } from 'antd';

const MyTable = ({ dataSource, columns, rowKey="id" ,defaultPageSize=10}) => {
  return (
    <Table
      rowKey={rowKey}
      dataSource={dataSource}
      columns={columns}
      pagination={{
        defaultPageSize: defaultPageSize,
        pageSizeOptions: ['10','20','30','40','50','60','70','80','90','100','200','300','500'],
        showSizeChanger:true,
        showTotal:((total)=>{return `共${total}条`})
      }}
      scroll={{ x: 'max-content' }}
      bordered
      size="small"
    />
  );
};

export default MyTable;
```

package.json 配置文件
```
   ......
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "antd": "^5.6.1",
    "axios": "^1.4.0",
    "echarts": "^5.4.2",
    "echarts-for-react": "^3.0.2",
    "moment": "^2.29.4",
    "react": "^16.2.0",
    "react-codemirror2": "^7.2.1",
    "react-dom": "^16.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "5.0.1",
    "recharts": "^2.7.1",
    "web-vitals": "^2.1.4"
   ......
```
暂时解决：取消scroll={{ x: 'max-content' }}属性错误消失，但是滚动非常需要，目前只能凑合用了

**Comment by kthxboosty** [comment]
I observe this issue when I use `<Tabs>` component. When the contents of a tab are too large for the screen, a scrollbar appears. This scrollbar reduces the width. In my case this reduction in width means not all tabs can be fully seen next to each other, so the "overflow" menu appears (`class="ant-tabs-nav-operations"`). I'm not sure exactly which part triggers the error. 

Browser/OS: Firefox 114.0.2 on macOS 13.1.
Antd version: 4.24.10

```
Uncaught runtime errors:

ERROR

ResizeObserver loop completed with undelivered notifications.
handleError@http://localhost:3000/static/js/bundle.js:248399:58
./node_modules/webpack-dev-server/client/overlay.js/createOverlay/<@http://localhost:3000/static/js/bundle.js:248418:18
EventListener.handleEvent*listenToRuntimeError@http://localhost:3000/static/js/bundle.js:248591:10
createOverlay@http://localhost:3000/static/js/bundle.js:248411:84
./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true@http://localhost:3000/static/js/bundle.js:247118:105
options.factory@http://localhost:3000/static/js/bundle.js:286377:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:285793:33
@http://localhost:3000/static/js/bundle.js:286957:30
@http://localhost:3000/static/js/bundle.js:286961:12
```
Relevant part of package.json:
```
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@reduxjs/toolkit": "^1.3.6",
    "antd": "^4.23.6",
[...]
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-helmet": "^6.1.0",
    "react-inlinesvg": "^2.3.0",
    "react-json-view": "^1.21.3",
    "react-plotlyjs": "^0.4.4",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "^5.0.1",
    "react-window-size-listener": "^1.2.3",
    "reselect": "^4.0.0",
  },
```
rc-resize-observer versions of dependencies:
```
$ npm ls rc-resize-observer
project@1.0.0 /path/to/project
└─┬ antd@4.24.10
  ├─┬ rc-menu@9.8.4
  │ └─┬ rc-overflow@1.3.0
  │   └── rc-resize-observer@1.3.1 deduped
  ├── rc-resize-observer@1.3.1
  ├─┬ rc-select@14.1.17
  │ └─┬ rc-virtual-list@3.5.2
  │   └── rc-resize-observer@1.3.1 deduped
  ├─┬ rc-table@7.26.0
  │ └── rc-resize-observer@1.3.1 deduped
  ├─┬ rc-tabs@12.5.10
  │ └── rc-resize-observer@1.3.1 deduped
  └─┬ rc-textarea@0.4.7
    └── rc-resize-observer@1.3.1 deduped
```

**Comment by Ali-ovo** [comment]
I also have the same problem

react version： 17.0.1
antd version： 5.6.3

the business is so complicated that I can't know exactly what went wrong

but the error occurred when I upgraded from `v4` to `v5`

**Comment by hsluoyz** [comment]
Any update on this?

**Comment by Tangjj1996** [comment]
So, what's the solution?

**Comment by tsingsun** [comment]
Any update , tired of it in debug

**Comment by luann112** [comment]
I'm being stucked with this issue, anyone have the solution? 🙏🏿🙏🏿🙏🏿

**Comment by xyy94813** [comment]
It is caused by `rc-resize-observer@npm:1.3.1`.

----

In my project, there are multiple versions of `rc-resize-observer`
After I try to use the same version of `rc-resize-observer` by this way:

```
yarn set resolution rc-resize-observer@npm:^1.0.0 1.3.1
```

Every component using  `rc-resize-observer` will report this bug.

Between version `1.0.0`  and version `1.3.1`, ` rc-resize-observer` refactored as a function component.

---- 

I was only able to catch this error with `window.onerror`.

**Comment by yoyo837** [comment]
Any one provide a new reproduce link can catch the error? Please!

**Comment by xyy94813** [comment]
Is the error, which can only be caught by `window.onerror`, due to the following code logic?

https://github.com/react-component/resize-observer/blob/fe320b1be8b17eef1c67cea3ff3fafa507d45b1c/src/SingleObserver/index.tsx#L88-L93

-----
**Note:**

**This looping error has caused a DDOS attack to our error reporting system.**
You must to limit rate of report

**Comment by xyy94813** [comment]
Marker
https://stackoverflow.com/a/76254508

**Comment by Makentosh** [comment]
still have some problem
ResizeObserver loop completed with undelivered notifications.

"antd": "^4.21.7",
 "react": "^17.0.2",

**Comment by dingchao-ihealth** [comment]
adding a fixed width or max-size worked for me.

**Comment by LiangZugeng** [comment]
In my case, `scroll={{ x:true }}` in a Table caused this, removed this setting and this issue is solved.

Not sure why I added this setting in the first place, and the page didn't show any difference after the removal of the setting, the document [https://4x.ant.design/components/table/#scroll] also didn't describe `x: true` clearly.

**Comment by rickvian** [comment]
> adding a fixed width or max-size worked for me.

hi, what component is this, and is it ok if you provide the code example, it will help lots people here

**Comment by mMarcos208** [comment]
I remove yarn.lock and upgrade react, ant, react scripts and works for me.

**Comment by QF-study** [comment]
> > Seems error has gone after refactor of `rc-trigger` & `rc-motion`.
> 
> antd（v 4.16.9）中，还存在题主说的问题呢。例子：https://codesandbox.io/s/4ovng?file=/src/index.js

antd (v 4.24.9) 依然有

**Comment by YriiT** [comment]
i get this bug on table after update antd to v5.9.1
on 5.6.1 everything was all right

**Comment by Chevindu** [comment]
This is by no means a fix, but I was able to temporarily avoid this error by setting a fixed `height` to the culprit element. In my case it was the `.ant-popover-inner-content` of [Popover](https://ant.design/components/popover/). I'm hoping to migrate to Ant v5 soon, hopefully this will be patched by then.

Current versions:
- "antd": "4.24.13",
- "react": "18.2.0",

**Comment by gongwenlong** [comment]
> +1， v5.5.2，v4.24.2就没这个问题

you are right

**Comment by samanthaburboz** [comment]
Facing the  same problem
ResizeObserver loop completed with undelivered notifications.

"antd": "5.9.0",
"react": "^17.0.1",

Table and Modal component giving issue

import React from 'react';
import { Table } from 'antd';

const MyTable = ({ dataSource, columns, rowKey="id" ,defaultPageSize=10}) => {
  return (
    <Table
      rowKey={rowKey}
      dataSource={dataSource}
      columns={columns}
      scroll={{ x: 'max-content' }}
      bordered
      size="small"
    />
  );
};

export default MyTable;

Works if use Table without   scroll={{ x: 'max-content' }} or  size="small"

**Comment by zmbxy** [comment]
遇到了同样的问题，希望能够得到修复

**Comment by TrangPham** [comment]
Adding a fixed width and maxWidth worked for me to Select element

**Comment by LiliumCandidum** [comment]
I faced the same issue with the Table and the Popover component: I had a Popover inside a row of a table and when the Popover text was too long for the page size, the error appeared.
I fixed with calculating the Popover width based on the window width.

versions:

- antd: 4.24.8
- react: 18.2.0

**Comment by liyuyu0929** [comment]
> 现象：Table组件设置了scroll={{ x: 'max-content' }}或者scroll={{ x:true }}属性后点击菜单出现错误Modal弹窗，每次点击都会出现，错误信息如下
> 
> ```
> ERROR
> ResizeObserver loop limit exceeded
>     at handleError (http://localhost:3000/static/js/bundle.js:324281:58)
>     at http://localhost:3000/static/js/bundle.js:324300:7
> ```
> 
> 代码：
> 
> ```
> import React from 'react';
> import { Table } from 'antd';
> 
> const MyTable = ({ dataSource, columns, rowKey="id" ,defaultPageSize=10}) => {
>   return (
>     <Table
>       rowKey={rowKey}
>       dataSource={dataSource}
>       columns={columns}
>       pagination={{
>         defaultPageSize: defaultPageSize,
>         pageSizeOptions: ['10','20','30','40','50','60','70','80','90','100','200','300','500'],
>         showSizeChanger:true,
>         showTotal:((total)=>{return `共${total}条`})
>       }}
>       scroll={{ x: 'max-content' }}
>       bordered
>       size="small"
>     />
>   );
> };
> 
> export default MyTable;
> ```
> 
> package.json 配置文件
> 
> ```
>    ......
>     "@testing-library/jest-dom": "^4.2.4",
>     "@testing-library/react": "^9.3.2",
>     "@testing-library/user-event": "^7.1.2",
>     "antd": "^5.6.1",
>     "axios": "^1.4.0",
>     "echarts": "^5.4.2",
>     "echarts-for-react": "^3.0.2",
>     "moment": "^2.29.4",
>     "react": "^16.2.0",
>     "react-codemirror2": "^7.2.1",
>     "react-dom": "^16.2.0",
>     "react-router-dom": "^5.1.2",
>     "react-scripts": "5.0.1",
>     "recharts": "^2.7.1",
>     "web-vitals": "^2.1.4"
>    ......
> ```
> 
> 暂时解决：取消scroll={{ x: 'max-content' }}属性错误消失，但是滚动非常需要，目前只能凑合用了

我也碰到过，暂时用style={{marginBottom:'20px',overflowX:"auto",whiteSpace: 'nowrap'}} 可以实现滚动

**Comment by Jokasxy** [comment]
From [Webpack docs](https://webpack.js.org/configuration/dev-server/#overlay), I've found a way to suppress only this message.

```
config.client = {
	...config.client,
	overlay: {
		errors: true,
		runtimeErrors: (error) => {
			if (error.message === 'ResizeObserver loop completed with undelivered notifications.') {
				return false;
			}
			return true;
		},
		warnings: false,
	},
};
```

**Comment by rickvian** [comment]
if anyone catch this issue logged by sentry:
https://sentry.io/answers/react-resizeobserver-loop-completed-with-undelivered-notifications/

**Comment by jquintozamora** [comment]
I have the same issue while using Cascader component. 

It happens when I click on the 2nd level of the tree.

ResizeObserver loop completed with undelivered notifications.

**Comment by souvik1000** [comment]
**Used Ant-d Version**: 4.24.16

I'm facing the same issue when, 
I'm using the **ant-d table** with the props `scroll={{ x: '720px', y: 'calc(100vh - 282px)' }}`.

But when I removed x: '720px' from the scroll object, problem got fixed. 

I think, I have used as per the documentation only. But it was started throwing Error as `ResizeObserver loop completed with undelivered notifications`. Please look into this issue.

**Comment by reinaldo-teixeira** [comment]
I'm facing the same problem with cascader menu on antd `4.24.3`

**Comment by Michael2109** [comment]
This is occurring with the Select component with Antd `v5.17.2` upon clicking it. Is there a fix for this?

**Comment by Hin-Nattapat** [comment]
I'm facing the same problem when i use "scroll" table props in my project
i use antd v.4 , anyone have the solution for this?

**Comment by VAIBHAVCES** [comment]
Is there any solution ??? I also stuck with this error. I am not exactly sure which component is causing the error but for me this error is visible with `AutoComplete`.

```
            <AutoComplete
              className="create"
              style={ { minWidth: '150px' , maxWidth:'150px'} }
              getPopupContainer={() => document.querySelector('.create')}
              dataSource={this.state.searchUserResults}
              // style={{ width: '560px' }}
              placeholder="Type few characters of name"
              value={this.state.project.owner ? this.state.project.owner.name : ''}
              onSelect={(value, option) => this.handleOnUserSelect(value, option)}
              onSearch={this.handleUserSearch}
            />
```

AFAIK, this problem is occurring due to : `getPopupContainer={() => document.querySelector('.create')}`
After doing some brainstorming I tried multiple things but nothing able to help me till now.
1. Tried fixed styling to parent box and to the component
2. Tried to wrap AutoComplete in another div and mapped  getPopupContainer to the div, but not helped

One thing I would like to highlight maybe helpful for others is that when I map getPopupContainer to the Select it gets fixed for some cases. 

For me scenario is that I have one component Project on which there are 2 types of forms one for project update and one for project creation. Now in  ProjectUpdate its full width page where if and only if I am mapping `AutoComplete` with `Select` then it works for that page, but not for the other pages. 
Only difference between the create page is that in that page its not a full length page except that every thing is exactly same I tried to wrap up the AutoComplete boxes of  create page into divs and give them static styling but nothing is helping out. I tried to play around with a lot by manipulating Select AutoComplete etc but this doesn't helps

**Comment by afc163** [comment]
@VAIBHAVCES Could you try antd@5.19.4 ?

**Comment by VAIBHAVCES** [comment]
@afc163 Tried that. It doesn't helps. Weird thing its reproducible on a certain component. i mean I was using this for a long time in a existing component but it worked fine, but when I am copying this same logic into another component( just need same logic in another place) its getting burst with this error.
But considering the amount of time its taking to debug it, I have moved out to a common `Select` component

**Comment by SolidZORO** [comment]
> @VAIBHAVCES Could you try antd@5.19.4 ?

@afc163 

我目前在 `"antd": "^5.20.1",` 依然有这个问题。只要用了 `<Typography.Paragraph>` 的 `ellipsis` 基本上 99% 可复现。

**Comment by yoyo837** [comment]
> > @VAIBHAVCES Could you try antd@5.19.4 ?
> 
> @afc163
> 
> 我目前在 `"antd": "^5.20.1",` 依然有这个问题。只要用了 `<Typography.Paragraph>` 的 `ellipsis` 基本上 99% 可复现。

来个复现。

**Comment by SolidZORO** [comment]
@yoyo837  @afc163  测试了一下，发现 react 版本的问题，17 就会出现，18 是正常的。

antd5-react18-resizeobserver-loop https://5qk5n9.csb.app/ （✅ 正常）

antd5-react17-resizeobserver-loop https://w6gly5.csb.app/（❌ 出现 ResizeObserver loop）

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/03967e32-ad33-4f47-9e7c-696963ba0f6f">

**Comment by sparrowek** [comment]
I had the same problem when Tooltip was used with InputNumber and wrapped in Form.Input. 
The solution was to reoder them to:
`<Tooltip><FormInput><InputNumber /></FormInput></Tooltip>`

**Comment by triyys** [comment]
I had the same problem when using `scroll={{ x: 'max-content' }}` in `Table` component.

```
"antd": "^4.24.14",
"react": "^17.0.2",
```

**Comment by xiaoyierle** [comment]
I had the same problem when using scroll={{ x: 'max-content' }} in Table component.
"antd": "^5.19.3",
"react": "^17.0.2",

**Comment by vidhanshu** [comment]
I'm facing the same error with table component with scroll={{x:"max-content"}} prop passed to it, and just checked otherwise also it's coming frequently

**Comment by Yovven** [comment]
之前一直没有报错，最近在 chrome 最新版本中出现报错 ”ResizeObserver loop completed with undelivered notifications“, 包括以下两个使用场景
1. <Table> 中设置了 scroll={{x:'650px'}}
2. <Typography.Paragraph> 使用 ellipsis

使用 react 17， antd@4.24.0

Table 组件的可以先暂时设置 datasource 默认值为 [{}] 的方式来规避，参考 [https://juejin.cn/post/7262623363700981797](url)

**Comment by RoystonDias1996** [comment]
Getting this same issue while using antd menu, with which mode property is set to horizontal

"Uncaught ResizeObserver loop completed with undelivered notifications."

Following is the config:
- The menu is used inside a modal. 
- antd version is 5
- react version is 18

**Comment by seho-dev** [comment]
If the problem is caused by the scroll property of the table component, you can use the following solution for the time being

```
import { useEffect, useState, useMemo } from 'react';
import { Table } from 'antd';

const OptimizedAntdTable = ({
  scroll: scrollProp,
  dataSource = [],
  children: childrenProp,
  ...restProps
}) => {
  const [canScroll, setCanScroll] = useState(false);

  useEffect(() => {
    if (dataSource?.length) {
      setCanScroll(true);
    }
  }, [dataSource]);

  const scroll = useMemo(() => {
    if ((restProps.components?.body || canScroll) && scrollProp) {
      return scrollProp;
    }
    return undefined;
  }, [scrollProp, restProps.components]);

  return (
    <Table scroll={scroll} dataSource={dataSource} {...restProps}>
      {childrenProp}
    </Table>
  );
};

export default OptimizedAntdTable;

```

```
<OptimizedAntdTable {...props} />
```

**Comment by yoyo837** [comment]
If you are still encountering this issue in version 5.x or 6.x, please feel free to create a new issue. Thank you.
