### ISSUE TITLE
初始化redux 的demo报错

### ISSUE THREAD

**Issue by janjon** [ant-design/ant-design#2691]
```
utils.js:188uncaught at root 
 at _callee 
 at watchTodosGet 
 at watchTodosGet 
 at getTodos 
 Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
    at invariant (http://localhost:9111/index.js:278:16)
    at traverseAllChildrenImpl (http://localhost:9111/index.js:9442:56)
    at traverseAllChildren (http://localhost:9111/index.js:9470:11)
    at Object.instantiateChildren (http://localhost:9111/index.js:29303:8)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:9111/index.js:34006:42)
    at ReactDOMComponent.mountChildren (http://localhost:9111/index.js:34043:28)
    at ReactDOMComponent._createInitialChildren (http://localhost:9111/index.js:31260:33)
    at ReactDOMComponent.mountComponent (http://localhost:9111/index.js:31076:13)
    at Object.mountComponent (http://localhost:9111/index.js:3495:36)
    at ReactDOMComponent.mountChildren (http://localhost:9111/index.js:34054:45)
```

求解啊！正在寻找框架

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/antd-init/issues/104
