### ISSUE TITLE
Error: write EPIPE in node 15

### ISSUE THREAD

**Issue by liuxiaocong** [ant-design/ant-design#29521]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8001/](http://localhost:8001/)

### Steps to reproduce
$ git clone git@github.com:ant-design/ant-design.git
$ cd ant-design
$ npm install
$ npm start

启动失败 （npm版本：15.5）
通过nvm将npm版本改成：v10.23.3后
启动成功

### What is expected?
正常启动

### What is actually happening?
无法启动

| Environment | Info |
|---|---|
| antd | undefined |
| React | 17 |
| System | mac |
| Browser | chrome |

---
[1] [Error: ENOTDIR: not a directory, scandir '/Users/evan.liu/evan/antd-design-orange/node_modules/@umijs/fabric/dist/fabric.rc/src'] {
[1]   errno: -20,
[1]   code: 'ENOTDIR',
[1]   syscall: 'scandir',
[1]   path: '/Users/evan.liu/evan/antd-design-orange/node_modules/@umijs/fabric/dist/fabric.rc/src'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at ChildProcess.target._send (node:internal/child_process:846:20)
[1]     at ChildProcess.target.send (node:internal/child_process:719:19)
[1]     at arrange (/Users/evan.liu/evan/antd-design-orange/node_modules/bisheng/lib/loaders/common/boss.js:35:12)
[1]     at ChildProcess.<anonymous> (/Users/evan.liu/evan/antd-design-orange/node_modules/bisheng/lib/loaders/common/boss.js:41:9)
[1]     at Object.onceWrapper (node:events:483:26)
[1]     at ChildProcess.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:917:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by afc163** [comment]
Error: write EPIPE 这个问题我也遇到了，再次 npm start 就能启动。

要再看一下问题原因，加 nvmrc 不是彻底的解决半部分。

**Comment by yoyo837** [comment]
其实就是不兼容当前node.js 版本。

**Comment by liuxiaocong** [comment]
> Error: write EPIPE 这个问题我也遇到了，再次 npm start 就能启动。
> 
> 要再看一下问题原因，加 nvmrc 不是彻底的解决办法。

感觉应该就是不支持最新版本的npm 15.5

**Comment by afc163** [comment]
- https://github.com/facebook/jest/issues/10144
- https://github.com/facebook/create-react-app/issues/9077

**Comment by afc163** [comment]
完整的报错信息：

```
🌈  antd-test-husky@4.12.3 git:❨upgrade❩ npm start

> antd@4.12.3 prestart
> npm run version


> antd@4.12.3 version
> node ./scripts/generate-version


> antd@4.12.3 start
> antd-tools run clean && cross-env NODE_ENV=development concurrently "npm run color-less" "bisheng start -c ./site/bisheng.config.js"

antd-tools run clean
[0] 
[0] > antd@4.12.3 color-less
[0] > node ./scripts/generate-color-less
[0] 
[0] 🔩 less render start!
[1] ℹ Compiling 🚚  Bisheng
[1] ℹ ｢wds｣: Project is running at http://localhost/
[1] ℹ ｢wds｣: webpack output is served from undefined
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/afc163/Projects/antd-test-husky/_site
[1] ℹ ｢wds｣: 404s will fallback to /index.html
[1] node:internal/process/promises:225
[1]           triggerUncaughtException(err, true /* fromPromise */);
[1]           ^
[1] 
[1] [Error: ENOTDIR: not a directory, scandir '/Users/afc163/Projects/antd-test-husky/node_modules/@umijs/fabric/dist/fabric.rc/src'] {
[1]   errno: -20,
[1]   code: 'ENOTDIR',
[1]   syscall: 'scandir',
[1]   path: '/Users/afc163/Projects/antd-test-husky/node_modules/@umijs/fabric/dist/fabric.rc/src'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at ChildProcess.target._send (node:internal/child_process:839:20)
[1]     at ChildProcess.target.send (node:internal/child_process:710:19)
[1]     at arrange (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/boss.js:35:12)
[1]     at ChildProcess.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/boss.js:41:9)
[1]     at Object.onceWrapper (node:events:483:26)
[1]     at ChildProcess.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on ChildProcess instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] node:events:353
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (node:internal/child_process:839:20)
[1]     at process.target.send (node:internal/child_process:710:19)
[1]     at process.<anonymous> (/Users/afc163/Projects/antd-test-husky/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (node:events:376:20)
[1]     at emit (node:internal/child_process:910:12)
[1]     at processTicksAndRejections (node:internal/process/task_queues:81:21)
[1] Emitted 'error' event on process instance at:
[1]     at node:internal/child_process:843:39
[1]     at processTicksAndRejections (node:internal/process/task_queues:75:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
```

**Comment by afc163** [comment]
看上去和 https://github.com/umijs/fabric/blob/6badc8a9bc913c0902a16e1ddc1bfb3d55d1e99d/src/eslint.ts#L34 这句话有关系。

**Comment by afc163** [comment]
上面这段代码也会影响 umi/Bigfish 项目的首次 npm start 的速度。

@sorrycc 关注一下

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/29521

**Comment by yoyo837** [comment]
@afc163 关联issue写错了？
