### ISSUE TITLE
Warning: `label` of `value` is not same as `label` in Select options. 

### ISSUE THREAD

**Issue by mperu92** [ant-design/ant-design#29908]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
I don't know how to reproduce it, it triggered the warning over devtools console apparently at any moment

### What is expected?
To know what could be the cause

### What is actually happening?
The Select component triggers this waring over browser console:
Warning: `label` of `value` is not same as `label` in Select options. 
    at Select (webpack-internal:///./node_modules/rc-select/es/generate.js:79:34)
    at Select (webpack-internal:///./node_modules/rc-select/es/Select.js:85:94)
    at InternalSelect (webpack-internal:///./node_modules/antd/es/select/index.js:44:31)
    at div
    at div
    at div
    at div
    at form
    at div
    at ManageProject (webpack-internal:///./Scripts/js/libs/components/frontend/Container/Partials/items/ManageProject.js:102:89)
    at div
    at BPDesk (webpack-internal:///./Scripts/js/libs/components/frontend/Container/Partials/BPDesk.js:209:89)
    at div
    at div
    at BPContainer (webpack-internal:///./Scripts/js/libs/components/frontend/Container/BPContainer.js:67:89)
    at App (webpack-internal:///./Scripts/js/libs/components/frontend/App.js:103:89)

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.8.6 |
| System | Winows 10 for workstations (more than 4 cores) |
| Browser | Google Chrome 89.0.4389.90 (official build - 64 bit) |

---
if I click on the path to my file it marks me this line of code (it is the compilation of webpack, it is not my original code)
_babel_runtime_corejs3_helpers_classCallCheck__WEBPACK_IMPORTED_MODULE_2___default()(this, ManageProject);

it do not seems a critical problem  but i would know what could be the cause

**Comment by hanalice** [comment]
@mperu92 我是在Select 的Option标签中使用了FormattedMessage 标签引发的此问题，但是在live 的环境中由于codeSandbox 无法引入umi 导致我无法重现这个问题。
