### ISSUE TITLE
React Testing Library "not wrapper in act(...)" warnings while testing antd Tabs

### ISSUE THREAD

**Issue by avatsavirs** [ant-design/ant-design#30964]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/avatsavirs/antd-tab-tests](https://github.com/avatsavirs/antd-tab-tests)

### Steps to reproduce
Run tests using npm test

### What is expected?
Tests run successfully without any warning. 

### What is actually happening?
Tests run successfully but with "An update to ForwardRef(TabNavList) inside a test was not wrapped in act(...)" warnings. 

| Environment | Info |
|---|---|
| antd | 4.13.0 |
| React | 17.0.2 |
| System | Ubuntu 20.04 |
| Browser | Firefox 89.0 |

---
I leave the tests running for 100ms at the end of the test case to make sure there are no unexpected changes. With antd Tabs this triggers multiple "not wrapped in act(...)" warnings, indicating some unintentional changes. These warning can we prevented if we manually unmount the component before the test is over. This makes testing components using ant-design Tabs problematic.  I want to know what's causing this unintentional change and how can it be prevented so I don't have to manually unmount the component before each test is over.

**Comment by amed** [comment]
This is confirmed on `v4.16.2`

```
    Warning: An update to Menu inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
```

**Comment by shikelong** [comment]
+1.  The warning printed out in antd@4.15.0

```bash
 Warning: An update to Upload inside a test was not wrapped in act(...).
```

**Comment by Lukazovic** [comment]
I am having the same issue. The workaround I found is to wrap the first `expect` into a `waitFor(() => {})`.

Example:
```jsx
import React from 'react';
import { Menu } from 'antd';

import { render, screen, waitFor } from '@testing-library/react';

const Component = () => (
  <Menu>
    <Menu.Item key="item-1">Item #1</Menu.Item>
    <Menu.Item key="item-2">Item #2</Menu.Item>
  </Menu>
);

describe('<Component />', () => {
  it('should render with items', async () => {
    render(<Component />);

    await waitFor(() => {
      expect(screen.getByText('Item #1')).toBeInTheDocument();
    });
    expect(screen.getByText('Item #2')).toBeInTheDocument();
  });
});
```

**Comment by balavishnuvj** [comment]
#31595

**Comment by reneolivo** [comment]
@Lukazovic unfortunately `waitFor` supresses all kind of errors. I was not able to debug an issue with my component because the `waitFor` was catching the error and not displaying it.

**Comment by EricVanDerDijs** [comment]
I received this error testing a behavior using the onClick on the Menu component, I fixed it calling cleanup at the end of the test

```
import { cleanup } from '@testing-library/react'

test('Some test, () => {
  // ... here goes test body
  // at the end I call cleanup()
  cleanup()
})
```

Not sure if this is the correct approach, my environment is:

```
MacOS: 11.5.1 (20G80)
antd: 4.16.13
react: 17.0.2

```

**Comment by kaiba42** [comment]
bump

**Comment by micaelomota** [comment]
Facing the same issue, I wrap the code with `act` but still...

    Warning: An update to ForwardRef(TabNavList) inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at TabNavLis

**Comment by elotgamu** [comment]
I was able to reproduce the issue as well by having a Menu with Menu items components.

But my test just check text is in home page

Packages:
```
"@testing-library/jest-dom": "^5.16.4",
"@testing-library/react": "^13.3.0",
"@testing-library/user-event": "^13.5.0",
"antd": "^4.21.4",
"axios": "^0.27.2",
"react": "^18.2.0",
```

I was able to get rid of the warning by using the `findBy*` method which 
applies an underlying `act` call

```js
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import App from "./App";

test("renders welcome message", async () => {
  render(<App />, { wrapper: MemoryRouter });

  // find a simple text which is async 
  const welcomeMessage = await screen.findByText(/Welcome to my blog!!!/i);
  expect(welcomeMessage).toBeInTheDocument();
});

```


```jsx
import "./App.css";
import { Layout, Menu } from "antd";

import { Link, Route, Routes } from "react-router-dom";

import Posts from "./pages/Posts";
import Homepage from "./pages/HomePage";
import About from "./pages/About";

const { Header, Content, Footer } = Layout;

const navItems = [
  { label: "Home", key: "home", path: "/" },
  { label: "Posts", key: "post", path: "/posts" },
  { label: "About", key: "about", path: "/about" },
];

function App() {
  return (
    <Layout className="layout">
      <Header>
        <div className="logo" />
        <Menu
          theme="dark"
          mode="horizontal"
          defaultSelectedKeys={["2"]}
          items={navItems.map((item) => ({
            key: item.key,
            label: (
              <Link to={item.path} title={item.label}>
                {item.label}
              </Link>
            ),
          }))}
        />
      </Header>
      <Content className="layout-content">
        <div className="site-layout-content">
          <Routes>
            <Route path="/posts" element={<Posts />} />
            <Route path="/about" element={<About />} />
            <Route path="/" element={<Homepage />} />
          </Routes>
        </div>
      </Content>
      <Footer
        style={{
          textAlign: "center",
        }}
      >
        Blog Post app
      </Footer>
    </Layout>
  );
}

export default App;

```

**Comment by bdwade100** [comment]
This is confirmed on v4.23.6 when writing tests involving the <Menu> component:

```
    Warning: An update to ForwardRef inside a test was not wrapped in act(...).        
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in ForwardRef (created by ForwardRef)
        in ForwardRef (created by Context.Consumer)
        in Menu (at AdvancedPlotsMenu.tsx:107)
        in AdvancedPlotsMenu (at AdvancedPlotsMenuTests.tsx:28)

      at consoleObject.<computed> [as error] (node_modules/filter-console/index.js:46:4)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at forceUpdate (node_modules/rc-menu/lib/hooks/useKeyRecords.js:58:7)
      at node_modules/rc-menu/lib/hooks/useKeyRecords.js:76:9

```

**Comment by albertininm** [comment]
I managed to get this warn gone by using `jest.runOnlyPendingTimers`.
As someone said above, `waitFor suppresses all kind of errors`, that's why I avoid using it.

I used to have this:
```typescript
describe('Component: Menu', () => {
  it('should render the component', async () => {
    render(<Menu />);

    const menu = screen.getByRole('menu');

    expect(menu).toBeInTheDocument();
  });
});
```

and now I have this which runs with no warnings:

```typescript
describe('Component: Menu', () => {
  beforeAll(() => {
    jest.useFakeTimers();
  });

  afterAll(() => {
    jest.useFakeTimers();
  });

  it('should render the component', async () => {
    render(<Menu />);

    await act(async () => {
      jest.runOnlyPendingTimers();
    });

    const menu = screen.getByRole('menu');

    expect(menu).toBeInTheDocument();
  });
});
```

This problem usually happens when your component has some animations or when the test involves user events.
