### ISSUE TITLE
Menu component generates React warnings after update to v4.16.x

### ISSUE THREAD

**Issue by pkyeck** [ant-design/ant-design#31025]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-menu-4163-lyz43?file=/index.js)

### Steps to reproduce
open dev-tools and look into console

### What is expected?
No warnings should be triggered

### What is actually happening?
```
Warning: React does not recognize the `eventKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `eventkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at p
    at ul
    at Overflow (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:42:32)
    at InheritableContextProvider (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:39:23)
    at Menu (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:76:32)
    at InternalMenu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:52:33)
    at Menu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:121:33)
    at div
    at div
    at ul
    at Overflow (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:42:32)
    at InheritableContextProvider (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:39:23)
    at Menu (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:76:32)
    at InternalMenu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:52:33)
    at Menu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:121:33)
    at div
```

and

```
Warning: React does not recognize the `warnKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `warnkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at p
    at ul
    at Overflow (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:42:32)
    at InheritableContextProvider (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:39:23)
    at Menu (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:76:32)
    at InternalMenu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:52:33)
    at Menu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:121:33)
    at div
    at div
    at ul
    at Overflow (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:42:32)
    at InheritableContextProvider (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:39:23)
    at Menu (eval at Z (https://codesandbox.io/static/js/sandbox.abede95bc.js:1:101083), <anonymous>:76:32)
    at InternalMenu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:52:33)
    at Menu (https://lyz43.csb.app/node_modules/antd/es/menu/index.js:121:33)
    at div
```

| Environment | Info |
|---|---|
| antd | 4.16.3 |
| React | 17.0.2 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/31055#issuecomment-865491024

**Comment by pkyeck** [comment]
@afc163 why wasn't it a breaking change then? If something was working before and isn't after an update that should have been a major release :(

**Comment by jailsonpaca** [comment]
I use this lines in files with the problem
   ```
 delete otherProps.eventKey;
    delete otherProps.warnKey;
```

**Comment by Mihai-github** [comment]
Hi, 
   I do not really understand how to use your fix, can you provide a simple example if I am not asking for too much?

> I use this lines in files with the problem
> 
> ```
> delete otherProps.eventKey;
>  delete otherProps.warnKey;
> ```

Hi, 
   I do not really understand how to use your fix, can you provide a simple example if I am not asking for too much?

**Comment by AbhisekJS** [comment]
> I use this lines in files with the problem
> 
> ```
> delete otherProps.eventKey;
>  delete otherProps.warnKey;
> ```

Please put an example
