### ISSUE TITLE
2.0 window is not defined

### ISSUE THREAD

**Issue by TDiDa** [ant-design/ant-design#3146]
跟着官网http://beta.ant.design/docs/react/practical-projects的项目实战
安装cnpm install antd@beta babel-plugin-import --save

编辑 webpack.config.js
` webpackConfig.babel.plugins.push(['antd', {
   libraryName: 'antd',
   style: 'css',
 }]);
`

npm start 后报错

``ERROR in ./src/index.js
Module build failed: ReferenceError: window is not defined
    at /Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:36455:10
    at Object.defineProperty.value (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:36465:3)
    at __webpack_require__ (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:36:30)
    at webpackContext (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:34158:10)
    at /Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:35826:12
    at Array.forEach (native)
    at Object.defineProperty.value (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:35825:13)
    at __webpack_require__ (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:36:30)
    at Object.module.exports (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:86:19)
    at __webpack_require__ (/Users/TDiDa/takeAway-BMS/node_modules/.2.0.0-beta.11@antd/dist/antd.js:36:30)
 @ multi index``

**Comment by benjycui** [comment]
配置方式错了，改为下面的试试 

```js
webpackConfig.babel.plugins.push(['import', { libraryName: 'antd', style: 'css', }]); 
```

**Comment by benjycui** [comment]
cc @sorrycc

**Comment by TDiDa** [comment]
OK了， 官网的例子得修正下
