### ISSUE TITLE
Unable to start project, some error shows up: "Error: write EPIPE."

### ISSUE THREAD

**Issue by iamyoki** [ant-design/ant-design#31670]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8001/index-cn](http://localhost:8001/index-cn)

### Steps to reproduce
1. clone https://github.com/ant-design/ant-design.git
2. yarn  (or npm i)
3. yarn start (or npm start)

### What is expected?
Start successfully.

### What is actually happening?
Start failed with error messages:
```
ant-design master ✗  yarn start  
yarn run v1.22.11
$ npm run version

> antd@4.16.10 version
> node ./scripts/generate-version

$ antd-tools run clean && cross-env NODE_ENV=development concurrently "npm run color-less" "bisheng start -c ./site/bisheng.config.js"
antd-tools run clean
[0] 
[0] > antd@4.16.10 color-less
[0] > node ./scripts/generate-color-less
[0] 
[0] 🔩 less render start!
[1] ℹ Compiling 🚚  Bisheng
[1] ℹ ｢wds｣: Project is running at http://localhost/
[1] ℹ ｢wds｣: webpack output is served from undefined
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/yoki/Code/ant-design/_site
[1] ℹ ｢wds｣: 404s will fallback to /index.html
[0] 🌈 Theme generated successfully. OutputFile: /Users/yoki/Code/ant-design/_site/color.less
[0] 🎩 less render end!
[0] npm run color-less exited with code 0
[1] /Users/yoki/Code/ant-design/node_modules/@babel/types/lib/definitions/utils.js:130
[1]     throw new TypeError(`Property ${key} of ${node.type} expected node to be of a type ${JSON.stringify(types)} but instead got ${JSON.stringify(val == null ? void 0 : val.type)}`);
[1]     ^
[1] 
[1] TypeError: Property body[36] of BlockStatement expected node to be of a type ["Statement"] but instead got "AssignmentExpression"
[1]     at validate (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/definitions/utils.js:130:11)
[1]     at validator (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/definitions/utils.js:101:7)
[1]     at Object.validate (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/definitions/utils.js:227:7)
[1]     at validateField (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/validators/validate.js:24:9)
[1]     at validate (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/validators/validate.js:17:3)
[1]     at builder (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/builders/builder.js:38:27)
[1]     at Object.blockStatement (/Users/yoki/Code/ant-design/node_modules/@babel/types/lib/builders/generated/index.js:284:31)
[1]     at transformer (/Users/yoki/Code/ant-design/node_modules/bisheng-plugin-react/lib/transformer.js:114:27)
[1]     at module.exports (/Users/yoki/Code/ant-design/node_modules/@ant-design/bisheng-plugin/lib/process-demo.js:151:15)
[1]     at module.exports (/Users/yoki/Code/ant-design/node_modules/@ant-design/bisheng-plugin/lib/node.js:17:12)
[1] events.js:377
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (internal/child_process.js:839:20)
[1]     at process.target.send (internal/child_process.js:710:19)
[1]     at process.<anonymous> (/Users/yoki/Code/ant-design/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (events.js:400:28)
[1]     at emit (internal/child_process.js:910:12)
[1]     at processTicksAndRejections (internal/process/task_queues.js:83:21)
[1] Emitted 'error' event on process instance at:
[1]     at internal/child_process.js:843:39
[1]     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] events.js:377
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: write EPIPE
[1]     at process.target._send (internal/child_process.js:839:20)
[1]     at process.target.send (internal/child_process.js:710:19)
[1]     at process.<anonymous> (/Users/yoki/Code/ant-design/node_modules/bisheng/lib/loaders/common/worker.js:15:11)
[1]     at process.emit (events.js:400:28)
[1]     at emit (internal/child_process.js:910:12)
[1]     at processTicksAndRejections (internal/process/task_queues.js:83:21)
[1] Emitted 'error' event on process instance at:
[1]     at internal/child_process.js:843:39
[1]     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[1]   errno: -32,
[1]   code: 'EPIPE',
[1]   syscall: 'write'
[1] }
[1] bisheng start -c ./site/bisheng.config.js exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ant-design master ✗  
```

| Environment | Info |
|---|---|
| antd | 4.16.10 |
| React | react |
| System | Macos 11 |
| Browser | last 1 chrome version |

---
node: v14.17.4
npm: 7.20.3
yarn: v1.22.11

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29521#issuecomment-787576664

```
yarn cache clean
git clean -fdx
yarn
yarn start
```

**Comment by algirdaspaskevicius** [comment]
Be careful running `git clean -fdx` command, as it deletes all untracked git files without the ability to restore them!
