### ISSUE TITLE
4.17.0-alpha.2 编译报错 style/index-default.css

### ISSUE THREAD

**Issue by wangjianio** [ant-design/ant-design#32108]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
`antd/es/style` 里没有 `index-default.css` 这个文件

### What is expected?
正常启动项目

### What is actually happening?
```
ERROR in ./node_modules/antd/es/spin/style/css.js 1:0-39
Module not found: Error: Can't resolve '../../style/index-default.css'
```

| Environment | Info |
|---|---|
| antd | 4.17.0-alpha.2 |
| React | 17.0.2 |
| System | macOS 11.2.3 |
| Browser | Chrome 93 |

---
4.16.13 是好的

**Comment by DaoxingHuang** [comment]
@zombieJ 我这里在最新的master 代码 会出现错误 ，感觉跟这次提交有关

**Comment by DaoxingHuang** [comment]
![image](https://user-images.githubusercontent.com/19969260/132807633-70658c6a-7cc3-41ee-826b-dfa4d2000e4a.png)

**Comment by DaoxingHuang** [comment]
主要是由variable.less 引起的

**Comment by zombieJ** [comment]
两个不是同一件事情，这个是 css.js 引用到了不存在的文件上：https://unpkg.com/browse/antd@4.17.0-alpha.2/es/button/style/

**Comment by DaoxingHuang** [comment]
> 两个不是同一件事情，这个是 css.js 引用到了不存在的文件上：https://unpkg.com/browse/antd@4.17.0-alpha.2/es/button/style/

![image](https://user-images.githubusercontent.com/19969260/132978025-c6297c22-140b-443e-8af2-5299a55beb7b.png)
@zombieJ  你这 没有这个编辑的问题吗？我无论 是fork的 master 还是 官方的master 都 有这个问题
日记文件：line: @import (reference) '../../../components/style/themes/variable.less'; filePath:/Users/daoxing.huang/Documents/GitHub/upstream/ant-design/site/theme/static/theme.less
错误信息：
[0] error TypeError: Cannot read property '1' of null
[0]     at /Users/daoxing.huang/Documents/GitHub/upstream/ant-design/node_modules/antd-theme-generator/index.js:754:62
[0]     at Array.map (<anonymous>)
[0]     at combineLess (/Users/daoxing.huang/Documents/GitHub/upstream/ant-design/node_modules/antd-theme-generator/index.js:751:6)
[0]     at generateTheme (/Users/daoxing.huang/Documents/GitHub/upstream/ant-design/node_modules/antd-theme-generator/index.js:454:28)
[0]     at Object.<anonymous> (/Users/daoxing.huang/Documents/GitHub/upstream/ant-design/scripts/generate-color-less.js:50:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
