### ISSUE TITLE
back top 编译出错。

### ISSUE THREAD

**Issue by lincolnge** [ant-design/ant-design#3283]
#### 发生问题的环境是：

~/Desktop/work/tech/turbo/turbo_project/node_modules/gulp/node_modules/orchestrator/index.js:153
			throw err;
			^

ReferenceError: window is not defined
    at ~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/components/back-top/index.tsx:55:1
    at Object.defineProperty.value (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/components/back-top/index.tsx:65:2)
    at __webpack_require__ (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/webpack/bootstrap 7748098c79ae00940d3f:19:1)
    at webpackContext (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/components ^\.\/[^_][\w-]+\/(style\/):103:1)
    at ~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/index.js:15:1
    at Array.forEach (native)
    at Object.defineProperty.value (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/index.js:14:1)
    at __webpack_require__ (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/webpack/bootstrap 7748098c79ae00940d3f:19:1)
    at Object.module.exports (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/antd.js:86:19)
    at __webpack_require__ (~/Desktop/work/tech/turbo/turbo_project/node_modules/antd/dist/webpack:/webpack/bootstrap 7748098c79ae00940d3f:19:1)

- antd 版本: 2.0.1
- 操作系统及其版本: Mac OS X 10.11.6
- 浏览器及其版本: Chrome

#### 您做了什么？

编译的时候就出错了

**Comment by benjycui** [comment]
可以提供个能重现问题的 repo？

**Comment by binzeehale** [comment]
多久出小版本，我也遇到这个问题了
