### ISSUE TITLE
关于“在 create-react-app 中使用”，@craco/craco和craco-less方式配置主题一直报错

### ISSUE THREAD

**Issue by OlyLis1005** [ant-design/ant-design#33072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/OlyLis1005/react-template](https://github.com/OlyLis1005/react-template)

### Steps to reproduce
原本是react-script@4.0.3 @craco/craco6.4.0，报错This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version
然后按照craco-less的test version配置（也就是@craco/craco@5.5.0和react-script@3.2.0），依然报相同错误

### What is expected?
正常运行

### What is actually happening?
"D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run craco-start --scripts-prepend-node-path=auto

> react-template@0.1.0 craco-start D:\Study\react-template
> cross-env NODE_ENV=development craco start

D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\plugin-utils.js:29
    throw new Error(
    ^

Error: Found an unhandled loader in the development webpack config: D:\Study\react-template\node_modules\_style-loader@1.0.0@style-loader\dist\index.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the DocSpring/craco-less repo:

   * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue webpack unknown rule

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue webpack unknown rule
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue webpack unknown rule

    at throwUnexpectedConfigError (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\plugin-utils.js:29:11)
    at throwError (D:\Study\react-template\node_modules\_craco-less@1.20.0@craco-less\lib\craco-less.js:14:5)
    at D:\Study\react-template\node_modules\_craco-less@1.20.0@craco-less\lib\craco-less.js:100:9
    at Array.forEach (<anonymous>)
    at createLessRule (D:\Study\react-template\node_modules\_craco-less@1.20.0@craco-less\lib\craco-less.js:32:13)
    at Object.overrideWebpackConfig (D:\Study\react-template\node_modules\_craco-less@1.20.0@craco-less\lib\craco-less.js:127:18)
    at overrideWebpack (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\features\plugins.js:42:40)
    at D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\features\plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\features\plugins.js:63:29)
    at mergeWebpackConfig (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\features\webpack\merge-webpack-config.js:67:30)
    at overrideWebpackDev (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\lib\features\webpack\override.js:11:36)
    at Object.<anonymous> (D:\Study\react-template\node_modules\_@craco_craco@5.5.0@@craco\craco\scripts\start.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-template@0.1.0 craco-start: `cross-env NODE_ENV=development craco start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-template@0.1.0 craco-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Roaming\npm-cache\_logs\2021-11-29T02_53_38_741Z-debug.log

Process finished with exit code 1

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
我本地按文档跑了一遍，没发现问题。

**Comment by OlyLis1005** [comment]
> 我本地按文档跑了一遍，没发现问题。

可以分享一下你的package.json吗，我的问题还没解决🤣

**Comment by afc163** [comment]
最好是你提供错的 repo，这样我可以帮助你找到问题。

**Comment by OlyLis1005** [comment]
> 最好是你提供错的 repo，这样我可以帮助你找到问题。

https://github.com/OlyLis1005/react-template.git

**Comment by afc163** [comment]
<img width="1597" alt="图片" src="https://user-images.githubusercontent.com/507615/143812171-7904342c-fcc6-4c83-87c6-44ed61c357b7.png">

你提供的 repo 我测试下来也没发现问题。

```
yarn
yarn craco-start
```

**Comment by OlyLis1005** [comment]
> <img alt="图片" width="1597" src="https://user-images.githubusercontent.com/507615/143812171-7904342c-fcc6-4c83-87c6-44ed61c357b7.png">
> 
> 你提供的 repo 我测试下来也没发现问题。
> 
> ```
> yarn
> yarn craco-start
> ```

omg！我再研究下吧😱，我试试yarn

**Comment by OlyLis1005** [comment]
问题解决了，似乎是 `cnpm` 的锅，虽然安装依赖成功，但是运行时候报错。之后分别重新试了 `npm install` 和 `yarn` 去安装依赖，都可以正常运行。`npm` 有时候也会失败，使用 `yarn` 就比较稳定。具体原因就不清楚了🤔
