### ISSUE TITLE
Table component rowSelection type does not work with TS 

### ISSUE THREAD

**Issue by andrewfschorr** [ant-design/ant-design#33162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-sunset-qx09p?file=/src/App.tsx)

### Steps to reproduce
in a typescript project add `type: 'radio'` to the object that is passed to `rowSelection` of the table props. In the example codesandbox it works, however it errors with the TS error page and the message: `Type 'string' is not assignable to type 'RowSelectionType | undefined'.  TS2322` 

### What is expected?
It should compile. 

### What is actually happening?
It errors. Something having to do with https://github.com/ant-design/ant-design/blob/master/components/table/interface.tsx#L20 this line 

| Environment | Info |
|---|---|
| antd | 4.17.2 |
| React | 17.0.2 |
| System | OSX 11.6 |
| Browser | Version 96.0.4664.55 |

---
It works with `type: 'checkbox' as 'checkbox'` 

Additionally I was going to fix myself, and submit a PR however when I follow the instructions on https://ant.design/docs/react/contributing, and run npm start. I get the following error message: 

```
npm start

> antd@4.17.2 prestart /Users/aschorr/workspace/ant-design
> npm run version


> antd@4.17.2 version /Users/aschorr/workspace/ant-design
> node ./scripts/generate-version


> antd@4.17.2 start /Users/aschorr/workspace/ant-design
> antd-tools run clean && cross-env NODE_ENV=development concurrently "bisheng start -c ./site/bisheng.config.js"

antd-tools run clean
[0] /Users/aschorr/workspace/ant-design/site/bisheng.config.js:124
[0]         if (plugin?.options?.filename?.includes?.('.css')) {
[0]                    ^
[0]
[0] SyntaxError: Unexpected token .
[0]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at Module.require (/Users/aschorr/workspace/ant-design/node_modules/bisheng/lib/index.js:74:23)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at getBishengConfig (/Users/aschorr/workspace/ant-design/node_modules/bisheng/lib/utils/get-bisheng-config.js:44:54)
[0]     at Object.start (/Users/aschorr/workspace/ant-design/node_modules/bisheng/lib/index.js:106:23)
[0]     at Object.<anonymous> (/Users/aschorr/workspace/ant-design/node_modules/bisheng/bin/bisheng-start:10:9)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0] bisheng start -c ./site/bisheng.config.js exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd@4.17.2 start: `antd-tools run clean && cross-env NODE_ENV=development concurrently "bisheng start -c ./site/bisheng.config.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@4.17.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aschorr/.npm/_logs/2021-12-03T23_38_36_108Z-debug.log
```

My node version is 16, but I additionally tried with node 10 and get the same error, so I think it might not be related. I am not going to file a bug for that, but can if you wish. Also, you should specificy a node version on that contributing page so others may not run into the same issue.

**Comment by afc163** [comment]
Use `type: 'checkbox' as const`.

**Comment by kaocong** [comment]
![image](https://user-images.githubusercontent.com/50489475/145205331-e1880a10-f33a-4147-9fa5-1b533b83fe00.png)
