### ISSUE TITLE
在 create-react-app 中 主题配置 安装craco和craco-less 一直报错

### ISSUE THREAD

**Issue by Shasha-beep** [ant-design/ant-design#33356]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/JSmagician/antd-test](https://gitee.com/JSmagician/antd-test)

### Steps to reproduce
yarn start

### What is expected?
运行成功

### What is actually happening?
Error: Can't find file-loader in the development webpack config!

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the DocSpring/craco-less repo:

   * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue webpack file-loader

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue webpack file-loader
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue webpack file-loader

    at throwUnexpectedConfigError (C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\plugin-utils.js:29:11)
    at throwError (C:\Users\lhcq\Desktop\test\node_modules\craco-less\lib\craco-less.js:14:5)
    at Object.overrideWebpackConfig (C:\Users\lhcq\Desktop\test\node_modules\craco-less\lib\craco-less.js:165:5)
    at overrideWebpack (C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\features\plugins.js:42:40)
    at C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\features\plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\features\plugins.js:63:29)
    at mergeWebpackConfig (C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\features\webpack\merge-webpack-config.js:110:30)
    at overrideWebpackDev (C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\lib\features\webpack\override.js:11:36)
    at C:\Users\lhcq\Desktop\test\node_modules\@craco\craco\scripts\start.js:27:5

| Environment | Info |
|---|---|
| antd | 4.17.3 |
| React | 17.0.2 |
| System | window |
| Browser | edge |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/33072#issuecomment-981390047

**Comment by Shasha-beep** [comment]
sorry，我在两台电脑上分别用npm和yarn进行了安装，都提示同样的错误
"react-scripts": "5.0.0"
"@craco/craco": "^6.4.3"
 "craco-less": "^1.20.0"

**Comment by afc163** [comment]
建议反馈给 @craco/craco

**Comment by chentle** [comment]
have u already found how to solve that problem?
![image](https://user-images.githubusercontent.com/71593936/147043259-50c378a7-3944-4ce1-8974-645e3a2c0ff5.png)
