### ISSUE TITLE
ant-design源码在win10 nodejs环境下 npm install 报错

### ISSUE THREAD

**Issue by ShirlyKong** [ant-design/ant-design#3379]
#### 发生问题的环境是：

- antd 版本:2.0.1
- 操作系统及其版本: Win10 家庭中文版  1607
- 浏览器及其版本: 

#### 您做了什么？
git clone源码，使用nodejs 命令行  npm install

#### 您期待的结果是：
正常安装依赖环境，进行编译

#### 实际上的结果是：
报错如下：E:\ant-design\node_modules\.0.3.7@orchestrator\index.js:153
                        throw err;
                        ^
 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c antd-tools run guard" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\LENOVO\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.1.1

**Comment by afc163** [comment]
https://github.com/cnpm/npminstall 已经 2.4.1 了。

请升级到最新版本的 tnpm 。
