### ISSUE TITLE
PageHeader onBack 报错

### ISSUE THREAD

**Issue by youwch** [ant-design/ant-design#34070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/page-header-cn/](https://ant.design/components/page-header-cn/)

### Steps to reproduce
1.点击title，返回上一页
2.报错：Uncaught TypeError: this.elements[0][s].split is not a function
    at init.hasClass (prevel.js:1:5460)
    at HTMLDocument.externalClick (eval at success (kernel.js:1:2555), <anonymous>:1:3116)
    at HTMLDocument.i (prevel.js:1:7253)
    at HTMLDocument.s.evt.s.handleEvt (prevel.js:1:7575)

### What is expected?
正常跳转不报错

### What is actually happening?
报错：Uncaught TypeError: this.elements[0][s].split is not a function
    at init.hasClass (prevel.js:1:5460)
    at HTMLDocument.externalClick (eval at success (kernel.js:1:2555), <anonymous>:1:3116)
    at HTMLDocument.i (prevel.js:1:7253)
    at HTMLDocument.s.evt.s.handleEvt (prevel.js:1:7575)

| Environment | Info |
|---|---|
| antd | 4.18.7 |
| React | react  |
| System | win10 |
| Browser | chrome |

**Comment by youwch** [comment]
在线测试地址，最小化代码
https://4j9h9m.csb.app/

**Comment by yoyo837** [comment]
没看见啥问题

**Comment by youwch** [comment]
@yoyo837 我把antd的版本换为了4.18.5, 在线复现了bug, 不知道是不是版本的问题？麻烦再看一下

**Comment by yoyo837** [comment]
看不见 你复现不要给里面的运行 链接，给外面的链接

**Comment by youwch** [comment]
@yoyo837 这个链接可以吗, 麻烦看一下 https://4j9h9m.csb.app/

**Comment by yoyo837** [comment]
看不见问题。

**Comment by youwch** [comment]
@yoyo837 不好意思, 我再充分测试复现一下, 再联系
