### ISSUE TITLE
使用 pnpm 构建失败

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/ant-design#34421]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/dropdown/issues/200](https://github.com/react-component/dropdown/issues/200)

### Steps to reproduce
1. 创建 vite react 项目
2. 安装 pnpm 包管理器
3. 安装 antd 依赖
4. 启动项目

### What is expected?
正常启动

### What is actually happening?
```
Pre-bundling dependencies:
  react
  react-dom
  antd
  antd/es/locale/zh_CN
  react-router-dom
  (...and 29 more)
(this will be run only when your dependencies or config have changed)
✘ [ERROR] Could not resolve "rc-util/es/ref"

    node_modules/.pnpm/rc-dropdown@3.3.2_react-dom@17.0.2 react@17.0.2/node_modules/rc-dropdown/es/Dropdown.js:11:27:
      11 │ import { supportRef } from "rc-util/es/ref";
         ╵                            ~~~~~~~~~~~~~~~~

  You can mark the path "rc-util/es/ref" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "rc-util/es/KeyCode"

    node_modules/.pnpm/rc-dropdown@3.3.2_react-dom@17.0.2 react@17.0.2/node_modules/rc-dropdown/es/hooks/useAccessibility.js:2:20:
      2 │ import KeyCode from "rc-util/es/KeyCode";
        ╵                     ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "rc-util/es/KeyCode" as external to exclude it from the bundle, which will
  remove this error.

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/.pnpm/rc-dropdown@3.3.2_react-dom@17.0.2 react@17.0.2/node_modules/rc-dropdown/es/Dropdown.js:11:27: ERROR: Could not resolve "rc-util/es/ref"
node_modules/.pnpm/rc-dropdown@3.3.2_react-dom@17.0.2 react@17.0.2/node_modules/rc-dropdown/es/hooks/useAccessibility.js:2:20: ERROR: Could not resolve "rc-util/es/KeyCode"
    at failureErrorWithLog (C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:1036:63)
    at buildResponseToResult (C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:1249:7)
    at C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:1358:14
    at C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:668:9
    at handleIncomingPacket (C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:765:9)
    at Socket.readFromStdout (C:\Users\liuwei\Desktop\gitlab\prominent-pc\node_modules\.pnpm\esbuild@0.14.25\node_modules\esbuild\lib\main.js:635:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
 ELIFECYCLE  Command failed with exit code 1.
```
| Environment | Info |
|---|---|
| antd | 4.19.1 |
| React | 17.0.2 |
| System | Windows10 |
| Browser | Chrome 99.0.4844.51 |

---
麻烦帮忙发布版本：https://github.com/react-component/dropdown/commit/99103666fe5826df758b30cf1ea831c25b1f7c9d

**Comment by afc163** [comment]
https://github.com/react-component/dropdown/releases/tag/v3.3.3
