### ISSUE TITLE
antd doesn't work with VITE and YARN berry

### ISSUE THREAD

**Issue by JaLe29** [ant-design/ant-design#34542]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/JaLe29/antd-yarn](https://github.com/JaLe29/antd-yarn)

### Steps to reproduce
Just try to start develop server using:
`yarn workspace my-workspace dev`

### What is expected?
It should start VITE develop server

### What is actually happening?
Currently I am facing to problem with yarn berry workspaces and vite. After start it is failing with following error. It is working correctly without yarn workspaces. 

```
yarn workspace my-workspace dev
Pre-bundling dependencies:
  react-dom
  antd
  react/jsx-dev-runtime
(this will be run only when your dependencies or config have changed)
X [ERROR] Could not resolve "rc-util/es/ref"

    ../../.yarn/__virtual__/rc-dropdown-virtual-c88e594611/0/cache/rc-dropdown-npm-3.3.2-bc5d0d9b35-a0d0da20d5.zip/node_modules/rc-dropdown/es/Dropdown.js:11:27:
      11 │ import { supportRef } from "rc-util/es/ref";
         ╵                            ~~~~~~~~~~~~~~~~

  You can mark the path "rc-util/es/ref" as external to exclude it from the bundle, which will
  remove this error.

X [ERROR] Could not resolve "rc-util/es/KeyCode"

    ../../.yarn/__virtual__/rc-dropdown-virtual-c88e594611/0/cache/rc-dropdown-npm-3.3.2-bc5d0d9b35-a0d0da20d5.zip/node_modules/rc-dropdown/es/hooks/useAccessibility.js:2:20:
      2 │ import KeyCode from "rc-util/es/KeyCode";
        ╵                     ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "rc-util/es/KeyCode" as external to exclude it from the bundle, which will
  remove this error.

error when starting dev server:
Error: Build failed with 2 errors:
../../.yarn/__virtual__/rc-dropdown-virtual-c88e594611/0/cache/rc-dropdown-npm-3.3.2-bc5d0d9b35-a0d0da20d5.zip/node_modules/rc-dropdown/es/Dropdown.js:11:27: ERROR: Could not resolve "rc-util/es/ref"     
../../.yarn/__virtual__/rc-dropdown-virtual-c88e594611/0/cache/rc-dropdown-npm-3.3.2-bc5d0d9b35-a0d0da20d5.zip/node_modules/rc-dropdown/es/hooks/useAccessibility.js:2:20: ERROR: Could not resolve "rc-util/es/KeyCode"
    at failureErrorWithLog (C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:1036:63)
    at buildResponseToResult (C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:1249:7)
    at C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:1358:14
    at C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:668:9
    at handleIncomingPacket (C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:765:9)
    at Socket.readFromStdout (C:\Users\user\Desktop\antd-yarn\.yarn\unplugged\esbuild-npm-0.14.26-ac86888f4d\node_modules\esbuild\lib\main.js:635:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
```

| Environment | Info |
|---|---|
| antd | 4.19.2 |
| React | 17 |
| System | windows / linux |
| Browser | - |

**Comment by yoyo837** [comment]
See #34421

**Comment by yoyo837** [comment]
Try remove `node_modules` and lock file (`yarn.lock` or `package-lock.json`) then reinstall.

**Comment by JaLe29** [comment]
You are right, there was a problem with my cache. Working correctly. Thank you.
