### ISSUE TITLE
Using jsx in OptGroup label prop throws a react warning in console

### ISSUE THREAD

**Issue by gurkohli** [ant-design/ant-design#36005]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dkbm92)

### Steps to reproduce

Use a jsx in OptGroup's label prop

### What is expected?

No warning is thrown in the console

### What is actually happening?

The following warning is thrown

```
Warning: Received `false` for a non-boolean attribute `title`.

If you want to write it to the DOM, pass a string instead: title="false" or title={value.toString()}.

If you used to conditionally omit it with title={condition && value}, pass title={condition ? value : undefined} instead.
    at div
    at Item (https://dkbm92.csb.app/node_modules/rc-virtual-list/es/Item.js:10:23)
    at div
    at DomWrapper (https://dkbm92.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://dkbm92.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:17:24)
    at ResizeObserver (https://dkbm92.csb.app/node_modules/rc-resize-observer/es/index.js:17:24)
    at div
    at eval (https://dkbm92.csb.app/node_modules/rc-virtual-list/es/Filler.js:46:21)
    at div
    at div
    at RawList (https://dkbm92.csb.app/node_modules/rc-virtual-list/es/List.js:162:32)
    at OptionList (https://dkbm92.csb.app/node_modules/rc-select/es/OptionList.js:42:48)
    at div
    at div
    at div
    at Align (https://dkbm92.csb.app/node_modules/rc-align/es/Align.js:31:23)
    at DomWrapper (https://dkbm92.csb.app/node_modules/rc-motion/es/DomWrapper.js:19:33)
    at eval (https://dkbm92.csb.app/node_modules/rc-motion/es/CSSMotion.js:39:32)
    at eval (https://dkbm92.csb.app/node_modules/rc-trigger/es/Popup/PopupInner.js:28:23)
    at div
    at eval (https://dkbm92.csb.app/node_modules/rc-trigger/es/Popup/index.js:26:22)
    at eval (https://dkbm92.csb.app/node_modules/rc-util/es/Portal.js:11:25)
    at Trigger (https://dkbm92.csb.app/node_modules/rc-trigger/es/index.js:60:35)
    at SelectTrigger (https://dkbm92.csb.app/node_modules/rc-select/es/SelectTrigger.js:58:25)
    at div
    at eval (https://dkbm92.csb.app/node_modules/rc-select/es/BaseSelect.js:55:18)
    at eval (https://dkbm92.csb.app/node_modules/rc-select/es/Select.js:55:18)
    at InternalSelect (https://dkbm92.csb.app/node_modules/antd/es/select/index.js:43:31)
```

| Environment | Info |
| --- | --- |
| antd | 4.21.0 |
| React | 18.1.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by kaiyoma** [comment]
We are running into this as well and it's causing test failures for us, since we scan the console for any warnings or errors during our test runs.

**Comment by gurkohli** [comment]
Can we trigger a publish of rc-select and further ant-design? We're still waiting for the fix to make its way to us.

**Comment by yoyo837** [comment]
https://github.com/react-component/select/releases/tag/v14.1.6

**Comment by gurkohli** [comment]
Thanks for your help! Could you also help with upgrade of rc-select in ant-design package and publishing that?

**Comment by yoyo837** [comment]
Just need remove `node_modules` and lock file(`package-lock.json` or `yarn.lock`), then reinstall it.

**Comment by gurkohli** [comment]
Okay great thanks! Just read the package.json and saw it’s using approximate versioning. Should be good to go. Thanks for your help!
