### ISSUE TITLE
defaultOpenKeys 失效

### ISSUE THREAD

**Issue by ueumd** [ant-design/ant-design#36728]
### Reproduction link

[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce

```
	<Menu
			theme="dark"
			mode="inline"
			defaultSelectedKeys={['/jsx/list']}
			defaultOpenKeys={'/jsx/list'}
			items={generateRouterList(routesList)}
			triggerSubMenuAction="click"
			onClick={clickMenu}
		></Menu>
```
defaultOpenKeys 传入数组默认不展开二级菜单，传入字符串正常展开，但切换一级路由时报错

Menu.js:308 Uncaught TypeError: mergedOpenKeys.filter is not a function
    at Object.current (Menu.js:308:38)
    at useMemoCallback.js:17:118
    at onInternalTitleClick2 (index.js:149:7)
    at Trigger2.fireEvents (index.js:667:11)
    at Trigger2._this2.onClick (index.js:154:15)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)

### What is expected?

页面刷新时二级菜单能正常展开

### What is actually happening?

-

| Environment | Info |
| --- | --- |
| antd | 4.22.0 |
| React | 18.2.0 |
| System | win11 |
| Browser | chrome 102.0.5005.63 |

**Comment by MadCcc** [comment]
string[]

**Comment by TopFiveGao** [comment]
这个issue有修复嘛？我也遇到这个bug了，反复看了官网代码半天，最终确认自己没有抄错官网代码。大佬解决了请告知一下啊，感谢！
