### ISSUE TITLE
三个条件并存的bug:（React 18) 且 (Menu mode="horizontal") 且 (浏览器在移动模式)

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#36746]
### What problem does this feature solve?

mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:27296 
        
       Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:27296:11)
    at scheduleUpdateOnFiber (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:25479:3)
    at dispatchSetState (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:17536:7)
    at onVisibleChange (mf-dep_vendors-node_modules_ant-design_icons_es_icons_EllipsisOutlined_js-node_modules_rc-menu_es_Su-9cb24f.8a319da2.async.js:550:7)
    at updateDisplayCount (mf-dep_vendors-node_modules_rc-overflow_es_index_js-node_modules_rc-util_es_KeyCode_js-node_modules_-e3ca8a.5779b0c8.async.js:279:73)
    at mf-dep_vendors-node_modules_rc-overflow_es_index_js-node_modules_rc-util_es_KeyCode_js-node_modules_-e3ca8a.5779b0c8.async.js:348:11
    at commitHookEffectListMount (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:23154:26)
    at commitLayoutEffectOnFiber (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:23272:17)
    at commitLayoutMountEffects_complete (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:24692:9)
    at commitLayoutEffects_begin (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:24678:7)
    at commitLayoutEffects (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:24616:3)
    at commitRootImpl (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:26827:5)
    at commitRoot (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:26686:5)
    at performSyncWorkOnRoot (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:26121:3)
    at flushSyncCallbacks (mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:12051:22)
    at mf-dep_vendors-node_modules_react-dom_index_js.1fe24e1a.async.js:25655:13

### What does the proposed API look like?

希望不要白屏，报错如下面

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/36559#issuecomment-1196238030

**Comment by kaoding** [comment]
> [#36559 (comment)](https://github.com/ant-design/ant-design/issues/36559#issuecomment-1196238030)

这个问题我碰到有一周以上时间了，经过测试发现只有同时碰到上面3个条件时才会出现，我以为是我自己的问题，原来早就有人碰到同样的问题，呵呵，坐等大老解决了。

**Comment by 1123612483** [comment]
我是2个条件
1. React18用React dom的`createRoot`
2. Menu的`mode="horizontal"`

**Comment by kaoding** [comment]
https://github.com/react-component/overflow/pull/24
