### ISSUE TITLE
React18下menu组件horizontal模式触发overflowed场景下的问题

### ISSUE THREAD

**Issue by yuningjiang123** [ant-design/ant-design#36776]
### Reproduction link

[https://stackblitz.com/edit/react18-rc-menu](https://stackblitz.com/edit/react18-rc-menu)

### Steps to reproduce

1. 让horizontal模式下的Menu触发overflow，即出现那三个点，让Navigation Three - Submenu这个菜单项被收敛在下拉菜单中
2. 鼠标hover那三个点，然后再移入Navigation Three - Submenu，打开第三层popup，鼠标移入第三层popup
3. 此时鼠标慢慢往上面移出第三层popup，会发现第二层已经消失了，可是第三层还在

### What is expected?

鼠标移出第三层popup时，所有popup都消失，对比react17下的效果
https://stackblitz.com/edit/react17-rc-menu

### What is actually happening?

鼠标已经移出第三层popup，第二层消失了，可是第三层没有消失

| Environment | Info |
| --- | --- |
| antd | 4.22.2 |
| React | 18.2.0 |
| System | Windows 10 专业版 20H2 |
| Browser | Chrome |

---
rc-menu也有这个问题，而且一定是要在触发overflowed的场景，单纯的三层嵌套Menu还不会出现这种现象，因此不知道是否跟rc-overflow也有关系。

**Comment by resiliated** [comment]
Hello, I can't read the issue, I don't know your language, but it's probably the same issue ? https://stackoverflow.com/questions/73138301/error-maximum-update-depth-exceeded-this-can-happen-when-a-component-repeatedl

I'm forced to use vertical menu to avoid this issue :)

**Comment by yuningjiang123** [comment]
> Hello, I can't read your issue (I don't understand your language), but it's probably the same as mine ? https://stackoverflow.com/questions/73138301/error-maximum-update-depth-exceeded-this-can-happen-when-a-component-repeatedl
> 
> I'm forced to use vertical menu to avoid this :)

Maybe not the same issue. I am pure at English but I can try to explain my issue in English ~

Steps to reproduce:
1. Narrow the wrapper width to make the horizontal Menu overflowed, 
2. Hover the overflow indicator, and then hover "Navigation Three - Submenu" to open the third level popup, which your mouse should also enter in
3. Then slowly move your mouse out of the third level popup. You can see the second level popup has vanished, while the third level popup still exists.

Here's a gif I recorded to show the behavior in React 18:
![React18](https://user-images.githubusercontent.com/45219486/182060468-d96fabab-ba4e-423a-8484-f02b1b2be6ff.gif)

In comparison with the behavior in React 17:
![React17](https://user-images.githubusercontent.com/45219486/182060630-e3f0ff78-3e01-4475-bfe4-8096b05601cb.gif)

**Comment by ajaygupta1988** [comment]
> Hello, I can't read your issue (I don't understand your language), but it's probably the same as mine ? https://stackoverflow.com/questions/73138301/error-maximum-update-depth-exceeded-this-can-happen-when-a-component-repeatedl
> 
> I'm forced to use vertical menu to avoid this :)

I am also facing the same problem

**Comment by tomsh99** [comment]
> Hello, I can't read your issue (I don't understand your language), but it's probably the same as mine ? https://stackoverflow.com/questions/73138301/error-maximum-update-depth-exceeded-this-can-happen-when-a-component-repeatedl
> 
> 
> 
> I'm forced to use vertical menu to avoid this :) 
> 
> 
> 
> 

Happens to me also😩 please fix it

**Comment by woutervanbakel** [comment]
Same here....

**Comment by tomsh99** [comment]
Antd 4.22.5 fixed that problem for me

**Comment by woutervanbakel** [comment]
Than I've a different issue. When using the horizontal menu in responsive mode (Currently Chrome and mobile browers only)
It crashes 

`The above error occurred in the <Overflow> component:

    at Overflow (webpack-internal:///./node_modules/rc-overflow/es/Overflow.js:40:32)
    at InheritableContextProvider (webpack-internal:///./node_modules/rc-menu/es/context/MenuContext.js:35:23)
    at eval (webpack-internal:///./node_modules/rc-menu/es/Menu.js:73:32)
    at eval (webpack-internal:///./node_modules/antd/es/menu/index.js:66:53)
    at Menu (webpack-internal:///./node_modules/antd/es/menu/index.js:185:90)
    at div
    at eval (webpack-internal:///./node_modules/antd/es/grid/col.js:49:62)
    at div
    at eval (webpack-internal:///./node_modules/antd/es/grid/row.js:45:34)
    at div
    at header
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:76:25)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:55:66)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:92:63)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:55:66)
    at Page (webpack-internal:///./lib/layout/Page.tsx:64:21)
    at PortalContext (webpack-internal:///./src/components/Context.tsx:23:20)
    at render
    at Portal (webpack-internal:///./src/pages/_app.tsx:22:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23632)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:71:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:592:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:703:27)`

**Comment by de24world** [comment]
I have same Issue with `Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.` 
           
Error in Tablet(Or Mobile)
` <Menu theme="dark" mode="horizontal" items={items} />
`

**Comment by MadCcc** [comment]
Could not reproduce in 4.24.8 and 5.3.0, closing.
Feel free to open new issue if find anything wrong.
