### ISSUE TITLE
Menu 菜单在移动设备上点击会报错

### ISSUE THREAD

**Issue by Kil1m** [ant-design/ant-design#36930]
### Reproduction link

[https://gitee.com/kil1m/my-blog-frontend.git或是直接访问kilim.cloud](https://gitee.com/kil1m/my-blog-frontend.git或是直接访问kilim.cloud)

### Steps to reproduce

1，在浏览器端切换到移动设备模式
2，点击顶部导航栏任意选项

### What is expected?

执行页面跳转或者其他Menu选项对应操作

### What is actually happening?

白屏，且报错如下：

The above error occurred in the <Overflow> component:

    at Overflow (http://localhost:3000/static/js/bundle.js:103454:32)
    at InheritableContextProvider (http://localhost:3000/static/js/bundle.js:100365:23)
    at http://localhost:3000/static/js/bundle.js:98961:32
    at http://localhost:3000/static/js/bundle.js:59099:53
    at Menu (http://localhost:3000/static/js/bundle.js:59208:90)
    at header
    at http://localhost:3000/static/js/bundle.js:58079:25
    at http://localhost:3000/static/js/bundle.js:58062:66
    at section
    at http://localhost:3000/static/js/bundle.js:58095:63
    at http://localhost:3000/static/js/bundle.js:58062:66
    at Back_Header (http://localhost:3000/static/js/bundle.js:4160:77)
    at RenderRouter (http://localhost:3000/static/js/bundle.js:5010:66)
    at Router (http://localhost:3000/static/js/bundle.js:151732:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:150541:5)
    at App

react-dom.development.js:27292 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:1)
    at dispatchSetState (react-dom.development.js:17527:1)
    at onVisibleChange (Menu.js:390:1)
    at updateDisplayCount (Overflow.js:151:1)
    at Overflow.js:220:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23268:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)

| Environment | Info |
| --- | --- |
| antd | 4.21.3 |
| React | 18.2.0 |
| System | win10 |
| Browser | Chrome 版本 103.0.5060.134（正式版本） （64 位） |

---
导航栏在Home.tsx,以及Layout.tsx中实现，在二者中，我并未使用setState函数
联系方式：kilimqqmail@qq.com

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/overflow/pull/24
