### ISSUE TITLE
`npm test` fails for me

### ISSUE THREAD

**Issue by waywardmonkeys** [ant-design/ant-design#3875]
I'm having trouble running `npm test` or `npm start` and the like.

https://github.com/ant-design/ant-design/wiki/Development doesn't seem to say that I need to do anything that I haven't done.

Any ideas?

```
batavia:ant-design bruce (more-typo-fixes) $ npm test

> antd@2.4.2 test /Users/bruce/Development/workbench/ant-design
> npm run lint && npm run dist && npm run jest


> antd@2.4.2 lint /Users/bruce/Development/workbench/ant-design
> npm run tslint && npm run eslint && npm run demolint && npm run lesshint


> antd@2.4.2 tslint /Users/bruce/Development/workbench/ant-design
> antd-tools run ts-lint && npm run compile && rm -rf lib

antd-tools run ts-lint

> antd@2.4.2 compile /Users/bruce/Development/workbench/ant-design
> antd-tools run compile && node ./tests/dekko/lib.test.js

antd-tools run compile

events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/bruce/Development/workbench/ant-design/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! antd@2.4.2 compile: `antd-tools run compile && node ./tests/dekko/lib.test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@2.4.2 compile script 'antd-tools run compile && node ./tests/dekko/lib.test.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     antd-tools run compile && node ./tests/dekko/lib.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bruce/Development/workbench/ant-design/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "tslint"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! antd@2.4.2 tslint: `antd-tools run ts-lint && npm run compile && rm -rf lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@2.4.2 tslint script 'antd-tools run ts-lint && npm run compile && rm -rf lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     antd-tools run ts-lint && npm run compile && rm -rf lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bruce/Development/workbench/ant-design/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! antd@2.4.2 lint: `npm run tslint && npm run eslint && npm run demolint && npm run lesshint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@2.4.2 lint script 'npm run tslint && npm run eslint && npm run demolint && npm run lesshint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tslint && npm run eslint && npm run demolint && npm run lesshint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bruce/Development/workbench/ant-design/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by afc163** [comment]
Try node@6 ?

**Comment by yesmeck** [comment]
I'm using node@7.1.0 too, it runs ok here.

![cw5ubblukaammlm](https://cloud.githubusercontent.com/assets/465125/20354561/938181a8-ac59-11e6-9d2d-25e19baa6d51.jpg)

**Comment by waywardmonkeys** [comment]
Thanks, @yesmeck. Clearning `node_modules` and re-doing the `npm install` fixed things.
