### ISSUE TITLE
Error on input in basic form on Nextjs

### ISSUE THREAD

**Issue by rsereir** [ant-design/ant-design#39413]
### Reproduction link

[https://www.antd-refacto-4rwj72i-sowdl7iah3332.fr-3.platformsh.site/login](https://www.antd-refacto-4rwj72i-sowdl7iah3332.fr-3.platformsh.site/login)

### Steps to reproduce

access to page with simple ant design form with input ( in production build )

### What is expected?

i want to render my form in production build

### What is actually happening?

it's working in local ( dev ) but in build prod i have a 500 error in ant design library 

| Environment | Info |
| --- | --- |
| antd | 5.0.5 |
| React | 17 |
| System | macos |
| Browser | chrome |

```php
<Form
                        onFinish={handleSubmit}
                    >
                        <Input.Text
                            name="email"
                            label={t('form.input.email.label')}
                            rules={[
                                {
                                    required: true,
                                    message: t('form.rules.required')
                                }
                            ]}
                        />
                        <Input.Password
                            name="plainPassword"
                            label={t('form.input.password.label')}
                            rules={[
                                {
                                    required: true,
                                    message: t('form.rules.required')
                                }
                            ]}
                        />
                        <Button type="submit" loading={loading}>{t('login.submit')}</Button>
                    </Form>
```

![Screenshot 2022-12-08 at 19 59 50](https://user-images.githubusercontent.com/43849341/206544179-b2b708cb-33d4-490b-889d-fdff3eff2963.png)

---
TypeError: Cannot read properties of undefined (reading 'vertical')
    at Object.children (/app/node_modules/antd/lib/form/FormItemLabel.js:60:26)
    at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:125)
    at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at Object.renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/app/node_modules/next/dist/server/render.js:804:45)
    at Object.defaultGetInitialProps (/app/node_modules/next/dist/server/render.js:391:51)
    at Function.getInitialProps (/app/.next/server/chunks/6859.js:202:20)
    at Object.loadGetInitialProps (/app/node_modules/next/dist/shared/lib/utils.js:65:29)
    at documentInitialProps (/app/node_modules/next/dist/server/render.js:817:48)
    at renderDocument (/app/node_modules/next/dist/server/render.js:841:55)

**Comment by rsereir** [comment]
Downgrade nextjs to 12.0 instead of 12.1 works for me
