### ISSUE TITLE
ant design 站点国内加载太慢

### ISSUE THREAD

**Issue by MrRENGE** [ant-design/ant-design#39438]
### Reproduction link

[https://4x.ant.design/components/slider-cn/](https://4x.ant.design/components/slider-cn/)

### Steps to reproduce

组件文档之间切换，控制台抛错，并且加载巨慢。
//
Uncaught (in promise) ChunkLoadError: Loading chunk 160 failed.
(error: https://4x.ant.design/components/slider/demo.8f5816.js)
    at i.e (index-448afd76.js:1:16449)
    at index-448afd76.js:968:26448
    at new Promise (<anonymous>)
    at demo (index-448afd76.js:968:26422)
    at index-448afd76.js:109:1483
    at I (index-448afd76.js:107:18707)
    at Generator.<anonymous> (index-448afd76.js:107:20100)
    at Generator.next (index-448afd76.js:107:19075)
    at S (index-448afd76.js:109:687)
    at F (index-448afd76.js:109:884)
//

### What is expected?

看文档能够流畅阅览

### What is actually happening?

卡死，加载失败，页面切换失败

| Environment | Info |
| --- | --- |
| antd | 4.24.5 |
| React | react |
| System | macos |
| Browser | chrome 100  |

**Comment by MadCcc** [comment]
国内推荐访问镜像：https://4x-ant-design.antgroup.com
