### ISSUE TITLE
TypeError: (0 , _moment2.default) is not a function

### ISSUE THREAD

**Issue by pastelsky** [ant-design/ant-design#3947]
I'm trying to use antd as a component library with my existing build system (webpack 2). Can I use components from this library without importing the entire build system?
I did 
```
npm install antd
```
and in my page, added
```jsx
import { DatePicker } from 'antd'

export function Page(){
  return <DatePicker/>
}
```

#### Error
```
Uncaught TypeError: (0 , _moment2.default) is not a function
    at Function.getDefaultProps (?d41d*:78)
    at Object.createClass (ReactClass.js:675)
    at Object../node_modules/rc-time-picker/lib/Panel.js (?d41d*:45)
    at __webpack_require__ (bootstrap d2f4533…:689)
    at fn (bootstrap d2f4533…:110)
    at Object../node_modules/antd/lib/date-picker/wrapPicker.js (wrapPicker.js:21)
    at __webpack_require__ (bootstrap d2f4533…:689)
    at fn (bootstrap d2f4533…:110)
    at Object../node_modules/antd/lib/date-picker/index.js (index.js:23)
    at __webpack_require__ (bootstrap d2f4533…:689)
```

## Environment
webpack 2
Antd 2.4.3
Node 7
OSX 10.10

**Comment by afc163** [comment]
Try this: https://github.com/webpack/webpack/issues/1694#issuecomment-164481066

**Comment by afc163** [comment]
Give us a reproducible repo?

**Comment by AlbertZheng** [comment]
@pastelsky  Are you using babel 5.x? If yes, it might be babel 5.x issue concerning ES6 exports and backward compatibility with CommonJS. Upgrade to babel 6.x and try again.

**Comment by MateusDantas** [comment]
I'm having this exact same issue. I don't think it's related to babel, but I do believe it's a problem with moment lib. It seems to me that moment is not webpack friendly, as I already had some issues with it in the past and it keeps occurring. 

Probably related: 
- https://github.com/webpack/webpack/issues/3128
- https://github.com/moment/momentjs.com/issues/269

**Comment by anton6** [comment]
+1

**Comment by anton6** [comment]
In my case, I managed to to get it working by installing moment with specific version: "moment": "2.15.2". Later version of moment seems to cause this problem for me.

@MateusDantas this is exactly why we recently switched to **date-fns**

**Comment by anton6** [comment]
Ok now when I try to change locale like this:
`import enUS from 'antd/lib/locale-provider/en_US';`
I get the following error: 

> Dynamic page loading failed TypeError: _moment2.default.locale is not a function
    at eval (eval at <anonymous> (http://localhost:3000/7.chunk.js:3201:1), <anonymous>:29:21)
    at Object.<anonymous> (http://localhost:3000/7.chunk.js:3201:1)
    at __webpack_require__ (http://localhost:3000/main.js:620:30)
    at fn (http://localhost:3000/main.js:103:20)
    at Object.eval (eval at <anonymous> (http://localhost:3000/7.chunk.js:2621:1), <anonymous>:22:89)
    at eval (eval at <anonymous> (http://localhost:3000/7.chunk.js:2621:1), <anonymous>:246:30)
    at Object.<anonymous> (http://localhost:3000/7.chunk.js:2621:1)
    at __webpack_require__ (http://localhost:3000/main.js:620:30)
    at fn (http://localhost:3000/main.js:103:20)
    at eval (eval at <anonymous> (http://localhost:3000/7.chunk.js:6:1), <anonymous>:1:69)

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/3363#issuecomment-256300626

>  webpack2 don't add `__es6modules` flag to the es6 modules currently (see webpack/webpack#3168) which leads to babel will treat that es6 module as CommonJS module.

**Comment by pastelsky** [comment]
The only way i could work around this was by adding an alias
```
alias: {
   moment: 'moment/moment.js'
}
```
But by adding this the bundle size is bloated since it includes many other language locales.

**Comment by tangoabcdelta** [comment]
I was trying to build an app with[ react boilerplate ](http://www.reactboilerplate.com/). Importing any component from `antd` results in this error.

**Comment by benjycui** [comment]
@tangoabcdelta ref: https://ant.design/docs/react/use-with-create-react-app

**Comment by jsmeander** [comment]
update your webpack version to "v2.2.0-rc.2" in package.json, work for me.

**Comment by KhushbooTaneja** [comment]
@pastelsky Where you added this alias ?
alias: {
   moment: 'moment/moment.js'
}
And how does it solved your problem ?
I am also facing the same issue

**Comment by deveedutta** [comment]
@KhushbooTaneja This alias has to be added in the `webpack` configuration. [details](https://webpack.github.io/docs/configuration.html#resolve-alias).

```js
  resolve: {
    modules: ['app', 'node_modules'],
    extensions: [
      '',
      '.js',
      '.jsx',
      '.react.js',
    ],
    mainFields: [
      'jsnext:main',
      'main',
    ],
    alias: {
      // required for moment to work properly
      moment: 'moment/moment.js',
    }
  },
```

**Comment by deveedutta** [comment]
Additionally, this issue can also be addressed ([according to the major contributor of ant-design](https://github.com/webpack/webpack/issues/3128#issuecomment-269155166)) 
by using:

```js
 module: {
      noParse: [/moment.js/],
}
```

**Comment by 18601673727** [comment]
tried every way but none of them work yet 😞

**Comment by afc163** [comment]
Could any of you guys give us a reproducible repo for this problem?

**Comment by 18601673727** [comment]
Dear @afc163, could you please kindly init a project base on https://github.com/mxstbr/react-boilerplate(3.3.3), and do the very basically integration with your lib(2.6.0) and you will see.

**Comment by 18601673727** [comment]
```
alias: { moment: 'moment/moment.js' },
```
➕
```
noParse: [/moment.js/],
```
➕
```
npm cache clean && npm uninstall webpack && npm install -D webpack@^2.2.0-rc.3
```
➕
updates some old dependencies, worked somehow...

maybe it's better to replace `moment` with `date-fns`

**Comment by deveedutta** [comment]
@afc163 
1. Download [react-boilerplate](https://github.com/mxstbr/react-boilerplate)
2. Built & Run the app
3. Download ant.design
4. Import a date picker from ant.design into any of the pages

You should see the error there.

**Comment by esmeander** [comment]
@deveedutta this is cause of a webpack beta version error, you could see the webpack version in package.json of react-boilerplate, just update it to the newest.

**Comment by deveedutta** [comment]
tagging @yiminghe

**Comment by afc163** [comment]
Found a workaround for using antd in react-boilerplate: https://github.com/ant-design/ant-design/issues/4491#issuecomment-270887624

**Comment by 18601673727** [comment]
@afc163, Please don't mind that I say `RangePicker` is still not working...
![image](https://cloud.githubusercontent.com/assets/3302620/21755787/caba94ce-d653-11e6-9879-373f0aa3ec1c.png)

**Comment by afc163** [comment]
@18601673727 

```diff
- import { RangePicker } from 'antd';
+ import { DatePicker } from 'antd';
+ const RangePicker = DatePicker.RangePicker;
```

**Comment by xxryan1234** [comment]
when running `npm run build` I encounter this warning

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  0.947a705a7423c641effb.chunk.js (485 kB)
```

what can I do in my webpack production config so I can avoid this error?

**Comment by Meetri-Infotech** [comment]
We are using AntD datepicker in our component. While rendering component for UT, it's giving following error

 TypeError: (0 , _moment.default) is not a function

Following is stacktrace 
at Object.getNow (../node_modules/rc-picker/lib/generate/moment.js:17:32)
      at getViewDate (../node_modules/rc-picker/lib/hooks/useRangeViewDates.js:107:155)
      at renderPanels (../node_modules/rc-picker/lib/RangePicker.js:839:22)
      at InnerRangePicker (../node_modules/rc-picker/lib/RangePicker.js:896:7)
      at renderWithHooks (../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (../node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (../node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (../node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (../node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (../node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (../node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (../node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (../node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at ../node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (../node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (../node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (../node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at ../node_modules/@testing-library/react/dist/pure.js:101:25
      at batchedUpdates$1 (../node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (../node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (../node_modules/@testing-library/react/dist/pure.js:97:26)

We are using following:
"antd": "^4.18.2"
"jest": "^27.4.7",
"@testing-library/jest-dom": "^5.16.1",
"@testing-library/react": "^12.1.5",
"typescript": "^4.5.4",
 "webpack": "^5.74.0",
"moment": "^2.29.4",

following is tsconfig
{
  "compilerOptions": {
    "lib": [
      "ES6",
      "DOM"
    ],
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": false,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "./src",
    "paths": {
      "src/*": [
        "*"
      ]
    }
  },
  "include": [
    "src"
  ]
}

Jest config
module.exports = {
  testEnvironment: 'jsdom',
  // The root of your source code, typically /src
  // `<rootDir>` is a token Jest substitutes
  roots: ['<rootDir>/src'],

  // Jest transformations -- this adds support for TypeScript
  // using ts-jest
  // transform: {
  //   "^.+\\.tsx?$": "ts-jest",
  //   "^.+\\.svg$": "jest-svg-transformer",
  //   "^.+\\.css$": "jest-transform-css",
  // },

  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/fileTransformer.js',
    '^.+\\.(css|scss)$': 'jest-transform-css',
  },

  // Runs special logic, such as cleaning up components
  // when using React Testing Library and adds special
  // extended assertions to Jest
  setupFilesAfterEnv: [
    '<rootDir>/testSetupFile.ts',
    '@testing-library/jest-dom/extend-expect',
  ],

  // Test spec file resolution pattern
  // Matches parent folder `__tests__` and filename
  // should contain `test` or `spec`.
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',

  // Module file extensions for importing
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleDirectories: ['node_modules', '.'],
};

It's causing because of Antd DatePicker. If I remove it, component is rendering correctly in test. Please  let me know how can I resolve it.
