### ISSUE TITLE
RangePicker initials values in Form crashed in v5

### ISSUE THREAD

**Issue by pcarpet** [ant-design/ant-design#39876]
### Reproduction link

[https://codepen.io/pcarpet/pen/eYjJXdZ?editors=0011](https://codepen.io/pcarpet/pen/eYjJXdZ?editors=0011)

### Steps to reproduce

1. Create a RangePicker in a form
2. Initialize values with moment function

### What is expected?

The dates are displayed in dateRange component

### What is actually happening?

Chrome crashed with following stack :

"Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.%s" "
    at InnerRangePicker (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:133827:29)
    at RangePicker (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:134784:102)
    at LocaleReceiver (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:24455:5)
    at https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:10672:20
    at https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:18137:5
    at div
    at div
    at div
    at https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:19559:55
    at FormItemInput (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:18395:5)
    at div
    at https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:19768:18
    at div
    at ItemHolder (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:17977:7)
    at Field (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:119363:102)
    at WrapperField (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:119824:20)
    at InternalFormItem (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:18158:5)
    at form
    at Form (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:119936:19)
    at SizeContextProvider (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:10087:5)
    at DisabledContextProvider (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:10059:5)
    at InternalForm (https://unpkg.com/antd@5.1.1/dist/antd-with-locales.js:17824:71)
    at App"

| Environment | Info |
| --- | --- |
| antd | 5.1.1 |
| React | 18.2.0 |
| System | Windows 10 |
| Browser | Google Chrome 108.0.5359.125 |

---
Works great on 4.17.3

**Comment by anacvignola** [comment]
I had the same problem, just change the moment for the lib [dayjs](https://day.js.org/) which is practically the same as it solves.

**Comment by jrr997** [comment]
https://ant.design/docs/react/use-custom-date-library#datepicker

**Comment by zombieJ** [comment]
Ref @anacvignola 's advance. v5 use dayjs instead of moment.

ref:
https://momentjs.com/docs/#/-project-status/

**Comment by ness001** [comment]
The problem still exists
