### ISSUE TITLE
npx -p @ant-design/codemod-v5 antd5-codemod client 报错，无法自动升级

### ISSUE THREAD

**Issue by shclu** [ant-design/ant-design#39939]
### Reproduction link

[https://xxx/xxx.com](https://xxx/xxx.com)

### Steps to reproduce

react@18.2.0 antd@4.24.7，控制台执行npx -p @ant-design/codemod-v5 antd5-codemod client

### What is expected?

项目自动升级至v5

### What is actually happening?

npx: 240 安装成功，用时 452.573 秒
Transform v5-props-changed-migration
Processing 788 files...
Spawning 3 workers...
Sending 50 files to free worker...
Sending 50 files to free worker...
Sending 50 files to free worker...
/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/transforms/v5-props-changed-migration.js:203
            if (nodePath.value?.value?.type === 'JSXExpressionContainer') {
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at setup (/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/node_modules/jscodeshift/src/Worker.js:91:18)
    at Object.<anonymous> (/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/no/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/transforms/v5-props-changed-migration.js:203
            if (nodePath.value?.value?.type === 'JSXExpressionContainer') {
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at setup (/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/node_modules/jscodeshift/src/Worker.js:91:18)
    at Object.<anonymous> (/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/node_modules/jscodeshift/src/Worker.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
de_modules/jscodeshift/src/Worker.js:45:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
/Users/beike/.npm/_npx/21543/lib/node_modules/@ant-design/codemod-v5/transforms/v5-props-changed-migration.js:203
            if (nodePath.value?.value?.type === 'JSXExpressionContainer') {

| Environment | Info |
| --- | --- |
| antd | 4.24.7 |
| React | 18.2.0 |
| System | macOS Big Sur 版本11.6 |
| Browser | 未涉及 |

**Comment by afc163** [comment]
本地 node 版本太低了？
