### ISSUE TITLE
@ant-design/pro-components : Cannot use import statement outside a module

### ISSUE THREAD

**Issue by UnkAtreus** [ant-design/ant-design#40312]
### Reproduction link

[https://github.com/UnkAtreus/d-law-fe](https://github.com/UnkAtreus/d-law-fe)

### Steps to reproduce

you can clone repo and pnpm dev 

### What is expected?

Display components without errors

### What is actually happening?

Cannot use any component in ant-design/pro-components in my project because when I try to import it, I'm getting index.js?5f7a:602 Uncaught SyntaxError: Cannot use import statement outside a module
    at C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\antd (5.1.2_biqbaboplfbrettd7655fr4n2y\node_modules\antd\es\skeleton\style\index.js:1)
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\@ant-design pro-skeleton@2.0.7_xkdntvt3sphixchsirkbxe2wm4\node_modules\@ant-design\pro-skeleton\lib\index.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\@ant-design pro-descriptions@2.0.44_tpeiamvowddlrnuktioiuoybui\node_modules\@ant-design\pro-descriptions\lib\index.js:18:43)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\@ant-design pro-components@2.3.52_tpeiamvowddlrnuktioiuoybui\node_modules\@ant-design\pro-components\lib\index.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at @ant-design/pro-components (file://C:\Users\nom_n\work\d-law-fe\.next\server\pages\index.js:112:18)
    at __webpack_require__ (file://C:\Users\nom_n\work\d-law-fe\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index.tsx:8:84)
    at __webpack_require__.a (file://C:\Users\nom_n\work\d-law-fe\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./src/pages/index.tsx:1:21)
    at ./src/pages/index.tsx (file://C:\Users\nom_n\work\d-law-fe\.next\server\pages\index.js:72:1)
    at __webpack_require__ (file://C:\Users\nom_n\work\d-law-fe\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (file://C:\Users\nom_n\work\d-law-fe\.next\server\pages\index.js:192:39)
    at <unknown> (file://C:\Users\nom_n\work\d-law-fe\.next\server\pages\index.js:193:28)
    at Object.<anonymous> (file://C:\Users\nom_n\work\d-law-fe\.next\server\pages\index.js:196:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\next@13.1.1_pjwopsidmaokadturxaafygjp4\node_modules\next\dist\server\require.js:88:12)
    at <unknown> (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\next@13.1.1_pjwopsidmaokadturxaafygjp4\node_modules\next\dist\server\load-components.js:37:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.loadComponents (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\next@13.1.1_pjwopsidmaokadturxaafygjp4\node_modules\next\dist\server\load-components.js:37:26)
    at async DevServer.findPageComponents (file://C:\Users\nom_n\work\d-law-fe\node_modules\.pnpm\next@13.1.1_pjwopsidmaokadturxaafygjp4\node_modules\next\dist\server\next-server.js:561:36)

| Environment | Info |
| --- | --- |
| antd | 5.1.5 |
| React | react:18.2.0 ,@ant-design/pro-components:2.3.52 |
| System | Window and Mac os |
| Browser | Google Chrome browser |

**Comment by luo3house** [comment]
It is the issue of `@ant-design/pro-components@2.3.52`

See: https://github.com/ant-design/pro-components/issues/6525
