### ISSUE TITLE
Webpack: How to extract LESS files into a Single CSS file

### ISSUE THREAD

**Issue by enzolutions** [ant-design/ant-design#4103]
Hi folks

I am trying to create an application with Antd; all works well, but the size of SPA is too much big.

For that reason, I am trying to extract the Less files to create one single CSS files to include via HTML to enable caching using webpack, but I am getting the following error

```
ERROR in ./~/antd/lib/style/index.less
Module parse failed: /Users/enzo/www/MagicGen/node_modules/antd/lib/style/index.less Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/enzo/www/MagicGen/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/enzo/www/MagicGen/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/enzo/www/MagicGen/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/enzo/www/MagicGen/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/enzo/www/MagicGen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/enzo/www/MagicGen/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/antd/lib/row/style/index.js 3:0-33
```

This my webpack.config.js

```
var webpack = require("webpack");
var path = require('path');
var glob_entries = require('webpack-glob-entries');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var OmitTildeWebpackPlugin = require('omit-tilde-webpack-plugin');

var MODULE_BUILD_DIR = path.resolve(__dirname, 'web/assets/build');
var MODULE_BUILD_CSS_DIR = path.resolve(__dirname, 'web/assets/css');
var MODULE_APP_DIR = path.resolve(__dirname, 'client/');

  var plugins = [];

  plugins.push(
    new ExtractTextPlugin('styles/magicgen.css', {
        allChunks: true
    })
  );

  plugins.push(
    new OmitTildeWebpackPlugin({
        deprecate: false
    })
  );

var config = {
    plugins: getPlugins(),
    //It generates all the files in a folder as entries.
    entry: glob_entries('./client/**/*.register.jsx'),
    output: {
       path: MODULE_BUILD_DIR,
       filename: '[name].js'
    },
    module: {
        loaders: [
          { test: require.resolve("react"), loader: "expose?React" },
          { test: /\.css$/, include: MODULE_BUILD_CSS_DIR, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
          { test: /\.less$/, include: MODULE_APP_DIR,  loader: ExtractTextPlugin.extract({ loader:[ 'css', 'less'], fallbackLoader: 'style-loader' })},
          { test: /\.jsx?/, include: MODULE_APP_DIR, exclude: /node_modules/, loader: 'babel'}
        ]
    }
};

module.exports = config;
```

Anyone have tried to implement something like this? Any ideas?

**Comment by benjycui** [comment]
If you are not familiar with webpack, you can try https://github.com/ant-tool/atool-build which has integrated with common webpack config.

**Comment by enzolutions** [comment]
Hi @benjycui 

I am familiar with webpack, but I was wondering if maybe there is some special consideration related with antd.

**Comment by yesmeck** [comment]
@enzolutions Which webpack version are you using?

**Comment by JakimLi** [comment]
why was this closed? I am having the same issue as well, I am using webpack, my other css files works ok, only when I do either `import 'antd/dist/antd.css' or use the babel-plugin-import to import the antd css files.

**Comment by benjycui** [comment]
@JakimLi a reproducible repo will be better.

**Comment by enzolutions** [comment]
Hi @yesmeck  and @JakimLi 

Sorry for late response, I am using webpack@1.13.3

This is my **webpack.config.js** file 

```
var webpack = require("webpack");
var path = require('path');
var glob_entries = require('webpack-glob-entries');
var OmitTildeWebpackPlugin = require('omit-tilde-webpack-plugin');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var extend = require("xtend");

var extractLESS = new ExtractTextPlugin('styles/[name].css',  {
    allChunks: true
});

var MODULE_BUILD_DIR = path.resolve(__dirname, 'web/assets/build');
var MODULE_BUILD_CSS_DIR = path.resolve(__dirname, 'client/css');
var MODULE_APP_DIR = path.resolve(__dirname, 'client/');

function getPlugins() {
    var plugins = [];

    plugins.push(extractLESS);
    plugins.push(
        new OmitTildeWebpackPlugin({
            deprecate: false
        })
    );
    return plugins;
}

var config = [
    {
        plugins: getPlugins(),
        entry: extend(glob_entries('./client/**/*.register.jsx'), glob_entries('./client/less/*.less')),
        output: {
            path: MODULE_BUILD_DIR,
            filename: '[name].js'
        },
        module: {
            loaders: [
                { test: require.resolve("react"), loader: "expose?React" },
                { test: /\.css$/, include: MODULE_BUILD_CSS_DIR, loader: ExtractTextPlugin.extract('style-loader', 'css-loader') },
                { test: /\.less$/i, loader: extractLESS.extract(['css','less'])},
                { test: /\.jsx?/, include: MODULE_APP_DIR, exclude: /node_modules/, loader: 'babel'},
            ],
        }
    }
];

module.exports = config;
```
The key is using ExtractTextPlugin and ExtractLess with proper loaders, I hope this works for you
