### ISSUE TITLE
`Uncaught Error: must set key for <rc-animate> children` on modal

### ISSUE THREAD

**Issue by bkniffler** [ant-design/ant-design#4120]
When using preact and modals, I'm getting `Uncaught Error: must set key for <rc-animate> children`.

The issue seems to be due to https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L191 needing a key for rc-animate to not complain.

I don't know why this is not thrown if I use react.

Here the stacktrace.
```
Animate.js:290 Uncaught Error: must set key for <rc-animate> children
    at http://localhost:3011/client/index.js:147664:17
    at Array.map (native)
    at cl.render (http://localhost:3011/client/index.js:147659:32)
    at callMethod (http://localhost:3011/client/index.js:1178:12)
    at cl.render (http://localhost:3011/client/index.js:1186:12)
    at renderComponent (http://localhost:3011/client/index.js:146284:60)
    at setComponentProps (http://localhost:3011/client/index.js:146265:103)
    at buildComponentFromVNode (http://localhost:3011/client/index.js:146354:13)
    at idiff (http://localhost:3011/client/index.js:146160:48)
    at innerDiffNode (http://localhost:3011/client/index.js:146211:21)(anonymous function) @ Animate.js:290render @ Animate.js:285callMethod @ index.js:442(anonymous function) @ index.js:450renderComponent @ preact.js:303setComponentProps @ preact.js:284buildComponentFromVNode @ preact.js:373idiff @ preact.js:179innerDiffNode @ preact.js:230idiff @ preact.js:196innerDiffNode @ preact.js:230idiff @ preact.js:196diff @ preact.js:157renderComponent @ preact.js:326renderComponent @ preact.js:317setComponentProps @ preact.js:284buildComponentFromVNode @ preact.js:373idiff @ preact.js:179diff @ preact.js:157render @ preact.js:409render @ index.js:142renderSubtreeIntoContainer @ index.js:160_renderComponent @ getContainerRenderMixin.js:47componentDidMount @ getContainerRenderMixin.js:59callMethod @ index.js:442(anonymous function) @ index.js:450flushMounts @ preact.js:149renderComponent @ preact.js:354setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310setComponentProps @ preact.js:284renderComponent @ preact.js:310forceUpdate @ preact.js:472(anonymous function) @ History.js:46(anonymous function) @ createTransitionManager.js:66notifyListeners @ createTransitionManager.js:65setState @ createBrowserHistory.js:99(anonymous function) @ createBrowserHistory.js:188confirmTransitionTo @ createTransitionManager.js:44push @ createBrowserHistory.js:168StaticRouter._this.transitionTo @ StaticRouter.js:46Link._this.handleTransition @ Link.js:55Link._this.handleClick @ Link.js:46eventProxy @ preact.js:130
```

**Comment by ifokeev** [comment]
Same here =\

**Comment by ViGi-P** [comment]
I'm facing this same problem with react. :(
When using Upload inside Modal.

**Comment by serprex** [comment]
````
Error: must set key for <rc-animate> children


    in Animate (created by UploadList)
    in UploadList (created by LocaleReceiver)
    in LocaleReceiver (created by Upload)
    in span (created by Upload)
    in Upload (created by Upload)
````

**Comment by LxRuzx** [comment]
So how do you solve it?

**Comment by XiaoCai20180701** [comment]
> ```
> Error: must set key for <rc-animate> children
> 
> 
>     in Animate (created by UploadList)
>     in UploadList (created by LocaleReceiver)
>     in LocaleReceiver (created by Upload)
>     in span (created by Upload)
>     in Upload (created by Upload)
> ```
> Caused by setting `fileList` to an array of my own creation

**What  was the solution?**

**Comment by serprex** [comment]
@XiaoCai20180701 My solution was to reimplement `Upload`. Project has since transitioned to semantic-ui

**Comment by zungweingo** [comment]
When you using Upload, the fileList should have 'uid'

**Comment by iamsongqian** [comment]
> I got this error today , finally i solve it by this
> 
> ```js
> //before
> setFieldsValue({
>      fileList,
>    });
> 
> //after
>  setFieldsValue({
>      fileList: fileList.map(item => ({
>           ...item,
>           uid: getUUid(),
>         })),
>    });
> ```
> 
> by add uid filed

so what's ur getUid()? random number?

**Comment by 07akioni** [comment]
> > I got this error today , finally i solve it by this
> > ```js
> > //before
> > setFieldsValue({
> >      fileList,
> >    });
> > 
> > //after
> >  setFieldsValue({
> >      fileList: fileList.map(item => ({
> >           ...item,
> >           uid: getUUid(),
> >         })),
> >    });
> > ```
> > 
> > 
> > by add uid filed
> 
> so what's ur getUid()? random number?

maybe `getUniqueId`

**Comment by Abel-Johnson** [comment]
> > > I got this error today , finally i solve it by this
> > > ```js
> > > //before
> > > setFieldsValue({
> > >      fileList,
> > >    });
> > > 
> > > //after
> > >  setFieldsValue({
> > >      fileList: fileList.map(item => ({
> > >           ...item,
> > >           uid: getUUid(),
> > >         })),
> > >    });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > by add uid filed
> > 
> > 
> > so what's ur getUid()? random number?
> 
> maybe `getUniqueId`

like this?

	/**
     * 生成唯一id
     * @return {string}
    */
   function getUniqueId() {
        var CHARS = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'.split('');
        //获取MsgId

        var uuid = 'xxxxxx'.replace(/x/g, function () {
            var index = (Math.random() * 62) | 0;
            return CHARS[index];
    });
