### ISSUE TITLE
Tooltip: findDOMNode is deprecated 

### ISSUE THREAD

**Issue by evgeniyworkbel** [ant-design/ant-design#41497]
### Reproduction link

[https://github.com/Kalips0o/IT-PM](https://github.com/Kalips0o/IT-PM)

### Steps to reproduce

I wrap svg according to Icon API:

```
import Icon from '@ant-design/icons';

function InfoSvg() {
    return (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path fillRule="evenodd" clipRule="evenodd" d="M12 2.25C12 2.25 13.9831 2.25 15.7954 3.01651C15.7954 3.01651 17.5452 3.75663 18.8943 5.10571C18.8943 5.10571 20.2434 6.45478 20.9835 8.20463C20.9835 8.20463 21.75 10.0169 21.75 12C21.75 12 21.75 13.9831 20.9835 15.7954C20.9835 15.7954 20.2434 17.5452 18.8943 18.8943C18.8943 18.8943 17.5452 20.2434 15.7954 20.9835C15.7954 20.9835 13.9831 21.75 12 21.75C12 21.75 10.0169 21.75 8.20463 20.9835C8.20463 20.9835 6.45478 20.2434 5.10571 18.8943C5.10571 18.8943 3.75663 17.5452 3.01651 15.7954C3.01651 15.7954 2.25 13.9831 2.25 12C2.25 12 2.25 10.0169 3.01651 8.20463C3.01651 8.20463 3.75663 6.45478 5.10571 5.10571C5.10571 5.10571 6.45478 3.75663 8.20463 3.01651C8.20463 3.01651 10.0169 2.25 12 2.25ZM12 3.75C12 3.75 10.321 3.75 8.78896 4.39802C8.78896 4.39802 7.30857 5.02417 6.16637 6.16637C6.16637 6.16637 5.02417 7.30857 4.39802 8.78896C4.39802 8.78896 3.75 10.321 3.75 12C3.75 12 3.75 13.679 4.39802 15.211C4.39802 15.211 5.02417 16.6914 6.16637 17.8336C6.16637 17.8336 7.30857 18.9758 8.78896 19.602C8.78896 19.602 10.321 20.25 12 20.25C12 20.25 13.679 20.25 15.211 19.602C15.211 19.602 16.6914 18.9758 17.8336 17.8336C17.8336 17.8336 18.9758 16.6914 19.602 15.211C19.602 15.211 20.25 13.6789 20.25 12C20.25 12 20.25 10.3211 19.602 8.78896C19.602 8.78896 18.9758 7.30857 17.8336 6.16637C17.8336 6.16637 16.6914 5.02417 15.211 4.39802C15.211 4.39802 13.679 3.75 12 3.75Z" fill="#252525" />
            <path d="M12 17.25H12.75C13.1642 17.25 13.5 16.9142 13.5 16.5C13.5 16.0858 13.1642 15.75 12.75 15.75V11.25C12.75 10.8358 12.4142 10.5 12 10.5H11.25C10.8358 10.5 10.5 10.8358 10.5 11.25C10.5 11.6642 10.8358 12 11.25 12V16.5C11.25 16.9142 11.5858 17.25 12 17.25Z" fill="#252525" />
            <path d="M12.9375 7.875C12.9375 8.49632 12.4338 9 11.8125 9C11.1912 9 10.6875 8.49632 10.6875 7.875C10.6875 7.25368 11.1912 6.75 11.8125 6.75C12.4338 6.75 12.9375 7.25368 12.9375 7.875Z" fill="#252525" />
        </svg>
    );
}

export default function InfoIcon(props) {
    return <Icon component={InfoSvg} {...props} />;
}
```

Then I need to tooltip which render this icon. I wrote the following code:

```
...
 return (
               <div className={styles.messagePin}>
                  <label htmlFor="pin">
                      Закрепить сообщение
                      <Tooltip title="Pin message">
                          <InfoIcon />
                       </Tooltip>
                   </label>
                 <Switch />
                 </div>
...
```

### What is expected?

There is no warning in console

### What is actually happening?

There is warning in console

```
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at span
    at http://localhost:3000/static/js/bundle.js:10692:25
    at InfoIcon
    at http://localhost:3000/static/js/bundle.js:13903:24
    at DomWrapper (http://localhost:3000/static/js/bundle.js:51588:90)
    at SingleObserver (http://localhost:3000/static/js/bundle.js:51630:24)
    at ResizeObserver (http://localhost:3000/static/js/bundle.js:51757:24)
    at http://localhost:3000/static/js/bundle.js:14520:34
    at Tooltip (http://localhost:3000/static/js/bundle.js:55862:32)
...
```

| Environment | Info |
| --- | --- |
| antd | 5.3.2 |
| React | 18.2.0 |
| System | Ubuntu 22.04 |
| Browser | Chrome 111 |

**Comment by MadCcc** [comment]
https://codesandbox.io/s/ji-ben-antd-5-3-2-forked-sfx3oy?file=/demo.tsx
`forwardRef` is needed, or it will fallback to `findDOMNode`.

**Comment by evgeniyworkbel** [comment]
@MadCcc thx. Please add example into docs in Tooltip - people will know that is possible
