### ISSUE TITLE
error - node_modules\@babel\runtime\helpers\inherits.js

### ISSUE THREAD

**Issue by HannesPaa** [ant-design/ant-design#41565]
### Reproduction link

[https://github.com/BruckCode/nextjs-with-antd](https://github.com/BruckCode/nextjs-with-antd)

### Steps to reproduce

I init a next js project. I added TailwindCSS. I installed antd and added jest test ignore https://ant.design/docs/react/use-with-create-react-app
I followed the instructions of https://ant.design/docs/react/customize-theme#whole-export

When i build now, all works. But then i added the first antd-Component like Button.

### What is expected?

Should work ;)

### What is actually happening?

This error:
```
error - node_modules\@babel\runtime\helpers\inherits.js (4:10) @ _inherits
error - TypeError: Super expression must either be null or a function
    at _inherits (webpack-internal:///(sc_server)/./node_modules/@babel/runtime/helpers/inherits.js:5:15)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js:16:28)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js:31:2)
    at (sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/DomWrapper.js (C:\Users\Johan\Downloads\nextjs-with-antd\.next\server\app\page.js:27014:1)
    at __webpack_require__ (C:\Users\Johan\Downloads\nextjs-with-antd\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/index.js:13:42)
    at (sc_server)/./node_modules/rc-resize-observer/lib/SingleObserver/index.js (C:\Users\Johan\Downloads\nextjs-with-antd\.next\server\app\page.js:27025:1)
    at __webpack_require__ (C:\Users\Johan\Downloads\nextjs-with-antd\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./node_modules/rc-resize-observer/lib/index.js:18:46)
    at (sc_server)/./node_modules/rc-resize-observer/lib/index.js (C:\Users\Johan\Downloads\nextjs-with-antd\.next\server\app\page.js:27036:1) {
  type: 'TypeError',
  page: '/'
}
```

| Environment | Info |
| --- | --- |
| antd | 5.3.3 |
| React | nextjs 13.2.4 |
| System | Windows 11 |
| Browser | MS Edge |

---
I researched alot, also in existing issues from your repo, but nothing fixed it.

**Comment by zombieJ** [comment]
Server component not support client only dom wrapper. Add `'use client'` mark to render in client:

```diff
    // page.tsx
++  'use client';

    import { Card, Button } from "antd";
```

For next `experimental` behavior, it's better to check next official doc instead dig in component lib : )
<img width="958" alt="截屏2023-04-06 10 48 04" src="https://user-images.githubusercontent.com/5378891/230259886-493ea301-d243-44ce-a54a-5a4df755a70f.png">


ref: 
* https://github.com/vercel/next.js/issues/42553#issuecomment-1306792489
* https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components

**Comment by amitsarkerr** [comment]
'use client' works good.
