### ISSUE TITLE
ColorPicker 导致 vite 无法运行

### ISSUE THREAD

**Issue by liuweiGL** [ant-design/ant-design#42437]
### Reproduction link

[https://github.com/liuweiGL/antd-color-picker-bug](https://github.com/liuweiGL/antd-color-picker-bug)

### Steps to reproduce

1. git clone git@github.com:liuweiGL/antd-color-picker-bug.git
2. pnpm i
3. pnpm dev

### What is expected?

构建正常

### What is actually happening?

vite 报错:
```
VITE v4.3.7  ready in 510 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] No matching export in "node_modules/.pnpm/@rc-component color-picker@1.0.1_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/index.js" for import "ColorPickerPanel"

    node_modules/.pnpm/antd@5.5.0_react-dom@18.2.0_react@18.2.0/node_modules/antd/es/color-picker/ColorPickerPanel.js:9:9:
      9 │ import { ColorPickerPanel as RcColorPickerPanel } from '@rc-component/color-picker';
        ╵          ~~~~~~~~~~~~~~~~

C:\Users\liuwei\Desktop\demo\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/antd@5.5.0_react-dom@18.2.0_react@18.2.0/node_modules/antd/es/color-picker/ColorPickerPanel.js:9:9: ERROR: No matching export in "node_modules/.pnpm/@rc-component color-picker@1.0.1_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/index.js" for import "ColorPickerPanel"
    at failureErrorWithLog (C:\Users\liuwei\Desktop\demo\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Users\liuwei\Desktop\demo\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1048:25
    at C:\Users\liuwei\Desktop\demo\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 9,
        file: 'node_modules/.pnpm/antd@5.5.0_react-dom@18.2.0_react@18.2.0/node_modules/antd/es/color-picker/ColorPickerPanel.js',
        length: 16,
        line: 9,
        lineText: "import { ColorPickerPanel as RcColorPickerPanel } from '@rc-component/color-picker';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/@rc-component color-picker@1.0.1_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/index.js" for import "ColorPickerPanel"'
    }
  ],
  warnings: []
}

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.

```

| Environment | Info |
| --- | --- |
| antd | 5.5.0 |
| React | 18.2.0 |
| System | Windows10 |
| Browser | Chrome 99.0.4844.51 |

---
https://github.com/ant-design/ant-design/blob/7271b7cb91801e37620e2925d136babce1ea5faa/components/color-picker/ColorPicker.tsx#L7

**Comment by RedJue** [comment]
嗯，应该是引用了 `lib` 目录导致的，后面发个修复版本换成 `es` 目录

**Comment by YHGod** [comment]
啥时候发 这会阻塞了 Attempted import error: 'ColorPickerPanel' is not exported from '@rc-component/color-picker' (imported as 'RcColorPickerPanel').

**Comment by RedJue** [comment]
> 啥时候发 这会阻塞了 Attempted import error: 'ColorPickerPanel' is not exported from '@rc-component/color-picker' (imported as 'RcColorPickerPanel').

临时处理可以先把 `@rc-component/color-picker` 锁 1.0.0，后面把 rc `lib` 换成 `es` 一起发

**Comment by stefanwille** [comment]
Looks like I have the same issue - Ant 5.5.0 and a fresh Vite 4.3.7 project. 

Here is a repo with a minimal reproduction: https://github.com/stefanwille/ant-550-vite-437

**Comment by MadCcc** [comment]
+latest: @rc-component/color-picker@1.0.0

**Comment by MadCcc** [comment]
1.0.1 版本 和 antd 5.5.0 不同步，先回退 dist-tag 了

**Comment by mvpyb** [comment]
我就说 上一秒好好的， 下一秒就报错了

**Comment by h7ml** [comment]
+1 同样遇到该问题。发生在开发和编译阶段

**Comment by MadCcc** [comment]
有类似问题的重新安装下依赖哈，latest 回到 1.0.0 了。

If encountered with same issue, just reinstall dependencies. The latest version of `@rc-component/color-picker` have been rollback to `v1.0.0`

**Comment by mvpyb** [comment]
![image](https://github.com/ant-design/ant-design/assets/34262867/4ff577aa-e1df-474b-b7fc-eae1d80254eb)
就是刚发布的1.0.1不兼容导致的

**Comment by stefanwille** [comment]
Works for me, thanks!

**Comment by RedJue** [comment]
Sorry guys.

**Comment by liuweiGL** [comment]
我试了下好像还是不行呢，5.5.0 版本中引用的 `color-picker` 是 ~1.0.0 的

https://github.com/ant-design/ant-design/blob/1a2906941f551028677379ba3c47fbe4e9969a2f/package.json#LL116C42-L116C42

但是截止到 `color-picker@1.0.2` 这个包里面没有 `rc-util` 依赖导致使用 pnpm 安装时 vite 还是会报错

https://github.com/react-component/color-picker/blob/daf32c833f8ac4963c972ff2abec67e3356255e3/package.json#L47

```
VITE v4.3.8  ready in 718 ms

  ➜  Local:   https://localhost:8080/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] Could not resolve "rc-util/es/hooks/useMergedState"

    ../../node_modules/.pnpm/@rc-component+color-picker@1.0.2_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/ColorPicker.js:6:27:
      6 │ import useMergedState from "rc-util/es/hooks/useMergedState";
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "rc-util/es/hooks/useMergedState" as external to exclude it from the bundle,
  which will remove this error.

C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
../../node_modules/.pnpm/@rc-component+color-picker@1.0.2_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/ColorPicker.js:6:27: ERROR: Could not resolve "rc-util/es/hooks/useMergedState"
    at failureErrorWithLog (C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1048:25
    at C:\Users\liuwei\Desktop\gitlab\eastcoal-pc\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: '../../node_modules/.pnpm/@rc-component+color-picker@1.0.2_react-dom@18.2.0_react@18.2.0/node_modules/@rc-component/color-picker/es/ColorPicker.js',
        length: 33,
        line: 6,
        lineText: 'import useMergedState from "rc-util/es/hooks/useMergedState";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "rc-util/es/hooks/useMergedState" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "rc-util/es/hooks/useMergedState"'
    }
  ],
  warnings: []
}
```

**Comment by liuweiGL** [comment]
pnpm 用户可以先在项目里面加个 rc-util 依赖，等 antd 更新了再移除

**Comment by RedJue** [comment]
> pnpm 用户可以先在项目里面加个 rc-util 依赖，等 antd 更新了再移除
> 
> 

等下次patch更新☺️
