### ISSUE TITLE
using imageRender causes zoom toolbar to error

### ISSUE THREAD

**Issue by deathemperor** [ant-design/ant-design#43857]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-preview-render-antd-5-7-3-forked-h6mn3f)

### Steps to reproduce

- use imageRender
- click on Zoom in or out

### What is expected?

no error, imageRender() is called like when pressing flip or rotate

### What is actually happening?

nothing happened, imageRender() is not called, error to console.log

```
useImageTransform.js:57 Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at dispatchZoomChange2 (useImageTransform.js:57:31)
    at onZoomIn2 (Preview.js:109:5)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
    at react-dom.development.js:9288:12
    at batchedUpdates$1 (react-dom.development.js:26140:12)
    at batchedUpdates (react-dom.development.js:3991:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:3)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:5)
    at dispatchEvent (react-dom.development.js:6457:5)
```

| Environment | Info |
| --- | --- |
| antd | 5.7.3 |
| React | 18.0.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by 1123612483** [comment]
因为自定义了预览内容，所以要使用工具栏的功能，得配合`toolbarRender`人手去实现默认工具栏的功能

**Comment by MadCcc** [comment]
@linxianxi

**Comment by linxianxi** [comment]
If you use `imageRender` and don't use originalNode, the operations is invalid. 

like this demo, you can hide toolbar https://ant.design/components/image-cn#image-demo-imagerender

or

```
imageRender={originalNode => <>{originalNode}  other... </>}
```

**Comment by zombieJ** [comment]
`imageRender` provide origin node. Use `cloneElement` to handle it:
https://codesandbox.io/s/custom-preview-render-antd-5-7-3-forked-nz3ygs?file=/demo.tsx

**Comment by rapasoft** [comment]
Hi! I just wanted to comment on that the originNode is of different type than I would expect. I would expect, that it would be of `<Image />` type, but it is basically a React Node wrapper over `<img />`, therefore it is not possible to adjust other properties like adding custom placeholder.

I am now struggling with how to use both custom toolbarRender and imageRender and also use functionality of `<Image />` when preview is loaded. Would be nice if someone could comment on that. I don't want to hijack this ticket, but it just comes naturally to me, to continue this discussion here.
