### ISSUE TITLE
2023-08-10 yarn install Error

### ISSUE THREAD

**Issue by Tridu33** [ant-design/ant-design#44149]
### Reproduction link

[https://npm.taobao.org/mirrors/115.0.5790.170/win64/chrome-win64.zip](https://npm.taobao.org/mirrors/115.0.5790.170/win64/chrome-win64.zip)

### Steps to reproduce

```cmd
[4/4] Building fresh packages...
[-/12] ⠄ waiting...
[-/12] ⠄ waiting...
[3/12] ⠄ sharp
[-/12] ⠄ waiting...
error C:\Users\antddebugger\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\antddebugger\node_modules\puppeteer
Output:
PUPPETEER_DOWNLOAD_HOST is deprecated. Use PUPPETEER_DOWNLOAD_BASE_URL instead.
(node:33524) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR: Failed to set up Chrome r115.0.5790.170! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/115.0.5790.170/win64/chrome-win64.zip
    at C:\Users\antddebugger\node_modules\@puppeteer\browsers\lib\cjs\httpUtil.js:102:31
    at ClientRequest.requestCallback (C:\Users\antddebugger\node_modules\@puppeteer\browsers\lib\cjs\httpUtil.js:79:13)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
```

### What is expected?

`git clone --depth=1 --single-branch git@github.com:ant-design/ant-design.git` 后`yarn install`期待能安装依赖成功，然后可以从 `antd/node_modules/@antd-design/tools/lib/getWebpackConfig.js` 就可以找到 webpack 的配置 `cheap-module-source-map`。但是安装依赖失败，说
```cmd
ERROR: Failed to set up Chrome r115.0.5790.170! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 404. URL: https://npm.taobao.org/mirrors/115.0.5790.170/win64/chrome-win64.zip
```
这个链接确实下载不了chrome，问题是为啥`yarn install`需要chrome?

### What is actually happening?

安装依赖失败

| Environment | Info |
| --- | --- |
| antd | 5.8.2 |
| React | none |
| System | windows 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
antd 会做截图测试，用的 Puppeteer。可以按照它的提示设置跳过下载，或者配置一下 Puppeteer windows 的镜像源哈~
