### ISSUE TITLE
npm run dev 时报错

### ISSUE THREAD

**Issue by uedkx** [ant-design/ant-design#451]
TEARS-2:antd-demo TEARS$ npm run dev

> antd-demo@1.0.0 dev /Users/TEARS/Desktop/antd-demo
> antd server

/Users/TEARS/Desktop/antd-demo/node_modules/antd-bin/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/TEARS/Desktop/antd-demo/node_modules/antd-bin/lib/server.js:16:13)
    at Object.<anonymous> (/Users/TEARS/Desktop/antd-demo/node_modules/antd-bin/bin/antd-server:11:25)
    at Module._compile (module.js:460:26)
TEARS-2:antd-demo TEARS$

**Comment by afc163** [comment]
node 版本太老了，建议用  4.0+ 。
