### ISSUE TITLE
FloatButton has console warning in 5.10.1

### ISSUE THREAD

**Issue by zystudios** [ant-design/ant-design#45387]
### Reproduction link

none

### Steps to reproduce

<FloatButton.BackTop visibilityHeight={1000} tooltip="Back to Top" />

### What is expected?

No warnings on the console

### What is actually happening?

console has warning

I'm using strict mode and it seems like strict mode causes a warning?
I don't want warnings in strict mode

```
react-dom.development.js:86 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at button
    at FloatButton (webpack-internal:///./node_modules/antd/es/float-button/FloatButton.js:41:18)
    at DomWrapper (webpack-internal:///./node_modules/rc-motion/es/DomWrapper.js:20:90)
    at eval (webpack-internal:///./node_modules/rc-motion/es/CSSMotion.js:51:32)
    at BackTop (webpack-internal:///./node_modules/antd/es/float-button/BackTop.js:41:18)
    at div
    at App (webpack-internal:///./client/src/page/view-all-member/index.tsx:74:69)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:554:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1170:5)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1108:15)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/dist/index.js:399:5)
    at LocaleProvider (webpack-internal:///./node_modules/antd/es/locale/index.js:23:5)
    at MotionWrapper (webpack-internal:///./node_modules/antd/es/config-provider/MotionWrapper.js:16:5)
    at ProviderChildren (webpack-internal:///./node_modules/antd/es/config-provider/index.js:133:5)
    at ConfigProvider (webpack-internal:///./node_modules/antd/es/config-provider/index.js:392:54)
    at div
    at App
```

| Environment | Info |
| --- | --- |
| antd | 5.10.1 |
| React | 18.2.0 |
| System | windows 10 |
| Browser | chrome 117.0.5938.92 |

**Comment by zombieJ** [comment]
Patch reproduce https://codesandbox.io/s/hui-dao-ding-bu-antd-5-10-0-forked-nxsxyz?file=/demo.tsx

**Comment by zystudios** [comment]
> Patch reproduce https://codesandbox.io/s/hui-dao-ding-bu-antd-5-10-0-forked-nxsxyz?file=/demo.tsx

also has the warning

chrome 117.0.5938.92

![image](https://github.com/ant-design/ant-design/assets/29728228/7c2aa5ac-ede9-4fcf-8d2f-029a3012f94d)

**Comment by nerdess** [comment]
Any news regarding this one?

I get the same error when I wrap a `<Radio.Button />` with a `<Tooltip />` on latest antd (v5.11.5)

```
<Radio.Group>
  <Tooltip title='This activates Yes'>
    <Radio.Button value='1'>
      Yes
    </Radio.Button>
  </Tooltip>
  <Tooltip title='This activates No'>
    <Radio.Button value='0'>
      No
    </Radio.Button>
  </Tooltip>
</Radio.Group>
```
<img width="694" alt="Bildschirmfoto 2024-01-12 um 14 06 12" src="https://github.com/react-component/motion/assets/711925/d19d4b43-ec15-4807-a75c-feec4f2f3e76">

**Comment by datts68** [comment]
Same issue when using <FloatButton />

**Comment by WouterrV** [comment]
> Any news regarding this one?
> 
> I get the same error when I wrap a `<Radio.Button />` with a `<Tooltip />` on latest antd (v5.11.5)
> 
> ```
> <Radio.Group>
>   <Tooltip title='This activates Yes'>
>     <Radio.Button value='1'>
>       Yes
>     </Radio.Button>
>   </Tooltip>
>   <Tooltip title='This activates No'>
>     <Radio.Button value='0'>
>       No
>     </Radio.Button>
>   </Tooltip>
> </Radio.Group>
> ```
> 
> <img alt="Bildschirmfoto 2024-01-12 um 14 06 12" width="694" src="https://private-user-images.githubusercontent.com/711925/296248686-d19d4b43-ec15-4807-a75c-feec4f2f3e76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDk0OTQsIm5iZiI6MTcxOTQwOTE5NCwicGF0aCI6Ii83MTE5MjUvMjk2MjQ4Njg2LWQxOWQ0YjQzLWVjMTUtNDgwNy1hNzVjLWZlZWM0ZjJmM2U3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMzM5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTE2NDU0ZDk4MzA5OTAyZWQyMTMwMzRlZGJhODI0YzA0YzM0MjkzYzYwMGM4NWZhODhkMTJjMDE4Nzg5N2E3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tNmWO5xTEiqf6kavAYu-d38j37kId9RCMUC1OgpEsZs">

That can be fixed/worked around by putting a <div> in between the Tooltip and the Button
