### ISSUE TITLE
warning.js:19 Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`? 

### ISSUE THREAD

**Issue by HappyAxin** [ant-design/ant-design#46235]
### Reproduction link

[https://ant-design.antgroup.com/components/upload-cn](https://ant-design.antgroup.com/components/upload-cn)

### Steps to reproduce

```js
<Upload.Dragger
    name={"fileList"}
    multiple={true}
    beforeUpload={() => false}
    listType={"picture"}
    >
        <p className="ant-upload-drag-icon">
            <InboxOutlined />
            </p>
    <p className="ant-upload-text">点击或拖动文件至此区域上传</p>
    <p className="ant-upload-hint">支持单次或批量上传。严禁上传公司数据或其他违禁文件。</p>
</Upload.Dragger>
```

### What is expected?

Console does not report errors

### What is actually happening?
```bash
Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`? 
    at InternalUpload (http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_InboxOutlined_js-node_modules_antd_es_modal_in-3ee128.chunk.js:3158:5)
    at http://localhost:3000/static/js/vendors-node_modules_ant-design_icons_es_icons_InboxOutlined_js-node_modules_antd_es_modal_in-3ee128.chunk.js:3065:7
    at http://localhost:3000/static/js/vendors-node_modules_antd_es_form_index_js.chunk.js:904:5
    at StatusProvider (http://localhost:3000/static/js/vendors-node_modules_antd_es_form_index_js.chunk.js:789:5)
```
![image](https://github.com/ant-design/ant-design/assets/46963688/47f64bcc-9a4c-48db-9fc8-3097e05f8127)
| Environment | Info |
| --- | --- |
| antd | 5.11.5 |
| React | 18.2 |
| System | windows |
| Browser | Chrome 119.0.6045.200（正式版本） |

**Comment by zombieJ** [comment]
As warning told, `value` is not a valid prop, use `fileList` instead.

**Comment by erikpa1** [comment]
@zombieJ Warning told nothing, he don't have "value" prop in his code, I have same problem,...

**Comment by xsvato01** [comment]
same here

**Comment by jeanmaried** [comment]
@zombieJ why did you close this? You didn't even try to answer the question and other people, myself included have this same issue.

```
<Upload
        name={name}
        listType="picture-circle"
        showUploadList={false}
        action="/api/upload-image"
        beforeUpload={beforeUpload}
        onChange={handleChange}
/>
```

No `value` prop and i get the same warning (being logged as an error).

**Comment by starry** [comment]
> @zombieJ why did you close this? You didn't even try to answer the question and other people, myself included have this same issue.
> 
> ```
> <Upload
>         name={name}
>         listType="picture-circle"
>         showUploadList={false}
>         action="/api/upload-image"
>         beforeUpload={beforeUpload}
>         onChange={handleChange}
> />
> ```
> 
> No `value` prop and i get the same warning (being logged as an error).

**add valuePropName for form.item**
 <Form.Item label="avatar" name="avatar" valuePropName="avatar">
<Upload .......
 </Form.Item>

**Comment by fires3as0n** [comment]
> > @zombieJ why did you close this? You didn't even try to answer the question and other people, myself included have this same issue.
> > ```
> > <Upload
> >         name={name}
> >         listType="picture-circle"
> >         showUploadList={false}
> >         action="/api/upload-image"
> >         beforeUpload={beforeUpload}
> >         onChange={handleChange}
> > />
> > ```
> > No `value` prop and i get the same warning (being logged as an error).
> 
> **add valuePropName for form.item** <Form.Item label="avatar" name="avatar" valuePropName="avatar"> <Upload ....... </Form.Item>

This worked for me, but I have 2 questions:
1. valuePropName can be set to literally any string, error will be gone, and the form will still work. So why does that happen?
2. Why do contributors close issues without even trying to solve them (@zombieJ  ??)
