### ISSUE TITLE
导入自制iconfont出错问题

### ISSUE THREAD

**Issue by linyongping** [ant-design/ant-design#4820]
项目采用dva + antd 的组合antd - 2.6.4

由于antd自带的icon图标组件不能满足业务需要，所以需要导入其他的iconfont。现在的问题是，从iconfont.cn下载下来的字体一旦引入便会报错，尝试很多方法不能解决，特地前来求助各位只要在项目中引入这个css文件便会报错

webpack中的transform-runtime style配置为true
```
    webpackConfig.babel.plugins.push('transform-runtime');
    webpackConfig.babel.plugins.push(['import', {
        libraryName: 'antd',
        style: true  // if true, use less
    }]);
```

字体文件css，unicode码特意避开了antd自带的icon，unicode码

```
@font-face {font-family: "myicon_lucky";
  src: url('iconfont.eot'); /* IE9*/
  src: url('iconfont.eot?t#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('iconfont.woff') format('woff'), /* chrome, firefox */
  url('iconfont.ttf') format('truetype');
}

.myicon_lucky {
  font-family:"myicon_lucky" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.myicon-iconfontedit:before { content: "\e715"; }

.myicon-dongjie:before { content: "\e713"; }


.myicon-jiechudongjie:before { content: "\e712"; }

.myicon-quanxian:before { content: "\e710"; }
```
只要在index.less中引入字体的css文件就会报错，把css文件后缀改为less也同样报错
```
ERROR in ./src/index.less
Module build failed: Error
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:726:13
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:52:16
    at done (D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:241:17)
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:44:16
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:723:17
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\async\lib\async.js:167:37
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
    at innerCallback (D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\Resolver.js:94:11)
    at loggingCallbackWrapper (D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\tapable\lib\Tapable.js:134:6
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:54:23
    at D:\httpWork\adminGateway\admin-gateway\src\main\resources\node_modules\enhanced-resolve\lib\Resolver.js:191:15
 @ ./src/index.js 5:0-23
```

**Comment by afc163** [comment]
给出可重现的 repo 和操作步骤吧。

**Comment by kairi1227** [comment]
猜一下你出问题的地方应该是：
```
@font-face {font-family: "myicon_lucky";
  src: url('iconfont.eot'); /* IE9*/
  src: url('iconfont.eot?t#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('iconfont.woff') format('woff'), /* chrome, firefox */
  url('iconfont.ttf') format('truetype');
}
```

加个相对路径就好了。修改为以下内容试试：
```
@font-face {font-family: "myicon_lucky";
  src: url('./iconfont.eot'); /* IE9*/
  src: url('./iconfont.eot?t#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('./iconfont.woff') format('woff'), /* chrome, firefox */
  url('./iconfont.ttf') format('truetype');
}
```

**Comment by afc163** [comment]
Close for no response.
