### ISSUE TITLE
Menu 组件focus状态，按方向键会报错：Uncaught TypeError: obj.onKeyDown is not a function

### ISSUE THREAD

**Issue by ds3783** [ant-design/ant-design#4849]
#### Environment(required)

- antd version:2.1.0
- OS and its version:MacOS 10.12.3
- Browser and its version:Chrome/56.0.2924.87

#### What did you do? Please provide steps to re-produce your problem.

使用了Menu、SubMenu和Menu.Item，点击SubMenu。
点击SubMenu展开后，按任意方向键，即可复现。

#### What do you expected?

不报错误

#### What happen?

控制台提示脚本错误：
Uncaught TypeError: obj.onKeyDown is not a function
    at http://localhost:8000/index.js:12663:24
    at Array.forEach (native)
    at Object.onKeyDown (http://localhost:8000/index.js:12661:34)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8000/index.js:8370:17)
    at executeDispatch (http://localhost:8000/index.js:7900:22)
    at Object.executeDispatchesInOrder (http://localhost:8000/index.js:7923:6)
    at executeDispatchesAndRelease (http://localhost:8000/index.js:4469:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8000/index.js:4480:11)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:8000/index.js:14644:10)

实际报错是：handled = obj.onKeyDown(e);

var MenuMixin = {
......
 // all keyboard events callbacks run from here at first
	  onKeyDown: function onKeyDown(e) {
	    var _this = this;

	    var keyCode = e.keyCode;
	    var handled = void 0;
	    this.getFlatInstanceArray().forEach(function (obj) {
	      if (obj && obj.props.active) {
	        **handled = obj.onKeyDown(e);**
	      }
	    });

**Comment by benjycui** [comment]
先升级至最新依赖版本。

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by ds3783** [comment]
I upgraded antd to 2.7.1 also other dependcies. and I wrote a demo  can reproduce the issue:
http://codepen.io/ds3783/pen/XpoQRY

**Comment by benjycui** [comment]
@ds3783 you should wrap `Menu.SubMenu` like this:

```jsx
class MySubMenu extends Component{
  onKeyDown() {
    // call SubMenu's onKeyDown
  }
  render(){
    return (<SubMenu {...this.props}>
        {this.props.children}
      </SubMenu>);
  }
}
```

**Comment by ds3783** [comment]
@benjycui  it  works 3q
