### ISSUE TITLE
table 组件 dataIndex 不能为children, 建议要么兼容要么在文档标识‼️一下

### ISSUE THREAD

**Issue by herbertxy** [ant-design/ant-design#49772]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2qfxhx?file=/index.js)

### Steps to reproduce

<Table
columns={[{
dataIndex: 'children',
title: 'children',
key: 'children'
}]}
dataSource={[{children: 111, id: 1}]}
/>

### What is expected?

程序运行正常

### What is actually happening?

组件奔溃，报错：
useSelection.js:52 Uncaught TypeError: (data || []).forEach is not a function
    at flattenData (useSelection.js:52:16)
    at eval (useSelection.js:55:203)
    at Array.forEach (<anonymous>)
    at flattenData (useSelection.js:52:16)
    at eval (useSelection.js:128:12)
    at mountMemo (react-dom.development.js:15846:19)
    at Object.useMemo (react-dom.development.js:16219:16)
    at useMemo (react.development.js:1532:21)
    at useSelection (useSelection.js:127:68)

| Environment | Info |
| --- | --- |
| antd | 4.24.16 | 5.X
| React | 17 |
| System | mac os 14 |
| Browser | chrome lasted |

**Comment by herbertxy** [comment]
应该说是datasource 的数据key 不能是children

**Comment by herbertxy** [comment]
5.x 同样有这个问题
