### ISSUE TITLE
带有 autoSize 的 TextArea 卸载后，用来计算的元素没有清除干净

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#51050]
### Reproduction link

[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/react-kgzvm9?file=demo.tsx)

### Steps to reproduce

1、点击 Hidden
2、控制台查看元素

### What is expected?

清除

### What is actually happening?

有个用来计算的 textarea 一直存在

![image](https://github.com/user-attachments/assets/af5026a5-472b-435c-a687-86552cc62d61)

| Environment | Info |
| --- | --- |
| antd | 5.21.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
这个元素是全局唯一的，在表格场景里多个 TextArea 设置 resize 会频繁创建删除导致性能损耗。所以干脆就不删了。

**Comment by jinxiangqiang** [comment]
Warning: `NaN` is an invalid value for the `height` css style property.
    at textarea
    at SingleObserver (http://localhost:9030/umi.js:43192:5)
    at ResizeObserver (http://localhost:9030/umi.js:43262:5)
    at eval (http://localhost:9030/umi.js:51455:5)
    at eval (http://localhost:9030/umi.js:27547:19)
    at eval (http://localhost:9030/umi.js:51604:3)
    at eval (http://localhost:9030/umi.js:87532:16)
    at FieldTextArea (http://localhost:9030/umi.js:225401:5)
    at ProFieldComponent (http://localhost:9030/umi.js:220889:3)
    at BaseProFormField (http://localhost:9030/umi.js:226297:5)
    at WithValueFomFiledProps (http://localhost:9030/umi.js:226424:15)
在我离开页面时，会报这个警告，是因为我使用了KeepAlive的原因吗？
