### ISSUE TITLE
DatePicker throws a warning when using the format prop.

### ISSUE THREAD

**Issue by devcaco** [ant-design/ant-design#51839]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-jyh2k9)

### Steps to reproduce

When using the Format prop with Format and type: mask properties in the DatePicker component and when the field is in focus for the first time it throws a warning/note in the console:

Note: Not match any format. Please help to fire a issue about this. 
    at eval (https://vhxjk4.csb.app/node_modules/rc-picker/es/PickerInput/Selector/Input.js:34:22)
    at div
    at SingleSelector (https://vhxjk4.csb.app/node_modules/rc-picker/es/PickerInput/Selector/SingleSelector/index.js:34:18)
    at eval (https://vhxjk4.csb.app/node_modules/@rc-component/trigger/es/TriggerWrapper.js:9:24)
    at DomWrapper (https://vhxjk4.csb.app/node_modules/rc-resize-observer/es/SingleObserver/DomWrapper.js:27:33)
    at SingleObserver (https://vhxjk4.csb.app/node_modules/rc-resize-observer/es/SingleObserver/index.js:19:24)
    at ResizeObserver (https://vhxjk4.csb.app/node_modules/rc-resize-observer/es/index.js:26:24)
    at eval (https://vhxjk4.csb.app/node_modules/@rc-component/trigger/es/index.js:50:34)
    at PickerTrigger (https://vhxjk4.csb.app/node_modules/rc-picker/es/PickerTrigger/index.js:51:27)
    at Picker (https://vhxjk4.csb.app/node_modules/rc-picker/es/PickerInput/SinglePicker.js:55:52)
    at NoCompactStyle (https://vhxjk4.csb.app/node_modules/antd/es/space/Compact.js:50:18)
    at ContextIsolator (https://vhxjk4.csb.app/node_modules/antd/es/_util/ContextIsolator.js:11:17)
    at eval (https://vhxjk4.csb.app/node_modules/antd/es/date-picker/generatePicker/generateSinglePicker.js:55:25)
    at div
    at Item (https://vhxjk4.csb.app/node_modules/antd/es/space/Item.js:10:19)
    at div
    at eval (https://vhxjk4.csb.app/node_modules/antd/es/space/index.js:40:88)
    at App

### What is expected?

Not to throw any warnings and/or notes in the console.

### What is actually happening?

Warning Note is being displayed in the console.

| Environment | Info |
| --- | --- |
| antd | 5.22.2 |
| React | React 18.3.1 |
| System | MacOs  |
| Browser | Chrome 131.0.6778.86 |

**Comment by devcaco** [comment]
Hello, I have updated the original post with the updated code sandbox link.
