### ISSUE TITLE
配合react-starter-kit使用报错

### ISSUE THREAD

**Issue by laispace** [ant-design/ant-design#546]
我使用了 [react-starter-kit](https://github.com/kriasoft/react-starter-kit) 作为脚手架
引入 antd 组件的时候就报错了. 是我的姿势不对?
我的代码很简单, 是这样: 

```
    import { Button } from 'antd';
    <Button type="primary" href="/new">新建页面</Button>

``` .

报的错是:

```
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Github\pager\node_modules\antd\lib\index.js:2:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

react-starter-kit 同样都是支持 ES6 写法的吧.

我看到 antd 有建议的生成项目结构的命令行工具, 但我目前就只想在已有的项目中添加 antd 组件, 有什么兼容的办法么?

**Comment by afc163** [comment]
你确定这么写语法是对的？

**Comment by laispace** [comment]
@afc163 <Button /> 是写在 render() 中的.

**Comment by afc163** [comment]
需要有 less-loader ，可以先自行研究 webpack.config.js 的写法。

https://github.com/ant-tool/atool-build/blob/052b585d124a20a4633879cd0d693027ad7287cd/src/getWebpackCommonConfig.js#L59

**Comment by afc163** [comment]
你可以试试在这行下面

https://github.com/kriasoft/react-starter-kit/blob/2d49465dcd1a6542daf991368e68df0e4591bfe4/src/components/App/App.scss#L1

写上：

```css
@import '../../../node_modules/antd/lib/index.less';
```
