### ISSUE TITLE
and dva框架创建新项目报错

### ISSUE THREAD

**Issue by wanghongxun226** [ant-design/ant-design#5730]
### Version
2.9.1

### Environment
node.js v6.10.2 dva v0.7.8

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
输入 dva new app报错

### What is expected?

Compiled successfully!

The app is running at:

  http://localhost:8000/

Note that the development build is not optimized.
To create a production build, use npm run build.

### What is actually happening?
D:\html\dora>dva new app
C:\Program Files\nodejs\node_modules\dva-cli\bin\dva-new
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

---
dva 所有命令都是报错，参照官网给你的链接https://ant.design/docs/react/practical-projects-cn

**Comment by afc163** [comment]
You should ask at https://github.com/dvajs/dva-cli
