### ISSUE TITLE
官网 TimePicker 选择框底部显示自定义的内容，报错

### ISSUE THREAD

**Issue by forever4313** [ant-design/ant-design#5829]
### Version
2.9.1

### Environment
win7 chrome

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
选择时间，点击ok，console里报错，无法关闭

### What is expected?
关闭正常，不报错

### What is actually happening?
index.js:155 Uncaught TypeError: t.close is not a function
    at onClick (https://ant.design/index.js:155:21785)
    at s.handleClick (https://ant.design/index.js:52:24901)
    at Object.s (https://ant.design/index.js:29:29838)
    at p (https://ant.design/index.js:29:25888)
    at Object.c [as executeDispatchesInOrder] (https://ant.design/index.js:29:26103)
    at d (https://ant.design/index.js:19:23310)
    at h (https://ant.design/index.js:19:23436)
    at Array.forEach (native)
    at t (https://ant.design/index.js:50:17503)
    at Object.processEventQueue (https://ant.design/index.js:19:24514)

**Comment by afc163** [comment]
seems to be related with #5804

**Comment by forever4313** [comment]
话说这个怎么解~~~~系统中用到了这个，以前2.8.3是正常的，现在报错。。。有点怵新版本了。

**Comment by benjycui** [comment]
@afc163 似乎是这里误改了的 https://github.com/react-component/time-picker/commit/3ab3a128deaf10300b31102b79458528227baa54#diff-3887f7d41a7549de526563bb6dd2bdb0L87

**Comment by afc163** [comment]
原来这个 close 是有用的。代码里完全看不出来。

话说这种调用方式也是不 React 的。

**Comment by forever4313** [comment]
那肿么办？最近会打包release吗~~

**Comment by afc163** [comment]
稍等。

**Comment by forever4313** [comment]
干巴爹

**Comment by afc163** [comment]
Reinstall node_modules.

**Comment by yszou** [comment]
@forever4313 

```javascript
onClick={() => panel.props.onEsc()}
```

之前 `close()` 的实现就是 `props.onEsc()` 。
