### ISSUE TITLE
npm run dev 启动报错 

### ISSUE THREAD

**Issue by yaofan** [ant-design/ant-design#612]
**问题描述**

按照快速上手的文档创建了一个文档，但是启动报错了

**发生环境**

- antd 版本： 0.10.x
- 操作系统及版本： mac ari
- 浏览器及版本： chrome
- 在线演示地址：

**重现步骤**

1. npm run dev
2. 报错信息如下：   

yaodeMacBook-Air-2:antd-demo yao$ npm run dev

> antd-demo@1.0.0 dev /Users/yao/antd/antd-demo
> antd server --port 8001

/Users/yao/antd/antd-demo/node_modules/antd-bin/node_modules/koa/lib/application.js:179
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/Users/yao/antd/antd-demo/node_modules/antd-bin/lib/server.js:16:13)
    at Object.<anonymous> (/Users/yao/antd/antd-demo/node_modules/antd-bin/bin/antd-server:11:25)
    at Module._compile (module.js:460:26)
yaodeMacBook-Air-2:antd-demo yao$

**Comment by afc163** [comment]
升级 node 到 4.x 以上。
