### ISSUE TITLE
npm start 报错，卡住

### ISSUE THREAD

**Issue by jokingzhang** [ant-design/ant-design#6227]
node 版本 v5.6.0

npm install 之后，

npm start
看到如下报错：
```
ant-design/node_modules/bisheng-plugin-react/lib/transformer.js:36
  babelConfig = {},
              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/joking_zhang/tmp/react/ant-design/node_modules/bisheng-plugin-antd/lib/process-demo.js:10:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```
并且，当模块加载到：1656/1657 build modules 会卡主...
导致项目跑不起来

**Comment by benjycui** [comment]
> SyntaxError: Unexpected token =

把 Node.js 升级到最新。
