### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by wjx8382** [ant-design/ant-design#650]
D:\React Project\antd-demo>npm run dev

> antd-demo@1.0.0 dev D:\React Project\antd-demo
> dora -p 8001 --plugins atool-build,proxy

compilelistened on 8001
Anyproxy rule: dora-plugin-anyproxy
Anyproxy rules initialize finished, have fun!
temp certs cleared
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

rootCA generated at :
C:\Users\...\.anyproxy_certs

GUI interface started at : http://10.1.4.92:8002/
Http proxy started at 10.1.4.92:8989
0/1 build modulesrootCA generated
please trust the rootCA.crt in C:\Users\...\.anyproxy_certs\
or you may get it via anyproxy webinterface
AnyProxy is about to exit with code: 0

**Comment by Carrotzpc** [comment]
windows 下遇到了同样的问题，前几天还可以的，今天试了下就不行了

**Comment by gdzgshum** [comment]
windows   我也遇到同样问题  安装好openssl 还是一样的问题

**Comment by gdzgshum** [comment]
@lifesinger

**Comment by gdzgshum** [comment]
1.设置openssl   http://haohetao.iteye.com/blog/920532
2.加入全局变量
3.添加浏览器证书

**Comment by wjx8382** [comment]
谢谢@gdzgshum，安装了openssl和证书了以后，这个错误解决了，但是现在又报另一个错误
错误如下：

D:\React Project\antd-demo>npm run dev

> antd-demo@1.0.0 dev D:\React Project\antd-demo
> dora -p 8001 --plugins atool-build,proxy

compilelistened on 8001
Anyproxy rule: dora-plugin-anyproxy
Anyproxy rules initialize finished, have fun!
GUI interface started at : http://192.168.1.22:8002/
Http proxy started at 192.168.1.22:8989
0/1 build modules
webpack: bundle build is now finished.
Hash: 2fcecfdcdf160cb79d12
Version: webpack 1.12.9
Time: 650ms
        Asset     Size  Chunks             Chunk Names
    common.js  1.35 kB       0  [emitted]  common
common.js.map  1.34 kB       0  [emitted]  common
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]

ERROR in ./src/entry/index.jsx
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "base" at 0, attempted to resolve
relative to "D:\\React Project\\antd-demo\\src\\entry"
    at D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transf
ormation\file\options\option-manager.js:173:20)
    at OptionManager.mergeOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\trans
formation\file\options\option-manager.js:271:36)
    at OptionManager.init (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\file\options\option-manager.js:416:10)
    at File.initOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\
file\index.js:190:75)
    at new File (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\ind
ex.js:121:22)
    at Pipeline.transform (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\pipeline.js:42:16)
    at transpile (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:87:
14)

index.jsx是这样子的：
import '../common/lib';
import App from '../component/App';
import ReactDOM from 'react-dom';
import React from 'react';

ReactDOM.render(<App />, document.getElementById('react-content'));

**Comment by afc163** [comment]
index.jsx 有明显语法错误。

```jsx
ReactDOM.render(, document.getElementById('react-content'));
```

**Comment by wjx8382** [comment]
写错了，最后一句是这样子的：
ReactDOM.render(<<App />App />, document.getElementById('react-content'));

**Comment by wjx8382** [comment]
@afc163 index.jsx是这样子的：
```
import '../common/lib';
import App from '../component/App';
import ReactDOM from 'react-dom';
import React from 'react';

ReactDOM.render(<App />, document.getElementById('react-content'));
```
还是报这个错
```
ERROR in ./src/entry/index.jsx
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "base" at 0, attempted to resolve
```

**Comment by jj6335** [comment]
+1

**Comment by Joodysen** [comment]
+1

**Comment by afc163** [comment]
@sorrycc 是 npm2 的问题么？

**Comment by Carrotzpc** [comment]
安装 `add-module-exports` 试试
```
npm install babel-plugin-add-module-exports --save-dev
```

**Comment by afc163** [comment]
配置按照最新的初始化模板对照一下：https://github.com/ant-design/antd-init/blob/master/boilerplate/package.json

**Comment by wjx8382** [comment]
@afc163 我用了这个模板以后还是这个错

**Comment by wjx8382** [comment]
@Carrotzpc 安装完报这个错了
```
ERROR in ./src/entry/index.jsx
Module build failed: ReferenceError: Unknown plugin "react-transform" specified in "base" at 3, attempted to resolve rel
ative to "D:\\React Project\\antd-demo\\src\\entry"
    at D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transf
ormation\file\options\option-manager.js:173:20)
    at OptionManager.mergeOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\trans
formation\file\options\option-manager.js:271:36)
    at OptionManager.init (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\file\options\option-manager.js:416:10)
    at File.initOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\
file\index.js:190:75)
    at new File (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\ind
ex.js:121:22)
    at Pipeline.transform (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\pipeline.js:42:16)
    at transpile (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:87:
14)
 @ multi index

```

**Comment by Carrotzpc** [comment]
@wjx8382 我之前也遇到过这种老是提示`Unknown plugin`的错误，安装完一个又会出现另外一个，可以尝试将`node_modules`下面的依赖包全部删除，重新执行`npm install`，我的`node`版本是`v4.2.3`，`npm`版本是`2.14.7`

**Comment by sorrycc** [comment]
系统是 windows 下的?

**Comment by sorrycc** [comment]
windows 下可能有兼容问题，我给 antd-init 加个用例跑跑看。

**Comment by asxu** [comment]
难道大家都是mac  Linux 电脑？

**Comment by sorrycc** [comment]
rm 是 linux 的命令，windows 下肯定报错的。把 `package.json` 里的 build 改成 `atool-build` 试试。

**Comment by Carrotzpc** [comment]
@sorrycc 对，系统是win10的

**Comment by wjx8382** [comment]
我也是win10的

**Comment by wjx8382** [comment]
@Carrotzpc 删除node_modules总是提示源文件名长度大于文件系统支持的长度
除了用“把文件夹名字改成‘1’，然后打开文件继续改，一层一层改下去”这种方法，还有什么简单的方法吗？

**Comment by gdzgshum** [comment]
前几天我也在这问题，搞得我都放弃使用了  rm和文件名长度我都出现了

**Comment by benjycui** [comment]
@wjx8382 可以用黑科技 360 强行删除

**Comment by wjx8382** [comment]
![image](https://cloud.githubusercontent.com/assets/6300935/11830022/377ba572-a3dc-11e5-8f8a-024237cd5bdc.png)
我用这种方式删除了。。

**Comment by Carrotzpc** [comment]
可以在项目建一个空文件夹`temp`，然后用`robocoy`命令删除：
```
mkdir temp
robocopy temp node_modules /purge
```
参考：[http://www.jianshu.com/p/95a269951a1b](http://www.jianshu.com/p/95a269951a1b)

**Comment by wjx8382** [comment]
@Carrotzpc 删了重新npm install还是报Unknown plugin "add-module-exports"

**Comment by sorrycc** [comment]
我在 node@5, npm@3 下试了下没有问题。由于 openssl 和 linux 命令的原因，需要修改 `package.json`：

```diff
- "dev": "dora -p 8001 --plugins atool-build,proxy,hmr",
+ "dev": "dora -p 8001 --plugins atool-build,hmr",
- "build": "rm -rf dist && atool-build && mkdir -p dist/${npm_package_name}/${npm_package_version} && mv dist/*.* dist/${npm_package_name}/${npm_package_version}/"
+ "build": "atool-build"
```

**Comment by wjx8382** [comment]
@sorrycc 改了`package.json`之后还是报错
```
"start": "npm run dev",
"dev": "dora -p 8001 --plugins atool-build,hmr",
"lint": "eslint --ext .js,.jsx src",
"build": "atool-build"
```
```
D:\React Project\antd-demo>npm run dev

> antd-demo@1.0.0 dev D:\React Project\antd-demo
> dora -p 8001 --plugins atool-build,hmr

1/1 build modules           dora: listened on 8001
10/11 build modules
webpack: bundle build is now finished.
Hash: 6b43857c2b7a145fa810
Version: webpack 1.12.9
Time: 783ms
        Asset     Size  Chunks             Chunk Names
    common.js  23.3 kB       0  [emitted]  common
     index.js  13.8 kB    1, 0  [emitted]  index
common.js.map  24.7 kB       0  [emitted]  common
 index.js.map  17.7 kB    1, 0  [emitted]  index
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]
chunk    {1} index.js, index.js.map (index) 12.4 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] (webpack)/buildin/module.js 251 bytes {1} [built]
    [2] ./~/dora-plugin-hmr/~/webpack-hot-middleware/client-overlay.js 1.01 kB {1} [built]
    [3] ./~/dora-plugin-hmr/~/webpack-hot-middleware/client.js?path=http://127.0.0.1:8001/__webpack_hmr 3.24 kB {1} [bui
lt]
    [4] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/decode.js 2.4 kB {1} [built]
    [5] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/encode.js 2.09 kB {1} [built]
    [6] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/index.js 127 bytes {1} [built]
    [7] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/strip-ansi/index.js 161 bytes {1} [built]
    [8] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {1} [built]
    [9] ./~/dora-plugin-hmr/~/webpack-hot-middleware/process-update.js 2.95 kB {1} [built]

ERROR in ./src/entry/index.jsx
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "base" at 0, attempted to resolve
relative to "D:\\React Project\\antd-demo\\src\\entry"
    at D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transf
ormation\file\options\option-manager.js:173:20)
    at OptionManager.mergeOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\trans
formation\file\options\option-manager.js:271:36)
    at OptionManager.init (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\file\options\option-manager.js:416:10)
    at File.initOptions (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\
file\index.js:190:75)
    at new File (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformation\file\ind
ex.js:121:22)
    at Pipeline.transform (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-core\lib\transformatio
n\pipeline.js:42:16)
    at transpile (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\React Project\antd-demo\node_modules\atool-build\node_modules\babel-loader\index.js:87:
14)
 @ multi index

```

**Comment by sorrycc** [comment]
换 npm3 试试。

**Comment by wjx8382** [comment]
换了npm3还是报上面那个错

**Comment by afc163** [comment]
换 npm3 之后重新安装一下呢？`rm -rf node_modules && npm install`

**Comment by Carrotzpc** [comment]
@wjx8382 我用 koa + webpack 写了一个 [demo](https://github.com/Carrotzpc/ant-koa-demo)，基本满足前端开发需求，windows 坑太多，你可以试下：[https://github.com/Carrotzpc/ant-koa-demo](https://github.com/Carrotzpc/ant-koa-demo)

**Comment by wjx8382** [comment]
@afc163 现在可以了，太感谢了

**Comment by ljn20120715** [comment]
$ npm run dev

> antd-demo@1.0.0 dev D:\code\react_nodejs_example\antd-test
> dora -p 8001 --plugins atool-build,proxy,hmr

           dora: listened on 8001
          proxy: listened on 8989

webpack: bundle build is now finished.
Hash: 6b43857c2b7a145fa810
Version: webpack 1.12.9
Time: 614ms
        Asset     Size  Chunks             Chunk Names
    common.js  23.3 kB       0  [emitted]  common
     index.js  13.8 kB    1, 0  [emitted]  index
common.js.map  24.7 kB       0  [emitted]  common
 index.js.map  17.7 kB    1, 0  [emitted]  index
chunk    {0} common.js, common.js.map (common) 0 bytes [rendered]
chunk    {1} index.js, index.js.map (index) 12.4 kB {0} [rendered]
    [0] multi index 40 bytes {1} [built] [1 error]
    [1] (webpack)/buildin/module.js 251 bytes {1} [built]
    [2] ./~/dora-plugin-hmr/~/webpack-hot-middleware/client-overlay.js 1.01 k                     B {1} [built]
    [3] ./~/dora-plugin-hmr/~/webpack-hot-middleware/client.js?path=http://12                     7.0.0.1:8001/__webpack_hmr 3.24 kB {1} [built]
    [4] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/decode.js                      2.4 kB {1} [built]
    [5] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/encode.js                      2.09 kB {1} [built]
    [6] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/querystring/index.js 1                     27 bytes {1} [built]
    [7] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/strip-ansi/index.js 16                     1 bytes {1} [built]
    [8] ./~/dora-plugin-hmr/~/webpack-hot-middleware/~/strip-ansi/~/ansi-rege                     x/index.js 145 bytes {1} [built]
    [9] ./~/dora-plugin-hmr/~/webpack-hot-middleware/process-update.js 2.95 k                     B {1} [built]

ERROR in ./src/entry/index.jsx
Module build failed: ReferenceError: Unknown plugin "add-module-exports" spec                     ified in "base" at 0, attempted to resolve relative to "D:\\code\\react_nodej                     s_example\\antd-test\\src\\entry"
    at D:\code\react_nodejs_example\antd-test\node_modules\atool-build\node_m                     odules\babel-core\lib\transformation\file\options\option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (D:\code\react_nodejs_example\antd-test\node                     _modules\atool-build\node_modules\babel-core\lib\transformation\file\options\                     option-manager.js:173:20)
    at OptionManager.mergeOptions (D:\code\react_nodejs_example\antd-test\nod                     e_modules\atool-build\node_modules\babel-core\lib\transformation\file\options                     \option-manager.js:271:36)
    at OptionManager.init (D:\code\react_nodejs_example\antd-test\node_module                     s\atool-build\node_modules\babel-core\lib\transformation\file\options\option-                     manager.js:416:10)
    at File.initOptions (D:\code\react_nodejs_example\antd-test\node_modules\                     atool-build\node_modules\babel-core\lib\transformation\file\index.js:190:75)
    at new File (D:\code\react_nodejs_example\antd-test\node_modules\atool-bu                     ild\node_modules\babel-core\lib\transformation\file\index.js:121:22)
    at Pipeline.transform (D:\code\react_nodejs_example\antd-test\node_module                     s\atool-build\node_modules\babel-core\lib\transformation\pipeline.js:42:16)
    at transpile (D:\code\react_nodejs_example\antd-test\node_modules\atool-b                     uild\node_modules\babel-loader\index.js:14:22)
    at Object.module.exports (D:\code\react_nodejs_example\antd-test\node_mod                     ules\atool-build\node_modules\babel-loader\index.js:87:14)
 @ multi index

@wjx8382  我和你碰到了相同的问题，但是根据 @afc163 的建议rm -rf node_modules && npm install 之后，执行npm install 基本不动（替换成tnpm install，可以），但最终运行npm run dev，还是报和你一样的错Unknown plugin "add-module-exports" ，你是怎么弄的？

**Comment by sorrycc** [comment]
@ljn20120715  这个问题已知，还没修复，先换 npm3 解决。https://github.com/sorrycc/babel-core-resolve-enhance/issues/1

**Comment by ljn20120715** [comment]
我的环境是：
$ node -v 
v5.3.0
$ npm -v
3.3.12
$ tnpm -v
tnpm@2.14.2 (C:\Users\*****\AppData\Roaming\npm\node_modules\tnpm\bin\tnpm)
ali-npm@2.15.2
npm@2.14.7
node@5.3.0 (D:\Program Files\nodejs\node.exe)
prefix=C:\Users\*****\AppData\Roaming\npm (load prefix from: $ npm config get prefix)
win32 x64 6.1.7601

@sorrycc   npm3是指 npm用3版本吗？如果是的话，我的已经是3.3.12版本。

**Comment by sorrycc** [comment]
你用 tnpm 装的? 那需要确保 tnpm -v 的时候 npm 是 3 。 (tnpm i tnpm@3 -g)

**Comment by NameIsEward** [comment]
ERROR in ./src/entry/index.jsx
Module build failed: Error: Couldn't find preset "es2015" relative to directory
"F:\\web开发环境\\antd\\src\\entry"
    at OptionManager.mergePresets (F:\web开发环境\antd\node_modules\atool-build\
node_modules\babel-core\lib\transformation\file\options\option-manager.js:327:17
)
    at OptionManager.mergeOptions (F:\web开发环境\antd\node_modules\atool-build\
node_modules\babel-core\lib\transformation\file\options\option-manager.js:287:12
)
    at OptionManager.init (F:\web开发环境\antd\node_modules\atool-build\node_mod
ules\babel-core\lib\transformation\file\options\option-manager.js:416:10)
    at File.initOptions (F:\web开发环境\antd\node_modules\atool-build\node_modul
es\babel-core\lib\transformation\file\index.js:191:75)
    at new File (F:\web开发环境\antd\node_modules\atool-build\node_modules\babel
-core\lib\transformation\file\index.js:122:22)
    at Pipeline.transform (F:\web开发环境\antd\node_modules\atool-build\node_mod
ules\babel-core\lib\transformation\pipeline.js:42:16)
    at transpile (F:\web开发环境\antd\node_modules\atool-build\node_modules\babe
l-loader\index.js:14:22)
    at Object.module.exports (F:\web开发环境\antd\node_modules\atool-build\node_
modules\babel-loader\index.js:88:12)
 @ multi index

**Comment by benjycui** [comment]
@NameIsEward Google this: `Error: Couldn't find preset "es2015" relative to directory`

And read this please: https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md

**Comment by sorrycc** [comment]
`F:\web开发环境` 换个英文名试试

**Comment by lysnoter** [comment]
$ mkdir antd-demo && cd antd-demo
$ antd-init
$ npm install

最后一句：npm install是干嘛的?

**Comment by xueyuchen** [comment]
## 关于add-module-exports的错误
### 环境
1. node v5.3.0
2. npm 3.3.2
3. OSX 10.11.3

### 执行
```
npm run webpack-dev-server --devtool eval --progress --colors --port 9090 --hot --content-base dist
```
### 报错
```
ERROR in ./~/antd/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/local/workspace/react_editer/node_modules/antd/package.json" at 0, attempted to resolve relative to "/Users/local/workspace/react_editer/node_modules/antd"
    at /Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:182:20)
    at OptionManager.mergeOptions (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:36)
    at OptionManager.addConfig (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:10)
    at OptionManager.findConfigs (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:440:30)
    at OptionManager.init (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:482:12)
    at File.initOptions (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
 @ ./src/script/components/header.js 7:11-26

```

@afc163

**Comment by wulv** [comment]
error node v4.4.0
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error antd-demo@1.0.0 dev: `dora -p 8001 --plugins webpack,hmr,proxy,livereload?enableJs=false`
22 error Exit status 1
23 error Failed at the antd-demo@1.0.0 dev script 'dora -p 8001 --plugins webpack,hmr,proxy,livereload?enableJs=false'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the antd-demo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     dora -p 8001 --plugins webpack,hmr,proxy,livereload?enableJs=false
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs antd-demo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls antd-demo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by golden-hu** [comment]
我是npm3也报这个错了。直接从git-hub上拉的代码
