### ISSUE TITLE
最新的命令行工具初始化之后执行npm run dev报错

### ISSUE THREAD

**Issue by ReadingSteiner** [ant-design/ant-design#655]
昨天还是OK的，今天用最新的命令行工具init之后就报错了。
报错内容
```
compileevents.js:141
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::8001
    at Object.exports._errnoException (util.js:849:11)
    at exports._exceptionWithHostPort (util.js:872:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at createServer (/xxxx/xxxx/Desktop/app-xxxx-xx/node_modules/dora/lib/index.js:59:10)
    at Object.<anonymous> (/xxxx/xxxx/Desktop/app-xxxx-xxxx/node_modules/dora/bin/dora:11:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 14.5.0
npm ERR! argv "/xxxx/xxxx/git/nvm/versions/alinode/v4.1.2/bin/node" "/xxxx/xxxx/git/nvm/versions/alinode/v4.1.2/bin/npm" "run" "dev"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! antd-demo@1.0.0 dev: `dora -p 8001 --plugins atool-build,proxy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd-demo@1.0.0 dev script 'dora -p 8001 --plugins atool-build,proxy'.
npm ERR! This is most likely a problem with the antd-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     dora -p 8001 --plugins atool-build,proxy
npm ERR! You can get their info via:
npm ERR!     npm owner ls antd-demo
npm ERR! There is likely additional logging output above.
```

**Comment by afc163** [comment]
`Error: listen EADDRINUSE :::8001`

**Comment by ReadingSteiner** [comment]
。。居然没看到这个，好丢脸囧
