### ISSUE TITLE
webpack 配置问题 真的纠结好久

### ISSUE THREAD

**Issue by gdzgshum** [ant-design/ant-design#672]
F:\lv\webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import webpack fro
m 'webpack';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\w
ebpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:425:26)

我尝试很多方法，表面上看应该是babel没生效；
但是es2015，babel， babel-core 等我都安装了，还有我把文件名字都改成webpack.config.babel.js也不行

请问这个是什么问题呢？

**Comment by bang88** [comment]
@gdzgshum  
```js
require('babel/register');
```
现在node还不完全支持es6，需要注册babel 我这里用的是babel5

**Comment by afc163** [comment]
webpack 配置问题，建议去相关网站提问或搜索，可以获得更专业的响应。
