### ISSUE TITLE
Parse index.css 时报错

### ISSUE THREAD

**Issue by yubozhao** [ant-design/ant-design#696]
我用browserify 时
````
   While processing files with cosmos:browserify (for target web.browser):
   common/lib/app.browserify.js: Unexpected token (3:5) while parsing
   /Users/bo.yu/Development/Projects/Evil_Trunk/Development/Trunk/Tools/Dashboard/packages/npm-container/.npm/package/node_modules/antd/lib/index.css while parsing file:
   /Users/bo.yu/Development/Projects/Evil_Trunk/Development/Trunk/Tools/Dashboard/packages/npm-container/.npm/package/node_modules/antd/lib/index.css

   While processing files with cosmos:browserify (for target os.osx.x86_64):
   common/lib/app.browserify.js: Unexpected token (3:5) while parsing
   /Users/bo.yu/Development/Projects/Evil_Trunk/Development/Trunk/Tools/Dashboard/packages/npm-container/.npm/package/node_modules/antd/lib/index.css while parsing file:
   /Users/bo.yu/Development/Projects/Evil_Trunk/Development/Trunk/Tools/Dashboard/packages/npm-container/.npm/package/node_modules/antd/lib/index.css

=> Your application has errors. Waiting for file change.
````

**Comment by rayou** [comment]
透過 babel-register 進行轉換時也是遇到類似的問題

`import antd from 'antd'`

錯誤訊息:
```
/home/user/project/node_modules/antd/lib/index.css:2
html {
     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/project/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/project/node_modules/antd/lib/index.js:9:1)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/project/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/user/project/app/components/Login.js:13:13)
    at Module._compile (module.js:435:26)
    at loader (/home/user/project/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/user/project/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

暫時解決方式先透過 `import component from antd/lib/components` 的方式從資料夾載入，另外將 css 透過 sass 進行封裝。

**Comment by yubozhao** [comment]
@rayou 我现在用Meteor 没法向你那样解决。。。只能需要哪个component就单独去添加，然后拷贝styles

**Comment by afc163** [comment]
0.11 之后，样式不默认加载，可以自行引入。
