### ISSUE TITLE
Happypack with AntUI

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#7133]
### Version
2.12.5

### Environment
Mac OS Sierra, Newest Google Chrome

### Reproduction link
[https://github.com/ctrlplusb/react-universally](https://github.com/ctrlplusb/react-universally)

### Steps to reproduce
Trying to add `['import', { libraryName: 'antd', style: 'css' }]` to the `configFactory.js` file after for example line 411.

### What is expected?
Expecting to work properly - loading the CSS etc.

### What is actually happening?
It says that there is an unexpected token:
```
html {
     ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/NYC/Desktop/my-app/subdir/node_modules/antd/lib/menu/style/css.js:3:1)
```

**Comment by benjycui** [comment]
Make sure that you had used correct loader to handle CSS files.

**Comment by Ancinek** [comment]
The problem was with the particular boilerplate I was using (react universally). Wrapping the import statement in `ifDevClient` method (provided by that boilerplate) did the trick. Hope this helps someone!

**Comment by paranoidjk** [comment]
do you mean https://github.com/ant-design/babel-plugin-import do not handle it correctly?

Could you file a issue in babel-plugin-import with a reproducible demo?

**Comment by afc163** [comment]
You need css-loader for antd css files.
