### ISSUE TITLE
Unable to generate Snapshot for antd Table with Jest

### ISSUE THREAD

**Issue by ishantoberoi** [ant-design/ant-design#7318]
### Version
2.11.2

### Environment
react 15.4.2, jest 20.0.4

### Reproduction link
[https://github.com/ant-design/ant-design/issues/7317](https://github.com/ant-design/ant-design/issues/7317)

### Steps to reproduce
Try an generate Table Snapshot using Jest

### What is expected?
Snaphshot should be generated

### What is actually happening?
Error

TypeError: Cannot read property 'className' of undefined

      at Spin.componentDidMount (../node_modules/antd/lib/spin/index.js:93:49)
      at ../node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (../node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ../node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (../node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (../node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)

**Comment by yesmeck** [comment]
You need jsdom.

**Comment by ishantoberoi** [comment]
@yesmeck Yes default test Environment for jest ###jsdom

**Comment by djyde** [comment]
Since `Table` used `findDOMNode`, which is not supported in Jest. You could find some solutions in https://github.com/facebook/react/issues/7371

**Comment by ishantoberoi** [comment]
I have removed the Spin component from table.
Now it works well, without Spin Component.
