### ISSUE TITLE
Integrating with react-snapshot will cause "matchMedia not present" error with Carousel component

### ISSUE THREAD

**Issue by Songkeys** [ant-design/ant-design#7341]
### Version
2.12.7

### Environment
react 15.6.1

### Reproduction link
[https://github.com/Songkeys/create-react-app-with-react-snapshot-and-antd](https://github.com/Songkeys/create-react-app-with-react-snapshot-and-antd)

### Steps to reproduce
First, I followed the [use with create react app](https://ant.design/docs/react/use-with-create-react-app) to integrate `antd` with `create-react-app`. Then, I setup [react-snapshot](https://github.com/geelen/react-snapshot) correctly. Everything works fine with `App.js` code below:

```
import React, { Component } from 'react';
import Button from 'antd/lib/button';
import './App.css';

export default class App extends Component {
  render() {
    return (
      <div>
          <Button>123</Button>
      </div>
    );
  }
}
```

And the log printed in the terminal when use `yarn build` with `react-snapshot` showed success:
```
❯ yarn build
yarn build v0.27.5
$ react-scripts build && react-snapshot
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  56.22 KB (-9.17 KB)  build/static/js/main.061f03aa.js
  46.39 KB             build/static/css/main.10ddcd22.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

🕷   Starting crawling http://localhost:54327/
✏   Saving / as /index.html
🕸   Finished crawling.
Done in 15.05s.
```

---

But, when I tried to import the `Carousel` component into the project and build it, the error occurred.

`App.js`:
```
import React, { Component } from 'react';
import Carousel from 'antd/lib/carousel';
import './App.css';

export default class App extends Component {
  render() {
    return (
      <div>
        <Carousel>
          <div><h3>1</h3></div>
          <div><h3>2</h3></div>
          <div><h3>3</h3></div>
          <div><h3>4</h3></div>
        </Carousel>
      </div>
    );
  }
}
```

Terminal output when building:
```
❯ yarn build
yarn build v0.27.5
$ react-scripts build && react-snapshot
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  63.52 KB (+7.3 KB)  build/static/js/main.a9a116e7.js
  46.39 KB            build/static/css/main.10ddcd22.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

🕷   Starting crawling http://localhost:54853/
Error: Uncaught [Error: matchMedia not present, legacy browsers require a polyfill]
    at reportException (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/songkeys/snaptest/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/songkeys/snaptest/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13) Error: matchMedia not present, legacy browsers require a polyfill
    at new r (http://localhost:54853/static/js/main.a9a116e7.js:1:214187)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:214123)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:193869)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:192924)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:178894)
    at t (http://localhost:54853/static/js/main.a9a116e7.js:1:101)
    at Object.<anonymous> (http://localhost:54853/static/js/main.a9a116e7.js:1:177811)
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
🕸   Finished crawling.
Done in 15.53s.
```

===

Also, when i tried to use `yarn test`  with `Carousel` imported, test would fail:
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    matchMedia not present, legacy browsers require a polyfill
      
      at new MediaQueryDispatch (node_modules/enquire.js/src/MediaQueryDispatch.js:15:15)
      at Object.<anonymous> (node_modules/enquire.js/src/index.js:2:18)
      at Object.<anonymous> (node_modules/react-slick/lib/slider.js:37:38)
      at Object.<anonymous> (node_modules/react-slick/lib/index.js:3:18)
      at Object.<anonymous> (node_modules/antd/lib/carousel/index.js:31:19)
      at Object.<anonymous> (src/App.js:2:17)
      at Object.<anonymous> (src/App.test.js:3:12)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.09s
Ran all test suites.
```

### What is expected?
Build successfully.

### What is actually happening?
Build failed.

---
I have tried add polyfill files descried here: [https://ant.design/docs/react/getting-started#Compatibility](https://ant.design/docs/react/getting-started#Compatibility). But it doesn't work for me.
Could anyone help me please or if you met any similar problems ever. Thanks a lot!

**Comment by afc163** [comment]
similar to https://github.com/ant-design/ant-design/issues/6560

**Comment by afc163** [comment]
https://github.com/geelen/react-snapshot/issues/33

**Comment by Songkeys** [comment]
@afc163 
Yes, I have searched for a long time and read what you referred but still not clear what is the right way to solve this. :(
(Or, is there any other way to generate static HTML files for SEO? Thanks.)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3308#issuecomment-325182753
