### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhangporco** [ant-design/ant-design#7515]
ERROR in ./node_modules/attr-accept/dist/index.js
Module build failed: ReferenceError: [BABEL] /Users/porco/gitProgram/node/woas-admin/node_modules/attr-accept/dist/index.js: Using removed Babel 5 option: /Users/porco/gitProgram/node/woas-admin/node_modules/attr-accept/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/porco/gitProgram/node/woas-admin/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/porco/gitProgram/node/woas-admin/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:419:13)
 @ ./node_modules/rc-upload/es/AjaxUploader.js 51:18-40
 @ ./node_modules/rc-upload/es/Upload.js
 @ ./node_modules/rc-upload/es/index.js
 @ ./node_modules/antd/es/upload/Upload.js
 @ ./node_modules/antd/es/upload/index.js
 @ ./node_modules/antd/es/index.js
 @ ./src/app/index.jsx
 @ multi babel-polyfill ./src/app/index.jsx

**Comment by zhayes** [comment]
我遇到了同样的问题在 引入 Upload type='picture-card'  组件 编译的时候报错，请问 解决了吗？

**Comment by xiashuyuan** [comment]
请问这个issue的问题解决了吗？ @ant-design-bot

**Comment by zhayes** [comment]
@xiashuyuan 最新的 2.13.x 的版本貌似对 Upload 做了修改。 你换个 2.12.7 版本试试！
去 其官方仓库 提提问题[https://github.com/ant-design/ant-design/issues?utf8=%E2%9C%93&q=upload%20]( https://github.com/ant-design/ant-design/issues?utf8=%E2%9C%93&q=upload%20)

**Comment by afc163** [comment]
https://github.com/GankLun/FirstDemo/pull/1
