### ISSUE TITLE
Test timeout sometimes

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8171]
```
  ● Upload › return promise in beforeUpload

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/_jest-jasmine2@21.2.1@jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/_jsdom@9.12.0@jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)
```

https://github.com/ant-design/ant-design/commit/54188b8e9754b1213b1416036489844f20d68bf6 not working.

**Comment by yesmeck** [comment]
https://github.com/facebook/jest/issues/4019

**Comment by okoala** [comment]
用 `jest.setTimeout` 直接整体加大超时时间吧~ 不用设置各种 timer 了

**Comment by afc163** [comment]
最近好像都没有重现了。
