### ISSUE TITLE
 Couldn't find preset "stage-0"

### ISSUE THREAD

**Issue by jx-luoluo** [ant-design/ant-design#819]
我引用 antd 并用 webpack 编译时报错如下：
```
ERROR in ./~/antd/lib/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/antd"
    at OptionManager.mergePresets (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:30)
    at OptionManager.init (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/luoluo/Documents/vobile-in/lotman/manage-frontend/node_modules/babel-loader/index.js:88:12)
 @ ./static/src/program_list.jsx 6:0-15
```

webpack.config.js
```javascript
var Clean = require('clean-webpack-plugin')
    , path = require('path');
module.exports = {
    entry:{
        programList: './static/src/program_list.jsx'
    },
    output: {
        path: './dist',
        filename: '[name].bundle.js',
        publicPath: './dist/'
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            {
                test: /\.less$/,
                loader: "style!css!less"
            },
            {
                test: /\.png$/,
                loader: "url-loader?mimetype=image/png,limit=1"
            },
            {
                test: /\.(ttf|eot|svg|woff)$/,
                loader: "file-loader"
            },
            {
                test: /\.jsx?$/,
                loader: 'babel?presets[]=react,presets[]=es2015' // 'babel-loader' is also a legal name to reference
            },
            {
                test:/jquery.min\.js$/,
                loader:"expose?$!expose?jQuery"
            }
        ],

        plugins: [
            new Clean(['dist'])
        ]
    },
    resolve: {
        alias:{ jquery: "jquery/jquery.min.js" }
    },
    amd: { jQuery: true }
};
```
引用
```javascript
require('antd')
```

请问下这个问题要怎么解决呢，是我少下了什么模块吗？

**Comment by benjycui** [comment]
Try `rm -rf node_modules && npm i`

**Comment by jx-luoluo** [comment]
刚想说，已解决。@benjycui  非常感谢。

**Comment by teamrun** [comment]
```
ERROR in ./~/antd/lib/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory 
"/Users/chenllos/dev/nice-repo/antd-tree-shaking/node_modules/antd"
``` 
错误又出现了

`antd`声明的stage-0依赖在devDependency中, 引用antd包来使用的自己的项目, 在安装antd时是不会安装devDep的

是不是应该把stage-0移出devDep 放进dep 或者直接不依赖它...

**Comment by teamrun** [comment]
刚刚安装的 版本号: `antd@0.12.11`

**Comment by benjycui** [comment]
@teamrun 建议使用 antd-init 新建项目。

**Comment by teamrun** [comment]
好的, 了解了~
