### ISSUE TITLE
关于ant-design 2.13.1版本使用Upload组件编译打包报错的问题

### ISSUE THREAD

**Issue by GankLun** [ant-design/ant-design#8209]
[`](  http://new-issue.ant.design)
ERROR in ./node_modules/_attr-accept@1.1.0@attr-accept/dist/index.js
Module build failed: ReferenceError: [BABEL] C:\Users\Administrator\Desktop\FEK\node_modules\_attr-accept@1.1.0@attr-accept\dist\index.js: Using removed Babel 5 o
ption: C:\Users\Administrator\Desktop\FEK\node_modules\_attr-accept@1.1.0@attr-accept\.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.
io/docs/plugins/#presets
    at Logger.error (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\options\option-manager.js
:220:20)
    at OptionManager.init (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\options\option-manager.js:368:12)

    at File.initOptions (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-core@6.26.0@babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-loader@7.1.2@babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\Administrator\Desktop\FEK\node_modules\_babel-loader@7.1.2@babel-loader\lib\index.js:175:20)
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/AjaxUploader.js 51:18-40
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/Upload.js
 @ ./node_modules/_rc-upload@2.4.3@rc-upload/es/index.js
 @ ./node_modules/_antd@2.13.9@antd/lib/upload/Upload.js
 @ ./node_modules/_antd@2.13.9@antd/lib/upload/index.js
 @ ./src/detail/index.js
 @ ./src/routes/route.js
 @ ./src/app/index.js
 @ ./src/home/home.js
 @ ./src/routes/index.js
 @ ./src/index.js
 @ multi ./node_modules/_webpack-dev-server@2.9.4@webpack-dev-server/client?http://localhost:3002 ./src/index.js

**Comment by afc163** [comment]
Try 2.13.10
