### ISSUE TITLE
npm run site with errors

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#8249]
branch: antd-3.0

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'ReactDOM'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:1:611)
    at a (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:1:174)
    at Object.exports.ssr.Object.defineProperty.value (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:35:777188)
    at a (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:1:174)
    at Object.exports.ssr.Object.defineProperty.value (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:35:775961)
    at a (/Users/afc163/Projects/ant-design/node_modules/_bisheng@0.27.6@bisheng/tmp/index-ssr.js:1:174)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd@3.0.0-rc.1 site: `cross-env NODE_ENV=production bisheng build --ssr -c ./site/bisheng.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the antd@3.0.0-rc.1 site script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/afc163/.npm/_logs/2017-11-20T13_32_15_766Z-debug.log
```

**Comment by benjycui** [comment]
看下你本地，这一行代码是否和线上的不一样 https://github.com/ant-design/ant-design/blob/master/site/bisheng.config.js#L77

**Comment by afc163** [comment]
antd-3.0

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/f02cd9cd529e92c126b9905370485147b9b01e92

**Comment by jljsj33** [comment]
🤣
