### ISSUE TITLE
Menu.Item throws an error in SSR due to Tooltip.

### ISSUE THREAD

**Issue by mitjade** [ant-design/ant-design#8458]
### Version
3.0.0

### Environment
Mac OS and Linux

### Steps to reproduce
Somewhere between v3 beta 6 and 7, `Menu.Item` started throwing errors in SSR. Replacing `Menu.Item` with `rc-menu` `Item` when doing SSR, fixes the problem.

### What is expected?
Removing Tooltip when doing SSR.

### What is actually happening?
Actual error is thrown in `react-apollo`:
```
backend error { TypeError: Cannot read property 'type' of undefined
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:8:29)
    at .../node_modules/react-apollo/getDataFromTree.js:45:56
    at Array.forEach (<anonymous>)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:45:23)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:48:17)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:48:17)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:48:17)
    at .../node_modules/react-apollo/getDataFromTree.js:59:21
    at forEachSingleChild (.../node_modules/react/cjs/react.development.js:839:8)
    at traverseAllChildrenImpl (.../node_modules/react/cjs/react.development.js:743:5)
    at traverseAllChildrenImpl (.../node_modules/react/cjs/react.development.js:759:23)
    at traverseAllChildren (.../node_modules/react/cjs/react.development.js:814:10)
    at Object.forEachChildren [as forEach] (.../node_modules/react/cjs/react.development.js:859:3)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:57:22)
    at walkTree (.../node_modules/react-apollo/getDataFromTree.js:48:17)
```

---
We ware able to do a workaround like so https://github.com/sysgears/apollo-universal-starter-kit/commit/28344b9bf2fc730555b3774d611bfd1bfc440360, but would really like to get this working without it.

**Comment by mitjade** [comment]
Fixed with https://github.com/apollographql/react-apollo/commit/fc36ac8d4b30b8909559837a85a5bf1dea3134a5
