### ISSUE TITLE
这个是什么错误？

### ISSUE THREAD

**Issue by ugvgylkm** [ant-design/ant-design#892]
版本 0.11.3
按照下面引用但是报错
import { Carousel } from 'antd';
ReactDOM.render(
  《Carousel vertical="true"》
    《div》《h3》1</h3></div>
    《div》《h3》2</h3></div>
    《div》《h3》3</h3></div>
    《div》《h3》4</h3></div>
  《/Carousel>
, mountNode);

报下面错误。

/~/antd/lib/index.js
Module build failed: ReferenceError: [BABEL] F:\node\dahua\webpack-react\node_modules\antd\lib\index.js: Unknown option: F:\node\dahua\webpack-react\node_modules\antd\package.json.presets
    at Logger.error (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:171:32)
    at OptionManager.init (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (F:\node\dahua\webpack-react\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at transpile (F:\node\dahua\webpack-react\node_modules\babel-loader\index.js:11:22)
    at Object.module.exports (F:\node\dahua\webpack-react\node_modules\babel-loader\index.js:70:12)
 @ ./app/main.js 19:12-27

**Comment by benjycui** [comment]
1. 不是 antd 的问题
1. Google "Unknown option: package.json.presets" 你会找到答案
1. 麻烦阅读下 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)
1. 麻烦学习一下 Markdown
