### ISSUE TITLE
can not run with npm start

### ISSUE THREAD

**Issue by WingGao** [ant-design/ant-design#9524]
### Version
3.2.3

### Environment
node 8.9.1

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1. clone repo
2. yarn
3. yarn start

### What is expected?
run success

### What is actually happening?
```
ant-design git:(patch-2) npm start

> antd@3.2.3 start /Users/suamo/Projs/ant-design
> rimraf _site && node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js

/Users/suamo/Projs/ant-design/site/bisheng.config.js:9
  rules.forEach((rule) => {
        ^

TypeError: Cannot read property 'forEach' of undefined
    at alertBabelConfig (/Users/suamo/Projs/ant-design/site/bisheng.config.js:9:9)
    at Object.webpackConfig (/Users/suamo/Projs/ant-design/site/bisheng.config.js:108:5)
    at updateWebpackConfig (/Users/suamo/Projs/ant-design/node_modules/bisheng/lib/utils/update-webpack-config.js:28:47)
    at Object.webpackUpdateConfig (/Users/suamo/Projs/ant-design/node_modules/bisheng/lib/dora-plugin-bisheng.js:7:12)
    at ret (/Users/suamo/Projs/ant-design/node_modules/dora/lib/plugin.js:152:29)
    at run (/Users/suamo/Projs/ant-design/node_modules/dora/lib/reduceAsync.js:21:5)
    at next (/Users/suamo/Projs/ant-design/node_modules/dora/lib/reduceAsync.js:14:14)
    at /Users/suamo/Projs/ant-design/node_modules/dora/lib/reduceAsync.js:26:7
    at ret (/Users/suamo/Projs/ant-design/node_modules/dora/lib/plugin.js:124:23)
    at run (/Users/suamo/Projs/ant-design/node_modules/dora/lib/reduceAsync.js:21:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd@3.2.3 start: `rimraf _site && node ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@3.2.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/suamo/.npm/_logs/2018-03-05T07_49_47_737Z-debug.log
```

**Comment by denvist** [comment]
Seems like `config.module.rules` are empty

**Comment by yutingzhao1991** [comment]
I can't reproduce this issue, can you try to give more infomation about this ( like print the `config` ).

And try to reinstall node_module and make sure it has been installed completely。

**Comment by WingGao** [comment]
@yutingzhao1991 
Here is the config object in `webpackConfig(config) {...}` function.
```js
{ babel:
   { cacheDirectory: '/var/folders/h5/nvnzc1tj0r77qsv2pz6rn0940000gn/T',
     presets:
      [ '/Users/suamo/Projs/ant-design/node_modules/babel-preset-es2015-ie/index.js',
        '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules/babel-preset-react/index.js',
        '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules/babel-preset-stage-0/index.js' ],
     plugins:
      [ '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules/babel-plugin-add-module-exports/lib/index.js',
        '/Users/suamo/Projs/ant-design/node_modules/babel-plugin-transform-decorators-legacy/lib/index.js' ] },
  ts:
   { transpileOnly: true,
     compilerOptions:
      { target: 'es6',
        jsx: 'preserve',
        moduleResolution: 'node',
        declaration: false,
        sourceMap: true } },
  output:
   { path: '/Users/suamo/Projs/ant-design/dist/',
     filename: '[name].js',
     chunkFilename: '[name].js',
     publicPath: '/' },
  devtool: '#cheap-module-source-map',
  resolve:
   { modulesDirectories:
      [ 'node_modules',
        '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules' ],
     extensions:
      [ '',
        '.web.tsx',
        '.web.ts',
        '.web.jsx',
        '.web.js',
        '.ts',
        '.tsx',
        '.js',
        '.jsx',
        '.json' ] },
  resolveLoader:
   { modulesDirectories:
      [ 'node_modules',
        '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules' ] },
  entry: {},
  node:
   { child_process: 'empty',
     cluster: 'empty',
     dgram: 'empty',
     dns: 'empty',
     fs: 'empty',
     module: 'empty',
     net: 'empty',
     readline: 'empty',
     repl: 'empty',
     tls: 'empty' },
  module:
   { noParse: [ /moment.js/ ],
     loaders:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  postcss:
   [ Processor {
       version: '5.2.18',
       plugins: [Array],
       postcssPlugin: 'rucksack',
       postcssVersion: '5.2.18' },
     { [Function: plugin]
       options: [Object],
       info: [Function],
       postcssPlugin: 'autoprefixer',
       postcssVersion: '5.2.18' } ],
  plugins:
   [ CommonsChunkPlugin {
       chunkNames: 'common',
       filenameTemplate: 'common.js',
       minChunks: undefined,
       selectedChunks: undefined,
       ident: '/Users/suamo/Projs/ant-design/node_modules/atool-build/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js0' },
     ExtractTextPlugin { filename: '[name].css', options: [Object], id: 1 },
     OccurrenceOrderPlugin { preferEntry: undefined },
     ProgressPlugin { handler: [Function] } ] }
```

**Comment by yesmeck** [comment]
Reinstall node_modules.

**Comment by WingGao** [comment]
@yesmeck `npm` is ok, but `yarn` was not.

**Comment by yesmeck** [comment]
Remove yarn.lock and reinstall.
