### ISSUE TITLE
ant.design 不能编译成功

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#961]
我下载的是antd-0.11.3 源码

1 用atool-build编译
atool-build --config webpack.antd.config.js 

/usr/local/node/lib/node_modules/atool-build/lib/mergeCustomConfig.js:28
  throw new Error('Return of ' + customConfigPath + ' must be a function.');
  ^

Error: Return of /home/root1/wangyun/ant-design-0.11.3/webpack.antd.config.js must be a function.
    at mergeCustomConfig (/usr/local/node/lib/node_modules/atool-build/lib/mergeCustomConfig.js:28:9)
    at getWebpackConfig (/usr/local/node/lib/node_modules/atool-build/lib/build.js:102:51)
    at exports.default (/usr/local/node/lib/node_modules/atool-build/lib/build.js:11:23)
    at Object.<anonymous> (/usr/local/node/lib/node_modules/atool-build/bin/atool-build:15:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

2 用webpack编译
webpack --config webpack.antd.config.js 

也是各种错误

webpack --config webpack.config.js
Hash: 861ec26824f86f50dc52
Version: webpack 1.12.2
Time: 1402ms
    + 1 hidden modules

ERROR in Loader /home/root1/wangyun/ant-design-0.11.3/node_modules/babel/index.js?{"presets":["es2015","react","stage-0"],"plugins":["add-module-exports"]} didn't return a function

**Comment by afc163** [comment]
http://ant.design/docs/react/getting-started

业务文件打包，可以参照文档进行操作。

**Comment by afc163** [comment]
`webpack --config webpack.antd.config.js` 报错，可以试试重新安装依赖。

**Comment by xueyuchen** [comment]
### 关于add-module-exports的错误
执行
```
npm run webpack-dev-server --devtool eval --progress --colors --port 9090 --hot --content-base dist
```
报错
```
ERROR in ./~/antd/lib/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/local/workspace/react_editer/node_modules/antd/package.json" at 0, attempted to resolve relative to "/Users/local/workspace/react_editer/node_modules/antd"
    at /Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:182:20)
    at OptionManager.mergeOptions (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:36)
    at OptionManager.addConfig (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:10)
    at OptionManager.findConfigs (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:440:30)
    at OptionManager.init (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:482:12)
    at File.initOptions (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/local/workspace/react_editer/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
 @ ./src/script/components/header.js 7:11-26

```
