### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by a6965921** [ant-design/ant-design#964]
qdeMacBook-Pro:antdesign gqgq$ npm install antd-init -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ antd-init@0.6.2 
  ├─┬ through2@2.0.0 
  │ ├─┬ readable-stream@2.0.5 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── inherits@2.0.1 
  │ │ ├── isarray@0.0.1 
  │ │ ├── process-nextick-args@1.0.6 
  │ │ ├── string_decoder@0.10.31 
  │ │ └── util-deprecate@1.0.2 
  │ └── xtend@4.0.1 
  ├─┬ vinyl-fs@2.2.1 
  │ ├─┬ duplexify@3.4.2 
  │ │ └─┬ end-of-stream@1.0.0 
  │ │   └─┬ once@1.3.3 
  │ │     └── wrappy@1.0.1 
  │ ├─┬ glob-stream@5.3.1 
  │ │ ├── extend@3.0.0 
  │ │ ├─┬ glob@5.0.15 
  │ │ │ ├── inflight@1.0.4 
  │ │ │ ├─┬ minimatch@3.0.0 
  │ │ │ │ └─┬ brace-expansion@1.1.2 
  │ │ │ │   ├── balanced-match@0.3.0 
  │ │ │ │   └── concat-map@0.0.1 
  │ │ │ └── path-is-absolute@1.0.0 
  │ │ ├─┬ glob-parent@2.0.0 
  │ │ │ └── is-glob@2.0.1 
  │ │ ├─┬ micromatch@2.3.7 
  │ │ │ ├─┬ arr-diff@2.0.0 
  │ │ │ │ └── arr-flatten@1.0.1 
  │ │ │ ├── array-unique@0.2.1 
  │ │ │ ├─┬ braces@1.8.3 
  │ │ │ │ ├─┬ expand-range@1.8.1 
  │ │ │ │ │ └─┬ fill-range@2.2.3 
  │ │ │ │ │   ├── is-number@2.1.0 
  │ │ │ │ │   ├── isobject@2.0.0 
  │ │ │ │ │   ├── randomatic@1.1.5 
  │ │ │ │ │   └── repeat-string@1.5.2 
  │ │ │ │ ├── preserve@0.2.0 
  │ │ │ │ └── repeat-element@1.1.2 
  │ │ │ ├── expand-brackets@0.1.4 
  │ │ │ ├── extglob@0.3.2 
  │ │ │ ├── filename-regex@2.0.0 
  │ │ │ ├── is-extglob@1.0.0 
  │ │ │ ├─┬ kind-of@3.0.2 
  │ │ │ │ └── is-buffer@1.1.2 
  │ │ │ ├── normalize-path@2.0.1 
  │ │ │ ├─┬ object.omit@2.0.0 
  │ │ │ │ ├─┬ for-own@0.1.3 
  │ │ │ │ │ └── for-in@0.1.4 
  │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ ├─┬ parse-glob@3.0.4 
  │ │ │ │ ├── glob-base@0.3.0 
  │ │ │ │ └── is-dotfile@1.0.2 
  │ │ │ └─┬ regex-cache@0.4.2 
  │ │ │   ├── is-equal-shallow@0.1.3 
  │ │ │   └── is-primitive@2.0.0 
  │ │ ├─┬ ordered-read-streams@0.3.0 
  │ │ │ └── is-stream@1.0.1 
  │ │ ├─┬ through2@0.6.5 
  │ │ │ └── readable-stream@1.0.33 
  │ │ ├─┬ to-absolute-glob@0.1.1 
  │ │ │ └── extend-shallow@2.0.1 
  │ │ └── unique-stream@2.2.0 
  │ ├── graceful-fs@4.1.2 
  │ ├─┬ gulp-sourcemaps@1.6.0 
  │ │ └── convert-source-map@1.1.3 
  │ ├── is-valid-glob@0.3.0 
  │ ├── merge-stream@1.0.0 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├── object-assign@4.0.1 
  │ ├─┬ strip-bom@2.0.0 
  │ │ └── is-utf8@0.2.1 
  │ ├─┬ strip-bom-stream@1.0.0 
  │ │ └── first-chunk-stream@1.0.0 
  │ ├── through2-filter@2.0.0 
  │ └─┬ vinyl@1.1.1 
  │   ├── clone@1.0.2 
  │   ├── clone-stats@0.0.1 
  │   └── replace-ext@0.0.1 
  └─┬ which@1.2.4 
    ├─┬ is-absolute@0.1.7 
    │ └── is-relative@0.1.3 
    └── isexe@1.1.1 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "antd-init" "-g"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/antdesign/npm-debug.log
gqdeMacBook-Pro:antdesign gqgq$ sudo npm install antd-init -g
sudo: cannot get working directory
Password:
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
gqdeMacBook-Pro:antdesign gqgq$ sudo npm install antd-init -g
sudo: cannot get working directory
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
gqdeMacBook-Pro:antdesign gqgq$ sudo npm install antd-init -g
sudo: cannot get working directory
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
gqdeMacBook-Pro:antdesign gqgq$ npm install antd-init -g
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:250:17)
    at Function.Module._resolveFilename (module.js:317:31)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)

**Comment by afc163** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions
